[book]
title = "repoweave"
authors = ["cwalv"]
language = "en"
src = "docs"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/cwalv/repoweave"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
