//! Repoweave's own adoption of the derived-content merge policy, exercised as
//! a land.
//!
//! Repoweave commits `.gitattributes` lines
//! declaring `docs/reference/{explain,schemas,prime}` derived, and a land
//! conflict in one of those paths then resolves mechanically — after which the
//! repo's own drift gate is what forces the regeneration commit. Until this,
//! the rule was prose repeated in every piece of standing guidance: "on a land
//! conflict take either side, re-run the generator, commit the regen."
//!
//! ## Why the fixture is shaped the way it is
//!
//! The definition half of the primitive can reach a replay by two routes: the
//! `DerivedContentPolicy` the call site states, and the durable
//! `merge.rwv-ours.driver` config `plant_rwv_merge_driver_config` writes.
//! `verify_replay_exclusion_invariant` plants that config in the **project**
//! repo before every rebase-strategy phase, so a fixture that watched a
//! declared path resolve *there* would pass whether or not anything stated a
//! policy.
//!
//! So the subject here is a **manifest** repo, which never receives the plant
//! — and [`assert_no_durable_definition`] says so out loud before every sync,
//! because that absence is what leaves the stated policy as the only route.
//! That is also the honest model of repoweave itself: repoweave is a managed
//! repo inside a weave, not the project repo of one, so its declarations are
//! honored through `apply_strategy`'s replays and nothing else.
//!
//! The declaration under test is repoweave's real one. [`declared_paths`]
//! reads the committed `.gitattributes` from the source tree and the fixture
//! commits those exact bytes, so the globs git evaluates here are the globs
//! git evaluates in the repo — including the `templates/` carve-out, which
//! [`the_templates_the_generator_reads_stay_authored`] holds to its claim.

use assert_cmd::Command as AssertCommand;
use repoweave::git::{git_vcs, has_rwv_merge_driver_config};
use repoweave::vcs::ConflictOp;
use std::path::{Path, PathBuf};

mod common;

// ---------------------------------------------------------------------------
// The paths repoweave declares derived
// ---------------------------------------------------------------------------

/// Repoweave's committed `.gitattributes` — the adoption itself.
fn declared_paths() -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(".gitattributes");
    std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "repoweave must declare its derived paths in {}: {e}",
            path.display()
        )
    })
}

/// A generated page under `docs/reference/explain/`, and the fixture's stand-in
/// for every artifact `generate-explain` writes.
const ARTIFACT: &str = "docs/reference/explain/index.md";

/// The source of record `ARTIFACT` is derived from. Authored, and deliberately
/// outside the declaration.
const TEMPLATES: &str = "docs/reference/explain/templates";

#[test]
fn repoweave_declares_its_generated_reference_artifacts_derived() {
    let attrs = declared_paths();
    for dir in [
        "docs/reference/explain",
        "docs/reference/schemas",
        "docs/reference/prime",
    ] {
        let needle = format!("{dir}/**");
        assert!(
            attrs.lines().any(|l| {
                let l = l.trim();
                !l.starts_with('#') && l.starts_with(&needle) && l.ends_with("merge=rwv-ours")
            }),
            "`{dir}` is regenerated by `cargo run --bin generate-explain` and \
             the drift gate blocks on it, so a land conflict there has no \
             answer worth adjudicating — it must be declared `merge=rwv-ours`. \
             Got:\n{attrs}"
        );
    }
}

// ---------------------------------------------------------------------------
// Git + rwv helpers
// ---------------------------------------------------------------------------

fn git(args: &[&str], dir: &Path) {
    let out = common::git()
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "Test")
        .env("GIT_AUTHOR_EMAIL", "test@test.com")
        .env("GIT_COMMITTER_NAME", "Test")
        .env("GIT_COMMITTER_EMAIL", "test@test.com")
        .output()
        .expect("git command failed to start");
    assert!(
        out.status.success(),
        "git {:?} in {} failed:\n{}",
        args,
        dir.display(),
        String::from_utf8_lossy(&out.stderr)
    );
}

fn git_out(args: &[&str], dir: &Path) -> String {
    let out = common::git()
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "Test")
        .env("GIT_AUTHOR_EMAIL", "test@test.com")
        .env("GIT_COMMITTER_NAME", "Test")
        .env("GIT_COMMITTER_EMAIL", "test@test.com")
        .output()
        .expect("git command failed to start");
    assert!(
        out.status.success(),
        "git {:?} in {} failed:\n{}",
        args,
        dir.display(),
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).unwrap().trim().to_string()
}

fn rwv() -> AssertCommand {
    common::rwv()
}

fn write(repo: &Path, rel: &str, contents: &str) {
    let path = repo.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, contents).unwrap();
}

fn read(repo: &Path, rel: &str) -> String {
    common::read_normalized(repo.join(rel))
}

// ---------------------------------------------------------------------------
// The generator, and the gate that blocks on its output
// ---------------------------------------------------------------------------

/// The fixture's generator: [`ARTIFACT`] is the sorted list of the verbs that
/// have a template. It reads the source directory rather than being handed its
/// answer, so "stale" here means what it means in repoweave — the committed
/// artifact does not match what the sources now imply.
fn regenerate(repo: &Path) {
    let mut verbs: Vec<String> = std::fs::read_dir(repo.join(TEMPLATES))
        .expect("the source of record must exist")
        .map(|e| {
            e.unwrap()
                .file_name()
                .to_string_lossy()
                .trim_end_matches(".md.tmpl")
                .to_owned()
        })
        .collect();
    verbs.sort();
    let body: String = verbs.iter().map(|v| format!("- {v}\n")).collect();
    write(repo, ARTIFACT, &format!("# Verbs\n\n{body}"));
}

/// `scripts/ci-local.sh`'s final stage, in miniature: regenerate, then diff the
/// working tree against the index. Blocking, and the only thing that makes a
/// mechanical side-pick safe — the pick is allowed to be wrong because this
/// refuses to let a wrong one ship.
fn drift_gate(repo: &Path) -> Result<(), String> {
    regenerate(repo);
    let out = common::git()
        .args(["diff", "--exit-code", "--", "docs/reference/"])
        .current_dir(repo)
        .output()
        .expect("git diff failed to start");
    if out.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&out.stdout).into_owned())
    }
}

// ---------------------------------------------------------------------------
// Workspace fixture
// ---------------------------------------------------------------------------

const MANAGED_REPO: &str = "github/org/docs-tool";
const PROJECT: &str = "app";

struct Workspace {
    root: PathBuf,
    managed_repo: PathBuf,
}

fn init_repo(path: &Path) -> String {
    std::fs::create_dir_all(path).unwrap();
    git(&["init", "-b", "main"], path);
    git(&["config", "user.email", "test@test.com"], path);
    git(&["config", "user.name", "Test"], path);
    write(path, "README.md", "init\n");
    git(&["add", "."], path);
    git(&["commit", "-m", "initial"], path);
    git_out(&["rev-parse", "HEAD"], path)
}

/// The primary workspace, whose one managed repo generates reference pages
/// from templates the way repoweave does.
///
/// `declare` chooses whether that repo commits repoweave's real
/// `.gitattributes`. It is the only difference between
/// [`a_land_conflict_in_a_generated_artifact_resolves_mechanically`] and
/// [`the_same_land_conflict_without_the_declaration_stops_the_sync`]: same
/// paths, same commits, same operation.
fn make_primary(tmp: &Path, declare: bool) -> Workspace {
    let ws = tmp.join("ws");
    let managed_repo = ws.join(MANAGED_REPO);
    init_repo(&managed_repo);

    if declare {
        write(&managed_repo, ".gitattributes", &declared_paths());
    }
    write(
        &managed_repo,
        &format!("{TEMPLATES}/land.md.tmpl"),
        "land\n",
    );
    regenerate(&managed_repo);
    git(&["add", "."], &managed_repo);
    git(
        &["commit", "-m", "docs: generate the reference index"],
        &managed_repo,
    );
    let managed_sha = git_out(&["rev-parse", "HEAD"], &managed_repo);

    let project_dir = ws.join("projects").join(PROJECT);
    init_repo(&project_dir);
    // The lock's own replay exclusion, which `--strategy rebase` requires.
    write(&project_dir, ".gitattributes", "rwv.lock merge=rwv-ours\n");
    write(
        &project_dir,
        "rwv.toml",
        &format!(
            "[repositories.\"{MANAGED_REPO}\"]\ntype = \"git\"\nurl = \"file://{repo}\"\nversion = \"main\"\nrole = \"owned\"\n",
            repo = common::url_path(&managed_repo)
        ),
    );
    write(
        &project_dir,
        "rwv.lock",
        &format!(
            "[repositories.\"{MANAGED_REPO}\"]\ntype = \"git\"\nurl = \"file://{repo}\"\nversion = \"{managed_sha}\"\n",
            repo = common::url_path(&managed_repo)
        ),
    );
    git(
        &["add", ".gitattributes", "rwv.toml", "rwv.lock"],
        &project_dir,
    );
    git(&["commit", "-m", "lock: initial"], &project_dir);

    write(&ws, ".rwv-active", &format!("{PROJECT}\n"));

    Workspace {
        root: ws,
        managed_repo,
    }
}

fn create_workweave(primary: &Workspace, weaveroot: &Path, name: &str) -> Workspace {
    rwv()
        .args(["workweave", PROJECT, "create", name])
        .current_dir(&primary.root)
        .assert()
        .success();

    let root = weaveroot.join(format!("{PROJECT}--{name}"));
    Workspace {
        managed_repo: root.join(MANAGED_REPO),
        root,
    }
}

/// Fixture precondition: no durable definition of the driver is reachable from
/// this repo's config.
///
/// Load-bearing, not decoration. `plant_rwv_merge_driver_config` writes such a
/// definition into project repos, and where one exists a declared path
/// resolves whatever any call site states — so every assertion below about the
/// *policy* would hold for a call site that stated nothing at all. A managed
/// repo never receives the plant; this is the assertion that keeps that true.
fn assert_no_durable_definition(repo: &Path) {
    assert!(
        !has_rwv_merge_driver_config(repo).unwrap(),
        "fixture precondition: `merge.rwv-ours.driver` must be undefined in {} — \
         with a durable definition present the declared path resolves however \
         the replay is invoked, and this fixture could not tell a stated policy \
         from an ignored one (is it set in your global git config?)",
        repo.display()
    );
}

/// `<side>` regenerates the reference index after adding a verb, and locks.
/// The template additions are disjoint new files, so the *sources* merge
/// cleanly; the two regenerated indexes are what collide.
fn add_a_verb_and_lock(ws: &Workspace, verb: &str) {
    write(
        &ws.managed_repo,
        &format!("{TEMPLATES}/{verb}.md.tmpl"),
        &format!("{verb}\n"),
    );
    regenerate(&ws.managed_repo);
    git(&["add", "."], &ws.managed_repo);
    git(
        &["commit", "-m", &format!("docs: document `{verb}`")],
        &ws.managed_repo,
    );
    rwv()
        .args(["lock", "--commit"])
        .current_dir(&ws.root)
        .assert()
        .success();
}

// ---------------------------------------------------------------------------
// The land
// ---------------------------------------------------------------------------

#[test]
fn a_land_conflict_in_a_generated_artifact_resolves_mechanically() {
    let tmp = common::tempdir().unwrap();
    let weaveroot = tmp.path().join(".workweaves");
    std::fs::create_dir_all(&weaveroot).unwrap();

    let primary = make_primary(tmp.path(), true);
    let ww = create_workweave(&primary, &weaveroot, "ww");

    // Both sides documented a different verb and regenerated the index. Every
    // real land of concurrent work on a generated artifact has this shape.
    add_a_verb_and_lock(&primary, "sync");
    add_a_verb_and_lock(&ww, "weave");

    let primary_artifact = read(&primary.managed_repo, ARTIFACT);
    assert_no_durable_definition(&ww.managed_repo);

    let synced = rwv()
        .args(["sync", "primary", "--strategy", "rebase"])
        .current_dir(&ww.root)
        .assert()
        .success();

    assert_eq!(
        git_vcs().mid_op(&ww.managed_repo),
        None,
        "a declared derived path must not leave the land half-finished"
    );

    // The pull direction resolves the same way and owes the same report as
    // the landing direction below — one code path, so a report that reached
    // only one of them would mean the two had drifted apart.
    let stderr = String::from_utf8_lossy(&synced.get_output().stderr).into_owned();
    assert!(
        stderr.contains(ARTIFACT),
        "`rwv sync` must name what it resolved away too; got:\n{stderr}"
    );

    // The pick is a side-pick and nothing else. Byte-identical to what the
    // replay target had committed means no generator ran during the merge (D2)
    // — had one run, the artifact would already name all three verbs.
    assert_eq!(
        read(&ww.managed_repo, ARTIFACT),
        primary_artifact,
        "the replay target's version of a declared path is what survives"
    );

    // The authored sources both landed. This is why the survivor is stale
    // rather than merely arbitrary.
    for verb in ["land", "sync", "weave"] {
        assert!(
            ww.managed_repo
                .join(format!("{TEMPLATES}/{verb}.md.tmpl"))
                .exists(),
            "the authored source for `{verb}` must survive the land"
        );
    }

    // --- and the gate is what forces the regen -----------------------------
    //
    // The resolution above is deliberately wrong: the index names two verbs
    // and the merged sources describe three. Nothing that merges can fix that,
    // because the answer is not in either side — it is in the generator.
    let drift = drift_gate(&ww.managed_repo)
        .expect_err("a mechanically-resolved artifact is stale, and the gate must say so");
    assert!(
        drift.contains(ARTIFACT),
        "the gate must name the artifact it is blocking on; got:\n{drift}"
    );

    let regenerated = read(&ww.managed_repo, ARTIFACT);
    assert!(
        regenerated.contains("- land")
            && regenerated.contains("- sync")
            && regenerated.contains("- weave"),
        "regeneration produces the answer no side-pick could: every verb the \
         merged sources describe. Got:\n{regenerated}"
    );

    git(&["add", "docs/"], &ww.managed_repo);
    git(
        &["commit", "-m", "docs: regenerate after the land"],
        &ww.managed_repo,
    );
    drift_gate(&ww.managed_repo).expect("the committed regen is what clears the gate");
}

#[test]
fn the_same_land_conflict_without_the_declaration_stops_the_sync() {
    let tmp = common::tempdir().unwrap();
    let weaveroot = tmp.path().join(".workweaves");
    std::fs::create_dir_all(&weaveroot).unwrap();

    // Identical to the test above in every respect but one: this managed repo
    // commits no `.gitattributes`. Without it the same divergence is an
    // ordinary conflict that stops the land — which is what makes the
    // declaration, and not some property of the fixture, responsible for the
    // resolution above.
    let primary = make_primary(tmp.path(), false);
    let ww = create_workweave(&primary, &weaveroot, "ww");

    add_a_verb_and_lock(&primary, "sync");
    add_a_verb_and_lock(&ww, "weave");

    let out = rwv()
        .args(["sync", "primary", "--strategy", "rebase"])
        .current_dir(&ww.root)
        .assert()
        .failure();
    let stderr = String::from_utf8_lossy(&out.get_output().stderr).into_owned();
    let stdout = String::from_utf8_lossy(&out.get_output().stdout).into_owned();

    assert_eq!(
        git_vcs().mid_op(&ww.managed_repo),
        Some(ConflictOp::Rebase),
        "an undeclared conflict must leave the land where an operator can act \
         on it.\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    let conflicted = git_out(
        &["diff", "--name-only", "--diff-filter=U"],
        &ww.managed_repo,
    );
    assert!(
        conflicted.contains(ARTIFACT),
        "the generated artifact must be the path left conflicted; got {conflicted:?}"
    );
}

#[test]
fn the_templates_the_generator_reads_stay_authored() {
    let tmp = common::tempdir().unwrap();
    let weaveroot = tmp.path().join(".workweaves");
    std::fs::create_dir_all(&weaveroot).unwrap();

    // The declaration IS committed here. The carve-out for `templates/` is
    // what has to stop this land: a side-pick on a source of record discards
    // someone's writing with nothing left to regenerate it from, which is the
    // one thing this mechanism must never do.
    let primary = make_primary(tmp.path(), true);
    let ww = create_workweave(&primary, &weaveroot, "ww");

    for (side, prose) in [
        (&primary, "primary's prose\n"),
        (&ww, "the other side's prose\n"),
    ] {
        write(
            &side.managed_repo,
            &format!("{TEMPLATES}/land.md.tmpl"),
            prose,
        );
        git(&["add", "."], &side.managed_repo);
        git(
            &["commit", "-m", "docs: rewrite the `land` page"],
            &side.managed_repo,
        );
        rwv()
            .args(["lock", "--commit"])
            .current_dir(&side.root)
            .assert()
            .success();
    }

    rwv()
        .args(["sync", "primary", "--strategy", "rebase"])
        .current_dir(&ww.root)
        .assert()
        .failure();

    let conflicted = git_out(
        &["diff", "--name-only", "--diff-filter=U"],
        &ww.managed_repo,
    );
    assert!(
        conflicted.contains(&format!("{TEMPLATES}/land.md.tmpl")),
        "a template is authored content and its conflicts are real; got {conflicted:?}"
    );
}

// ---------------------------------------------------------------------------
// The report — regression pin for a landing that discarded a regeneration
// silently
// ---------------------------------------------------------------------------
//
// Two workweaves regenerated `docs/reference/explain/doctor.md`. The first
// landed. The second rebased on top; its workweave diff carried the file and
// its landed commit did not contain it at all. The side-pick was correct and
// documented — what was wrong was that nothing said so. No conflict, no
// marker, no diffstat entry, no line in the sync output. The tree then held a
// shipped page that did not describe a shipped finding, and the next person to
// run the drift gate inherited a red gate they had not caused.
//
// The prohibition these two tests pin is "the discard is not silent". They are
// written to fail if the report is removed or narrowed, because the asymmetry
// it introduces — a warning on a resolution the design calls correct — is
// exactly the kind of thing a later reader tidies away.

/// Land `ww` onto its recorded parent, returning `(stdout, stderr)`.
fn land(ww: &Workspace, json: bool) -> (String, String) {
    let mut cmd = rwv();
    cmd.args(["sync-to", "--strategy", "rebase"]);
    if json {
        cmd.arg("--json");
    }
    let out = cmd.current_dir(&ww.root).assert().success();
    (
        String::from_utf8_lossy(&out.get_output().stdout).into_owned(),
        String::from_utf8_lossy(&out.get_output().stderr).into_owned(),
    )
}

/// Both sides regenerate the index, then `ww` lands. Returns the land's
/// output, having first established that the land really did resolve `ww`'s
/// regeneration away — a report asserted against a land that dropped nothing
/// would pass for the wrong reason.
fn land_after_both_sides_regenerate(tmp: &Path, json: bool) -> (String, String) {
    let weaveroot = tmp.join(".workweaves");
    std::fs::create_dir_all(&weaveroot).unwrap();

    let primary = make_primary(tmp, true);
    let ww = create_workweave(&primary, &weaveroot, "ww");

    add_a_verb_and_lock(&primary, "sync");
    add_a_verb_and_lock(&ww, "weave");

    let ww_regeneration = read(&ww.managed_repo, ARTIFACT);
    let target_version = read(&primary.managed_repo, ARTIFACT);
    assert_ne!(
        ww_regeneration, target_version,
        "fixture precondition: the two sides must disagree about the artifact, \
         or there is no discard to report"
    );
    assert_no_durable_definition(&ww.managed_repo);

    let output = land(&ww, json);

    assert_eq!(
        read(&ww.managed_repo, ARTIFACT),
        target_version,
        "fixture precondition: the land must have resolved `ww`'s regeneration \
         away. Without that this asserts a report about nothing."
    );
    assert!(
        !git_out(&["log", "-1", "--name-only", "--format="], &ww.managed_repo).contains(ARTIFACT),
        "fixture precondition: the discard must be invisible in the landed \
         commit — that invisibility is the whole reason the report has to exist"
    );
    output
}

#[test]
fn a_land_that_resolves_a_regeneration_away_names_the_path() {
    let tmp = common::tempdir().unwrap();
    let (stdout, stderr) = land_after_both_sides_regenerate(tmp.path(), false);
    let output = format!("{stdout}{stderr}");

    assert!(
        output.contains(ARTIFACT),
        "a land that took the operator's regeneration out of what it landed must \
         name the path it took out. Got:\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        output.contains("regenerate"),
        "naming the path is half the report; the operator also has to be told \
         what to do about it. Got:\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
}

#[test]
fn the_same_land_names_the_path_in_json() {
    let tmp = common::tempdir().unwrap();
    let (stdout, stderr) = land_after_both_sides_regenerate(tmp.path(), true);

    let envelope: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("`sync-to --json` must emit one envelope: {e}\n{stdout}"));
    let dropped: Vec<&str> = envelope["outcomes"]
        .as_array()
        .expect("the envelope carries per-repo outcomes")
        .iter()
        .filter_map(|o| o["derived_content_dropped"].as_array())
        .flatten()
        .filter_map(|p| p.as_str())
        .collect();

    // Two surfaces, one land: a report that reaches only the one being read
    // is a report that has already half-decayed. The text assertion above and
    // this one have to move together.
    assert!(
        dropped.contains(&ARTIFACT),
        "the machine surface must name it too; got {dropped:?} in:\n{stdout}\
         \nstderr:\n{stderr}"
    );
}

#[test]
fn a_land_that_did_not_touch_the_artifact_reports_nothing() {
    let tmp = common::tempdir().unwrap();
    let weaveroot = tmp.path().join(".workweaves");
    std::fs::create_dir_all(&weaveroot).unwrap();

    // Only the target regenerates. `ww` commits authored content that has
    // nothing to do with the artifact — so the artifact differs between `ww`'s
    // tip and what lands, and nothing of `ww`'s was discarded.
    //
    // This is the case a report keyed on "the artifact changed" would cry wolf
    // about, and crying wolf is how a warning gets ignored and then removed.
    let primary = make_primary(tmp.path(), true);
    let ww = create_workweave(&primary, &weaveroot, "ww");

    add_a_verb_and_lock(&primary, "sync");

    write(&ww.managed_repo, "NOTES.md", "unrelated\n");
    git(&["add", "."], &ww.managed_repo);
    git(&["commit", "-m", "docs: notes"], &ww.managed_repo);
    rwv()
        .args(["lock", "--commit"])
        .current_dir(&ww.root)
        .assert()
        .success();

    let (stdout, stderr) = land(&ww, false);

    assert_ne!(
        read(&ww.managed_repo, ARTIFACT),
        String::new(),
        "sanity: the artifact exists on the landed tree"
    );
    assert!(
        !stderr.contains(ARTIFACT) && !stdout.contains(ARTIFACT),
        "nothing of `ww`'s was discarded, so nothing is owed a report. Got:\
         \nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
}
