//! E2E tests for `rwv setup` subcommands (agents-md, claude).

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use std::path::Path;

const GENERATED_HEADER: &str = "<!-- Generated by rwv \u{2014} do not edit -->";

fn make_workspace(parent: &Path, name: &str) -> std::path::PathBuf {
    let root = parent.join(name);
    fs::create_dir_all(root.join("github")).unwrap();
    fs::create_dir_all(root.join("projects")).unwrap();
    root
}

fn write_manifest(root: &Path, project: &str, yaml: &str) {
    let dir = root.join("projects").join(project);
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join("rwv.yaml"), yaml).unwrap();
}

// ============================================================================
// 1. Creates AGENTS.md with expected content
// ============================================================================

#[test]
fn setup_agents_md_creates_file() {
    let tmp = tempfile::tempdir().unwrap();
    let root = make_workspace(tmp.path(), "ws");

    write_manifest(
        &root,
        "web-app",
        r#"
repositories:
  github/acme/server:
    type: git
    url: https://github.com/acme/server.git
    version: main
    role: primary
integrations:
  cargo:
    enabled: true
"#,
    );

    fs::write(root.join(".rwv-active"), "web-app\n").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "agents-md"])
        .current_dir(&root)
        .assert()
        .success()
        .stderr(predicate::str::contains("wrote"));

    let content = fs::read_to_string(root.join("AGENTS.md")).unwrap();
    assert!(content.starts_with(GENERATED_HEADER));
    assert!(content.contains("# repoweave workspace"));
    assert!(content.contains("**Project**: `web-app`"));
    assert!(content.contains("## Repositories"));
    assert!(content.contains("github/acme/server"));
    assert!(content.contains("## Key commands"));
}

// ============================================================================
// 2. Idempotent — running twice produces same result
// ============================================================================

#[test]
fn setup_agents_md_idempotent() {
    let tmp = tempfile::tempdir().unwrap();
    let root = make_workspace(tmp.path(), "ws");
    write_manifest(&root, "demo", "repositories: {}\n");
    fs::write(root.join(".rwv-active"), "demo\n").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "agents-md"])
        .current_dir(&root)
        .assert()
        .success();

    let first = fs::read_to_string(root.join("AGENTS.md")).unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "agents-md"])
        .current_dir(&root)
        .assert()
        .success();

    let second = fs::read_to_string(root.join("AGENTS.md")).unwrap();
    assert_eq!(first, second);
}

// ============================================================================
// 3. Refuses to overwrite hand-edited file
// ============================================================================

#[test]
fn setup_agents_md_refuses_hand_edited() {
    let tmp = tempfile::tempdir().unwrap();
    let root = make_workspace(tmp.path(), "ws");
    write_manifest(&root, "demo", "repositories: {}\n");
    fs::write(root.join(".rwv-active"), "demo\n").unwrap();

    // Write a hand-edited AGENTS.md (no generated header).
    fs::write(root.join("AGENTS.md"), "# My custom agents doc\n").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "agents-md"])
        .current_dir(&root)
        .assert()
        .failure()
        .stderr(predicate::str::contains("not generated by rwv"));
}

// ============================================================================
// 4. Fails outside workspace
// ============================================================================

#[test]
fn setup_agents_md_fails_outside_workspace() {
    let tmp = tempfile::tempdir().unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "agents-md"])
        .current_dir(tmp.path())
        .assert()
        .failure();
}

// ============================================================================
// 5. setup claude — errors when settings.json missing
// ============================================================================

#[test]
fn setup_claude_errors_without_settings() {
    let tmp = tempfile::tempdir().unwrap();

    // Point HOME to a dir without .claude/settings.json
    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "claude"])
        .env("HOME", tmp.path())
        .assert()
        .failure()
        .stderr(predicate::str::contains("does not exist"));
}

// ============================================================================
// 6. setup claude — registers hooks in empty settings
// ============================================================================

#[test]
fn setup_claude_registers_hooks() {
    let tmp = tempfile::tempdir().unwrap();
    let claude_dir = tmp.path().join(".claude");
    fs::create_dir_all(&claude_dir).unwrap();
    fs::write(claude_dir.join("settings.json"), "{}").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "claude"])
        .env("HOME", tmp.path())
        .assert()
        .success()
        .stdout(predicate::str::contains("Registered"));

    let content: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(claude_dir.join("settings.json")).unwrap())
            .unwrap();

    // rwv prime registered for SessionStart + PreCompact
    for event in &["SessionStart", "PreCompact"] {
        let arr = content["hooks"][event].as_array().unwrap();
        assert!(!arr.is_empty(), "{event} hooks should be non-empty");
        let found = arr.iter().any(|g| {
            g["hooks"]
                .as_array()
                .map(|hs| {
                    hs.iter()
                        .any(|h| h["command"].as_str() == Some("rwv prime"))
                })
                .unwrap_or(false)
        });
        assert!(found, "{event} should contain rwv prime hook");
    }

    // WorktreeCreate + WorktreeRemove registered with rwv workweave --claude-hook
    for event in &["WorktreeCreate", "WorktreeRemove"] {
        let arr = content["hooks"][event]
            .as_array()
            .unwrap_or_else(|| panic!("{event} should be registered"));
        let found = arr.iter().any(|g| {
            g["hooks"]
                .as_array()
                .map(|hs| {
                    hs.iter()
                        .any(|h| h["command"].as_str() == Some("rwv workweave --claude-hook"))
                })
                .unwrap_or(false)
        });
        assert!(
            found,
            "{event} should contain 'rwv workweave --claude-hook'"
        );
    }

    // No hook scripts should be installed — rwv workweave --claude-hook is used directly.
    let hooks_dir = claude_dir.join("hooks");
    assert!(
        !hooks_dir.exists(),
        "hooks_dir should not be created (no shell scripts needed)"
    );
}

// ============================================================================
// 7. setup claude — idempotent
// ============================================================================

#[test]
fn setup_claude_idempotent() {
    let tmp = tempfile::tempdir().unwrap();
    let claude_dir = tmp.path().join(".claude");
    fs::create_dir_all(&claude_dir).unwrap();
    fs::write(claude_dir.join("settings.json"), "{}").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "claude"])
        .env("HOME", tmp.path())
        .assert()
        .success();

    let first = fs::read_to_string(claude_dir.join("settings.json")).unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "claude"])
        .env("HOME", tmp.path())
        .assert()
        .success()
        .stdout(predicate::str::contains("up to date"));

    let second = fs::read_to_string(claude_dir.join("settings.json")).unwrap();
    assert_eq!(first, second, "second run should not modify the file");
}

// ============================================================================
// 8. setup claude — no hook scripts installed (uses rwv workweave --claude-hook)
// ============================================================================

#[test]
fn setup_claude_scripts_are_executable() {
    // rwv setup claude no longer installs shell scripts; it registers
    // `rwv workweave --claude-hook` directly. Verify no scripts are installed.
    let tmp = tempfile::tempdir().unwrap();
    let claude_dir = tmp.path().join(".claude");
    fs::create_dir_all(&claude_dir).unwrap();
    fs::write(claude_dir.join("settings.json"), "{}").unwrap();

    Command::cargo_bin("rwv")
        .unwrap()
        .args(["setup", "claude"])
        .env("HOME", tmp.path())
        .assert()
        .success();

    let hooks_dir = claude_dir.join("hooks");
    assert!(
        !hooks_dir.exists(),
        "hooks_dir should not be created (scripts not needed with --claude-hook)"
    );
}
