// ===========================================================================
// cargo-workspace
// ===========================================================================

use super::*;

#[test]
fn auto_detects_repos_with_cargo_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/acme/server/Cargo.toml");
    touch(root, "github/acme/web/Cargo.toml");
    touch(root, "github/acme/docs/README.md");

    let manifest = make_manifest(vec![
        ("github/acme/server", Role::Owned),
        ("github/acme/web", Role::Owned),
        ("github/acme/docs", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = CargoWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(content.contains("github/acme/server"));
    assert!(content.contains("github/acme/web"));
    assert!(!content.contains("github/acme/docs"));
}

#[test]
fn generates_cargo_toml_with_workspace_section() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/chatly/protocol/Cargo.toml");
    touch(root, "github/chatly/server/Cargo.toml");

    let manifest = make_manifest(vec![
        ("github/chatly/protocol", Role::Owned),
        ("github/chatly/server", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = CargoWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // The legacy `# Generated by rwv ...` first-line header is gone
    // post-port. Ownership is proven by the per-key
    // `# managed by rwv` decor on each owned key (TomlDoc marker).
    assert!(
        content.contains("# managed by rwv"),
        "managed-by-rwv decor missing: {content}"
    );
    assert!(content.contains("[workspace]"));
    assert!(content.contains("\"github/chatly/protocol\""));
    assert!(content.contains("\"github/chatly/server\""));
    assert!(content.contains("resolver = \"2\""));
}

#[test]
fn excludes_reference_repos() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/acme/server/Cargo.toml");
    touch(root, "github/acme/reference-lib/Cargo.toml");

    let manifest = make_manifest(vec![
        ("github/acme/server", Role::Owned),
        ("github/acme/reference-lib", Role::Reference),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = CargoWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(content.contains("github/acme/server"));
    assert!(!content.contains("reference-lib"));
}

#[test]
fn deactivation_removes_generated_cargo_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Post-port: ownership is proven by the per-key
    // `# managed by rwv` decor, not a first-line header. Seed a Cargo.toml
    // shaped the way rwv would author it.
    //
    // `resolver` is now Ownership::DefaultOnly — it is NOT
    // stripped on deactivate. A file with only `members` (Author) and
    // `resolver` (DefaultOnly) will, after deactivate, still contain
    // `resolver = "2"`, so the file is NOT deleted (it has remaining
    // content). Test updated to assert the file exists and only members
    // was stripped.
    write_file(
        root,
        "Cargo.toml",
        "[workspace]\n# managed by rwv\nmembers = []\n# managed by rwv\nresolver = \"2\"\n",
    );
    assert!(root.join("Cargo.toml").exists());

    let integration = CargoWorkspace;
    integration.deactivate(root).unwrap();

    // File should still exist: resolver (DefaultOnly) was not stripped.
    assert!(
        root.join("Cargo.toml").exists(),
        "Cargo.toml must not be deleted when resolver (DefaultOnly) content remains"
    );
    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // members (Author) was stripped.
    assert!(
        !content.contains("members"),
        "members (Author key) should be stripped on deactivate: {content}"
    );
    // resolver (DefaultOnly) was NOT stripped.
    assert!(
        content.contains("resolver"),
        "resolver (DefaultOnly) must survive deactivate: {content}"
    );
}

#[test]
fn deactivation_preserves_handwritten_cargo_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // A hand-written Cargo.toml without the generated header should NOT be removed
    write_file(
        root,
        "Cargo.toml",
        "[package]\nname = \"my-project\"\nversion = \"0.1.0\"\n",
    );
    assert!(root.join("Cargo.toml").exists());

    let integration = CargoWorkspace;
    integration.deactivate(root).unwrap();
    assert!(root.join("Cargo.toml").exists());
}

#[cfg(unix)]
#[test]
fn check_warns_when_cargo_not_on_path() {
    let absent = doctor_json_on_tool_only_path(
        "cargo-workspace",
        "github/acme/server/Cargo.toml",
        "[package]\nname = \"server\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        &[],
    );
    let present = doctor_json_on_tool_only_path(
        "cargo-workspace",
        "github/acme/server/Cargo.toml",
        "[package]\nname = \"server\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        &["cargo"],
    );

    tool_missing_fires_then_clears(&absent, &present, "cargo-workspace", "cargo");
}

// -----------------------------------------------------------------------
// Nested-workspace handling
// -----------------------------------------------------------------------

#[test]
fn nested_workspace_without_opt_out_fails_with_named_repo_error() {
    // A member repo declares its own [workspace]. Activation must fail
    // before any cargo invocation, naming the conflicting repo and
    // listing the three resolutions.
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/cwalv/plain/Cargo.toml",
        "[package]\nname = \"plain\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/cwalv/forked/Cargo.toml",
        "[package]\nname = \"forked\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
             [workspace]\nmembers = [\"crates/*\"]\n",
    );

    let manifest = make_manifest(vec![
        ("github/cwalv/plain", Role::Owned),
        ("github/cwalv/forked", Role::Fork),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let err = CargoWorkspace.activate(&ctx).unwrap_err().to_string();
    assert!(
        err.contains("github/cwalv/forked"),
        "error should name the conflicting repo, got: {err}"
    );
    assert!(
        err.contains("[workspace]"),
        "error should explain the cause, got: {err}"
    );
    assert!(
        err.contains("exclude"),
        "error should point at the opt-out key, got: {err}"
    );
    // Generated Cargo.toml must NOT have been written on the failure path.
    assert!(
        !root.join("Cargo.toml").exists(),
        "no Cargo.toml should be written when activation fails"
    );
}

#[test]
fn nested_workspace_with_opt_out_drops_repo_from_members() {
    // With the opt-out set, the conflicting repo is dropped from members.
    // Post-port: the `# excluded:` comment emitted by the
    // legacy whole-overwrite path is gone. The merge model owns *keys*,
    // not free-floating comments — TomlDoc has no comment-emission API
    // and the helper's contract is "never author outside the owned-key
    // set". Operators see exclusions in rwv.toml directly; surfacing
    // them in the file was decorative.
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/cwalv/plain/Cargo.toml",
        "[package]\nname = \"plain\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/cwalv/forked/Cargo.toml",
        "[package]\nname = \"forked\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
             [workspace]\nmembers = [\"crates/*\"]\n",
    );

    let manifest = make_manifest(vec![
        ("github/cwalv/plain", Role::Owned),
        ("github/cwalv/forked", Role::Fork),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("exclude = [\"github/cwalv/forked\"]");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("\"github/cwalv/plain\""),
        "non-conflicting repo should still be a member, got:\n{content}"
    );
    assert!(
        !content.contains("\"github/cwalv/forked\""),
        "opted-out repo should not appear as a member, got:\n{content}"
    );
}

#[test]
fn virtual_workspace_without_opt_out_fails_with_named_repo_error() {
    // Virtual workspace = `[workspace]` and no `[package]`. Same failure
    // mode as a hybrid workspace+package file.
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/cwalv/plain/Cargo.toml",
        "[package]\nname = \"plain\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/cwalv/virtual_ws/Cargo.toml",
        "[workspace]\nmembers = [\"crate-a\", \"crate-b\"]\nresolver = \"2\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/cwalv/plain", Role::Owned),
        ("github/cwalv/virtual_ws", Role::Fork),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let err = CargoWorkspace.activate(&ctx).unwrap_err().to_string();
    assert!(
        err.contains("github/cwalv/virtual_ws"),
        "virtual-workspace conflict should name the repo, got: {err}"
    );
}

#[test]
fn opt_out_for_non_rust_repo_is_silently_ignored() {
    // Operators should be able to pre-emptively opt out a repo path even
    // if that repo isn't a Rust repo today; the integration should not
    // complain. (No-op fallback per spec.)
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/cwalv/plain/Cargo.toml",
        "[package]\nname = \"plain\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/cwalv/plain", Role::Owned),
        ("github/cwalv/docs-only", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml(
        "exclude = [\"github/cwalv/docs-only\", \"github/missing/repo\"]",
    );
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    // No panic, no error — non-Rust opt-out entries are dropped.
    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // The non-Rust opt-out doesn't appear as a `# excluded:` comment
    // because the repo never made it through Cargo.toml detection.
    assert!(!content.contains("# excluded: github/cwalv/docs-only"));
    assert!(!content.contains("# excluded: github/missing/repo"));
    assert!(content.contains("\"github/cwalv/plain\""));
}

#[test]
fn check_reports_nested_workspace_conflict_as_error_issue() {
    // `rwv doctor` should surface the same diagnostic as activation
    // would, so operators see it without having to attempt a lock.
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/cwalv/forked/Cargo.toml",
        "[workspace]\nmembers = [\"crate-a\"]\n",
    );

    let manifest = make_manifest(vec![("github/cwalv/forked", Role::Fork)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let issues = CargoWorkspace.check(&ctx).unwrap();
    assert!(
        issues
            .iter()
            .any(|i| i.severity == Severity::Error && i.message.contains("github/cwalv/forked")),
        "check should report a nested-workspace error, got: {issues:?}"
    );
}

// -----------------------------------------------------------------------
// cargo-workspace — real-world manifest scenarios
// -----------------------------------------------------------------------
//
// Seeds use real idioms from two published Cargo workspaces rather than
// minimal fixtures: a NOTE comment block, `profile.*` panic="abort" and
// `workspace.lints.clippy`; and `workspace.dependencies`,
// `workspace.package`, `profile.release.package.<crate>` and
// `workspace.lints.rust`. The merge must leave every one of them
// byte-stable, which a synthetic manifest would not exercise.

/// Activate preserves `[profile.*]` + `[workspace.lints]`.
/// Seed file: previously-activated state (per-key `# managed by rwv` on
/// members/resolver) plus the seed idioms above. After re-activate, the NOTE
/// comment block, panic="abort", and clippy deny policy must all survive
/// byte-stable.
#[test]
fn s6_1_activate_preserves_rvtty_profiles_and_lints() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Real Rust repos that the integration will detect as members.
    touch(root, "github/acme/rvtty-a/Cargo.toml");
    touch(root, "github/acme/rvtty-b/Cargo.toml");

    // Seed the root Cargo.toml in previously-activated shape:
    //   - per-key `# managed by rwv` decoration on members and resolver
    //     (the port's ownership marker; legacy `# Generated by rwv` header is gone)
    //   - rvtty idioms (NOTE block, profile panic=abort, workspace.lints.clippy)
    //     as user foreign content that must round-trip untouched.
    write_file(
        root,
        "Cargo.toml",
        r#"#
# NOTE (olb.5.4): rvtty-style hand-maintained block. profile/lint policy
# must round-trip activate untouched. This comment block is part of the
# regression — strip it and the rationale is lost forever.

[workspace]
# managed by rwv
members = []
# managed by rwv
resolver = "2"

# Panic strategy: abort in all profiles.
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Workspace-wide clippy lint policy.
[workspace.lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
dbg_macro    = "deny"
"#,
    );

    let manifest = make_manifest(vec![
        ("github/acme/rvtty-a", Role::Owned),
        ("github/acme/rvtty-b", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let path = root.join("Cargo.toml");
    contract::assert_activate_preserves_foreign(
        &path,
        || {
            CargoWorkspace.activate(&ctx).unwrap();
        },
        &[
            contract::substr_probe("members[rvtty-a]", "github/acme/rvtty-a"),
            contract::substr_probe("members[rvtty-b]", "github/acme/rvtty-b"),
            contract::substr_probe("resolver", "resolver = \"2\""),
        ],
        // Marker: per-key `# managed by rwv` decor on `members`.
        &contract::substr_probe("toml marker on members", "managed by rwv"),
        &[
            "NOTE (olb.5.4)",
            "panic = \"abort\"",
            "print_stdout = \"deny\"",
            "print_stderr = \"deny\"",
            "dbg_macro",
            "# Panic strategy",
            "[workspace.lints.clippy]",
        ],
    );
}

/// Re-activate is idempotent w.r.t. `[workspace.dependencies]`
/// / `[workspace.package]` / `[profile.*]` (the ruff surface).
#[test]
fn s6_2_reactivate_idempotent_over_ruff_surface() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/astral/ruff/Cargo.toml");
    touch(root, "github/astral/ty/Cargo.toml");

    // Ruff-idiom previously-activated root: per-key `# managed by rwv` on
    // members and resolver, plus the full ruff surface (workspace.package,
    // deps, lints, profile.*) as user foreign content.
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/astral/ruff"]
# managed by rwv
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.78"
homepage = "https://docs.astral.sh/ruff"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.80"
serde = { version = "1.0", features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "warn"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.package.ruff_python_parser]
codegen-units = 1
"#,
    );

    let manifest = make_manifest(vec![
        ("github/astral/ruff", Role::Owned),
        ("github/astral/ty", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let path = root.join("Cargo.toml");
    contract::assert_activate_idempotent(
        &path,
        || {
            CargoWorkspace.activate(&ctx).unwrap();
        },
        |_p| { /* no user mutation between activates */ },
        &[
            contract::substr_probe("members[ruff]", "github/astral/ruff"),
            contract::substr_probe("members[ty]", "github/astral/ty"),
        ],
        &contract::substr_probe("toml marker on members", "managed by rwv"),
        &[
            "[workspace.package]",
            "rust-version = \"1.78\"",
            "[workspace.dependencies]",
            "anyhow = \"1.0.80\"",
            "[workspace.lints.rust]",
            "unsafe_code = \"warn\"",
            "[profile.release]",
            "lto = \"fat\"",
            "[profile.release.package.ruff_python_parser]",
        ],
    );
}

/// Deactivate strips only Author keys, keeps user policy and
/// DefaultOnly keys.
///
/// `resolver` is now Ownership::DefaultOnly — it is NOT stripped
/// on deactivate. Only `members` (Author) is stripped. `resolver` survives
/// along with the rest of the user's content.
#[test]
fn s6_3_deactivate_strips_keeps_user_policy() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Seed with marker + owned keys + heavy user policy.
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/server"]
# managed by rwv
resolver = "2"

[profile.dev]
panic = "abort"

[workspace.lints.clippy]
dbg_macro = "deny"

[patch.crates-io]
foo = { path = "vendor/foo" }
"#,
    );

    let path = root.join("Cargo.toml");
    // Only `members` (Ownership::Author) is an owned probe that must be
    // absent after deactivate. `resolver` (Ownership::DefaultOnly) survives
    // and is listed in foreign_substrings below.
    contract::assert_deactivate_strips_keeps(
        &path,
        || {
            CargoWorkspace.deactivate(root).unwrap();
        },
        &[contract::substr_probe(
            "members entry",
            "github/acme/server",
        )],
        &contract::substr_probe("toml marker", "managed by rwv"),
        &[
            // resolver (DefaultOnly) must survive deactivate.
            "resolver = \"2\"",
            "[profile.dev]",
            "panic = \"abort\"",
            "[workspace.lints.clippy]",
            "dbg_macro = \"deny\"",
            "[patch.crates-io]",
            "foo = { path = \"vendor/foo\" }",
        ],
    );
}

/// Members sub-path config + nested-workspace exemption.
/// Repo with no root Cargo.toml; config emits
/// `<repo>/<sub>` per include. Sibling workspace is NOT an ancestor and
/// must NOT trip the nested-workspace error.
///
/// Members sub-path config is added by C6 (cargo design-finalization) +
/// C8 (cargo members-subpath + [patch] opt-in).
#[test]
fn s6_4_members_subpath_and_nested_workspace_exemption() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // No root Cargo.toml under github/cwalv/rvtty.
    write_file(
        root,
        "github/cwalv/rvtty/daemon/Cargo.toml",
        "[package]\nname = \"daemon\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/cwalv/rvtty/client/Cargo.toml",
        "[package]\nname = \"client\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/cwalv/rvtty/common/Cargo.toml",
        "[package]\nname = \"common\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    // Sibling workspace (not an ancestor).
    write_file(
        root,
        "rvtty/workspace/Cargo.toml",
        "[workspace]\nmembers = [\"../daemon\", \"../client\"]\nresolver = \"2\"\n",
    );

    let manifest = make_manifest(vec![("github/cwalv/rvtty", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    // The members-subpath config shape: per-repo sub-path include list.
    let config = IntegrationConfig::from_toml(
        "[members.\"github/cwalv/rvtty\"]\ninclude = [\"daemon\", \"client\", \"common\"]\n",
    );
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    // Must NOT fail with nested-workspace error: the sibling workspace at
    // rvtty/workspace/Cargo.toml is not an ancestor of any included sub-path.
    CargoWorkspace.activate(&ctx).expect(
        "activate must succeed: members.<repo> exempts the root, and the \
             sibling workspace is not an ancestor of the included sub-paths",
    );

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("github/cwalv/rvtty/daemon"),
        "members should include daemon sub-path; got:\n{content}"
    );
    assert!(
        content.contains("github/cwalv/rvtty/client"),
        "members should include client sub-path; got:\n{content}"
    );
    assert!(
        content.contains("github/cwalv/rvtty/common"),
        "members should include common sub-path; got:\n{content}"
    );
    // The repo root itself must NOT be a member (no root Cargo.toml).
    let lines_with_repo_root: Vec<&str> = content
        .lines()
        .filter(|l| l.contains("\"github/cwalv/rvtty\""))
        .collect();
    assert!(
        lines_with_repo_root.is_empty(),
        "repo root (github/cwalv/rvtty) must NOT appear as a member; got:\n{content}"
    );
}

/// Opt-in `[patch.crates-io]` generation for
/// cross-repo path deps. With `integrations.cargo-workspace.patch: true`
/// rwv scans each member's `Cargo.toml` for `path = "..."` deps that
/// point into another known member, and emits a
/// `[patch.crates-io].<crate>` entry keyed by the target crate's name.
#[test]
fn patch_opt_in_emits_crates_io_entries_for_cross_repo_path_deps() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Two repos. `app` depends on `lib` via a relative `path = ...`.
    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        r#"[package]
name = "acme-app"
version = "0.1.0"
edition = "2021"

[dependencies]
acme-lib = { path = "../lib" }
"#,
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = true\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("[patch.crates-io"),
        "expected a `[patch.crates-io]` section; got:\n{content}"
    );
    assert!(
        content.contains("acme-lib"),
        "expected a patch entry keyed by the dep's crate name `acme-lib`; got:\n{content}"
    );
    assert!(
        content.contains("github/acme/lib"),
        "expected the patch entry to point at the lib member; got:\n{content}"
    );
    // The rwv marker should decorate the generated patch entry.
    assert!(
        content.contains("managed by rwv"),
        "expected the rwv marker on managed keys; got:\n{content}"
    );
}

/// When `patch` is the default (false), no `[patch]` table
/// is generated even when cross-repo path deps exist. This is the
/// internal-crate path: operators commit the relative `path=` dep and
/// rwv stays out of `[patch]` entirely.
#[test]
fn patch_default_false_emits_no_patch_table() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        r#"[package]
name = "acme-app"
version = "0.1.0"
edition = "2021"

[dependencies]
acme-lib = { path = "../lib" }
"#,
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    // Default config: patch defaults to false.
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        !content.contains("[patch"),
        "no `[patch]` table should be generated with patch=false; got:\n{content}"
    );
}

/// Deactivate strips rwv-authored `[patch.crates-io]`
/// entries; user-authored entries survive — deactivate goes through the
/// same toml_edit merge activate does. (Co-requisite of the activate-time
/// generation.)
#[test]
fn deactivate_strips_rwv_patch_entries_keeps_user_entries() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Seed a Cargo.toml that mixes an rwv-managed [patch.crates-io].acme-lib
    // entry (carrying the marker decor) with a hand-authored
    // [patch.crates-io].vendor-foo entry. Also exercise the [workspace]
    // strip-deactivate path coexists with the new patch strip.
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app", "github/acme/lib"]
# managed by rwv
resolver = "2"

[patch.crates-io]
# managed by rwv
acme-lib = { path = "github/acme/lib" }
vendor-foo = { git = "https://example.com/vendor-foo" }
"#,
    );

    CargoWorkspace.deactivate(root).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // rwv-authored patch entry is gone.
    assert!(
        !content.contains("acme-lib"),
        "rwv-authored patch entry should be stripped; got:\n{content}"
    );
    // User-authored patch entry survives.
    assert!(
        content.contains("vendor-foo"),
        "user-authored patch entry should survive; got:\n{content}"
    );
    // The user-authored [patch.crates-io] table itself survives (because
    // it's non-empty after the rwv strip).
    assert!(
        content.contains("[patch.crates-io]"),
        "user-authored [patch.crates-io] should survive; got:\n{content}"
    );
}

// -----------------------------------------------------------------------
// PatchMode::Derived (registry-dep tier)
//
// Rationale is in src/integrations/cargo_workspace.rs's top-doc comment.
//
// The tests below exercise the derived-mode invariants:
//
// - Registry-dep matched by name → patch emitted.
// - `committed-paths` mode is UNCHANGED under a member declaring a
//   path dep (regression guard on the mirror behavior).
// - `derived` with a reference-role repo hosting the crate → patched
//   from the reference-repo path.
// - Git-source dep → `[patch."<url>"]` entry (not crates-io).
// - Member `.cargo/config.toml` shadowing key → warning surfaced,
//   output still correct.
// - Unpublished in-weave crate is documented tier-boundary behavior,
//   not a failure — asserted here so the shape is regression-tested.
// -----------------------------------------------------------------------

/// A member declaring `<in-weave-crate> = "<req>"` as a registry dep
/// gets patched to the in-weave path when the crate name matches.
/// This is what derived mode exists for: sovereign members declare bare
/// registry versions and the weave supplies the live sources.
#[test]
fn derived_patch_matches_registry_dep_by_name() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // `acme-lib` at v0.3.5 in-weave; `acme-app` depends on it as a
    // registry dep (no path=, no git=). Committed-paths mode would
    // emit nothing (there's no cross-repo `path=` to mirror);
    // derived mode should notice the name match and patch.
    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("[patch.crates-io"),
        "derived mode must emit [patch.crates-io] for a matched \
             registry dep; got:\n{content}"
    );
    assert!(
        content.contains("acme-lib"),
        "expected patch entry keyed by the target crate name \
             `acme-lib`; got:\n{content}"
    );
    assert!(
        content.contains("github/acme/lib"),
        "expected patch entry to point at the in-weave lib member; \
             got:\n{content}"
    );
    assert!(
        content.contains("managed by rwv"),
        "generated patch entry must carry the rwv marker; got:\n{content}"
    );
}

/// A member with a committed cross-member `path=` dep continues to
/// receive the mirror patch under `patch: committed-paths` — the
/// enum rename is a pure rename, existing manifests keep working.
///
/// This test uses the modern string spelling (`committed-paths`) to
/// exercise the parse path; the boolean back-compat is covered in
/// manifest_test.rs.
#[test]
fn committed_paths_mode_unchanged_for_path_dep_member() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = { path = \"../lib\" }\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"committed-paths\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // Same as the pre-rename `patch_opt_in_emits_crates_io_entries_for_cross_repo_path_deps`
    // assertions — the mirror behavior is unchanged.
    assert!(
        content.contains("[patch.crates-io"),
        "committed-paths mode must emit [patch.crates-io] for a \
             cross-repo path dep; got:\n{content}"
    );
    assert!(content.contains("acme-lib"), "got:\n{content}");
    assert!(content.contains("github/acme/lib"), "got:\n{content}");
    assert!(content.contains("managed by rwv"), "got:\n{content}");
}

/// A `reference`-role repo is excluded from the workspace `members`
/// list (they're read-only study material), but under derived mode
/// they participate in the patch *index*: an active member declaring
/// a registry dep whose name matches a reference-repo crate gets
/// patched to the reference-repo path.
///
/// Reference-role repos are symlinked to the canonical clone in
/// workweaves; symlinks keep logical paths in `cargo metadata` with zero
/// rebuild churn, so they are safe patch sources.
#[test]
fn derived_patch_includes_reference_repos_as_sources() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Reference-role repo hosts the crate.
    write_file(
        root,
        "github/upstream/lib/Cargo.toml",
        "[package]\nname = \"upstream-lib\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    );
    // Active member depends on it as a registry dep.
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nupstream-lib = \"1.0\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/upstream/lib", Role::Reference),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();

    // Reference repo must NOT appear as a workspace member (parse
    // the members array precisely — the reference path DOES appear
    // as a patch-entry `path = "..."` value, so a substring check
    // is not sufficient).
    let doc: toml_edit::DocumentMut = content.parse().expect("valid TOML");
    let members: Vec<String> = doc
        .get("workspace")
        .and_then(|i| i.as_table())
        .and_then(|t| t.get("members"))
        .and_then(|i| i.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default();
    assert!(
        !members.contains(&"github/upstream/lib".to_string()),
        "reference-role repo must not be a workspace member; got: {members:?}"
    );

    // But it MUST appear as the patch source.
    assert!(
        content.contains("upstream-lib"),
        "reference-role repo must be usable as a derived patch source; \
             got:\n{content}"
    );
    assert!(
        content.contains("github/upstream/lib"),
        "patch path must point at the reference-repo dir; got:\n{content}"
    );
}

/// A member declaring `foo = { git = "<url>" }` produces a
/// `[patch."<url>"]` sub-table entry — NOT `[patch.crates-io]`.
/// Cargo treats git-source deps as a distinct source; a
/// `[patch.crates-io]` entry does not patch a git-source dep.
#[test]
fn derived_patch_emits_git_url_subtable_for_git_source_dep() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\n\
             acme-lib = { git = \"https://example.com/acme/lib.git\", version = \"0.1\" }\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("\"https://example.com/acme/lib.git\""),
        "git-source dep must produce [patch.\"<git-url>\"] entry; \
             got:\n{content}"
    );
    assert!(
        content.contains("acme-lib"),
        "patch entry must be keyed by the target crate name; got:\n{content}"
    );
    // The [patch.crates-io] table must NOT carry this crate — the git
    // source is a distinct source from crates.io. It's OK if the
    // [patch.crates-io] table is absent entirely.
    let after_crates_io = content.split("[patch.crates-io").nth(1).unwrap_or("");
    assert!(
        !after_crates_io.contains("acme-lib"),
        "git-source dep must NOT be patched via [patch.crates-io]; \
             got:\n{content}"
    );
}

/// A member's own `.cargo/config.toml` declaring the same
/// `[patch.crates-io].<crate>` key silently defeats the weave-level
/// patch — cargo merges `.cargo/config.toml` closest-config-wins per key,
/// and its diagnostic actively misleads about which one won.
///
/// Derived mode must surface a warning to stderr at generation time
/// AND emit the patch anyway (the operator may still resolve the
/// shadowing after being informed). The absence of the warning
/// wouldn't fail the write, but the write must remain correct.
#[test]
fn derived_patch_surfaces_shadowing_warning_and_writes_output() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );
    // Shadowing config.
    write_file(
        root,
        "github/acme/app/.cargo/config.toml",
        "[patch.crates-io]\nacme-lib = { path = \"/wrong/place\" }\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    // The write still lands — the warning is advisory, not gating.
    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("[patch.crates-io"),
        "derived-mode output must land even when a member config \
             shadows the key; got:\n{content}"
    );
    assert!(
        content.contains("acme-lib") && content.contains("github/acme/lib"),
        "patch entry must be correct; got:\n{content}"
    );
    // The stderr channel is not captured here (integration tests
    // don't easily assert on eprintln); the shadowing-detection
    // helper is unit-covered via scan_patch_shadowing_against_keys.
}

/// The tier boundary: a member depending on an
/// *unpublished* crate name (one that only exists in the weave)
/// resolves only inside the weave — standalone `cargo build` would
/// fail with "no matching package".
///
/// Derived mode's job is to make the in-weave path work — and it
/// does, by emitting the patch — but rwv makes no claim about
/// standalone-buildability of the member.  This is documented
/// behavior, not a bug. Assert that the shape (patch emitted, no
/// warning) matches the documented expectation, so any future change
/// to the tier boundary is caught.
#[test]
fn derived_patch_tier_boundary_unpublished_crate_still_patches() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // `weave-only-lib` is a name that (by design) does not exist on
    // crates.io. The member declares it as a bare registry dep;
    // derived mode's index still matches it and emits the patch.
    write_file(
        root,
        "github/acme/weave-only/Cargo.toml",
        "[package]\nname = \"weave-only-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nweave-only-lib = \"0.1\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/weave-only", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        content.contains("weave-only-lib"),
        "derived-mode makes the in-weave resolution work even for \
             names that don't exist on crates.io — the tier boundary \
             is a member-standalone concern, not a weave concern; \
             got:\n{content}"
    );
    assert!(
        content.contains("github/acme/weave-only"),
        "expected the patch to point at the in-weave path; got:\n{content}"
    );
}

/// A member declaring `foo = "1.0"` when the in-weave `foo` is
/// version `2.0.0` must NOT be patched — cargo would hard-error
/// with a misleading "location searched: crates.io index" message.
/// Derived mode catches the mismatch upfront and
/// simply omits the patch (an eprintln warning surfaces the reason
/// to the operator).
#[test]
fn derived_patch_skips_incompatible_version() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"2.0.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"1.0\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // The [patch.crates-io] table must NOT carry `acme-lib` — the
    // in-weave version (2.0.0) does not satisfy the member's req
    // (1.0). It's OK if the table is absent entirely.
    assert!(
        !content.contains("acme-lib"),
        "incompatible in-weave version must skip patch emission; \
             got:\n{content}"
    );
}

/// A member depending on itself under its own crate name (weird but
/// exercisable in fixtures) must not produce a self-patch — cargo
/// would reject a patch pointing at the same manifest that declares
/// the dep.
#[test]
fn derived_patch_skips_self_patch() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Contrived: `foo` depends on `foo`. Not realistic, but the
    // guard is a correctness invariant.
    write_file(
        root,
        "github/acme/foo/Cargo.toml",
        "[package]\nname = \"foo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nfoo = \"0.1\"\n",
    );

    let manifest = make_manifest(vec![("github/acme/foo", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // No [patch.crates-io] should be generated.
    assert!(
        !content.contains("[patch.crates-io"),
        "self-patches must be skipped; got:\n{content}"
    );
}

/// Derived mode must resolve `dep.workspace = true` when the
/// workspace-deps table is reachable via the same discovery the
/// version-skew scanner uses.
///
/// Note on fixture shape: cargo's activation-time nested-workspace
/// hard-error blocks the common grok-build shape (repo root has
/// `[workspace.dependencies]`) at the weave-workspace level. The
/// `classify_dep` unit test in `cargo_workspace.rs` covers the
/// resolve path in isolation; here we exercise the fall-through
/// path — a member using `workspace = true` with **no** reachable
/// workspace-deps table must produce no derived patch (silent
/// skip, no panic).
#[test]
fn derived_patch_workspace_true_without_anchor_skips_silently() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    );
    // A member with no reachable workspace-deps table declares its
    // dep as `workspace = true`. This is a broken manifest at cargo
    // load time — but derived-mode must not panic; it must simply
    // skip the entry.
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = { workspace = true }\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    // Must not panic. The output should carry no patch entry for
    // acme-lib — the workspace = true dep is uninterpretable, so
    // derived-mode skips it. Cargo would refuse the manifest itself
    // at generate-lockfile time.
    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        !content.contains("acme-lib"),
        "unresolvable workspace = true dep must not produce a patch; \
             got:\n{content}"
    );
}

/// User-authored `[patch.crates-io].<crate>` entries survive derived
/// mode — rwv's verify-and-warn semantics apply the same as in
/// committed-paths mode.
#[test]
fn derived_patch_verify_and_warn_preserves_user_authored_entry() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Seed a Cargo.toml with a user-authored patch entry the derived
    // pass would otherwise want to write.
    write_file(
        root,
        "Cargo.toml",
        "[patch.crates-io]\nacme-lib = { git = \"https://user.example.com/acme-lib.git\" }\n",
    );
    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.1\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // User-authored entry survives (unchanged).
    assert!(
        content.contains("https://user.example.com/acme-lib.git"),
        "user-authored patch entry must survive; got:\n{content}"
    );
    // No `# managed by rwv` marker on the user entry (would be a
    // sign that we blew it away).
    //
    // The user's patch line and rwv's would land next to each other;
    // check that the user's URL is present and that we didn't
    // silently overwrite it with a `path = ...`.
    assert!(
        !content.contains("path = \"github/acme/lib\""),
        "user-authored acme-lib entry must not be overwritten by \
             derived; got:\n{content}"
    );
}

/// `patch: off` (default) and `patch: derived` with no matched deps
/// must both emit no `[patch]` table — noise-free. The activation
/// path must not create an empty table under `derived` just because
/// the mode is on.
#[test]
fn derived_patch_off_and_no_match_emit_no_table() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/foo/Cargo.toml",
        "[package]\nname = \"foo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nserde = \"1.0\"\n",
    );

    let manifest = make_manifest(vec![("github/acme/foo", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        !content.contains("[patch"),
        "no `[patch]` table should be generated when no members are \
             in-weave for the declared deps; got:\n{content}"
    );
}

/// Deactivate strips derived-mode `[patch."<git-url>"]` entries the
/// same way it strips `[patch.crates-io]` entries — the strip pass
/// enumerates every `[patch.<registry>]` sub-table, not just
/// crates-io.
#[test]
fn deactivate_strips_derived_git_patch_entries() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app"]
# managed by rwv
resolver = "2"

[patch."https://example.com/acme/lib.git"]
# managed by rwv
acme-lib = { path = "github/acme/lib" }
"#,
    );

    CargoWorkspace.deactivate(root).unwrap();

    let content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    // The git-URL patch table with a single rwv-authored entry
    // should be fully pruned.
    assert!(
        !content.contains("acme-lib"),
        "rwv-authored git-URL patch entry should be stripped; got:\n{content}"
    );
    assert!(
        !content.contains("[patch."),
        "empty [patch.\"<url>\"] table should be pruned; got:\n{content}"
    );
}

// -----------------------------------------------------------------------
// PatchSurface::CargoConfig (nesting-immune lens)
//
// The whole point here is the nested-workspace case: cargo hard-errors
// when it discovers a nested `[workspace]` inside another workspace
// member, so those repos must opt out of the weave workspace — and once
// they do, the workspace-manifest `[patch]` NEVER reaches their builds.
// The `.cargo/config.toml` surface is discovered by upward walk from cwd
// instead of by workspace membership, so it reaches the opt-out.
//
// Assertions here are structural — upward config discovery, relative
// paths, hybrid-managed ownership; a live-cargo assertion of "this
// patch would apply" against a nested-workspace fixture lives in
// e2e_cargo_test.rs — the boundary follows how existing derived-mode
// tests split (unit-level structure here, cargo-invoked structure there).
// -----------------------------------------------------------------------

/// Activate under `patch-surface: cargo-config` writes patches into
/// `.cargo/config.toml` (NOT the manifest) and rewrites weave-relative
/// paths to `../<member>` so they resolve against `.cargo/`'s logical
/// location.
#[test]
fn cargo_config_surface_writes_patches_to_dot_cargo() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    // The managed Cargo.toml exists but MUST NOT carry [patch.*] —
    // the surface routes elsewhere.
    let manifest_content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        !manifest_content.contains("[patch"),
        "cargo-config surface must not write `[patch]` into the manifest; got:\n{manifest_content}"
    );

    // The .cargo/config.toml file MUST exist and carry the patch entry.
    let config_path = root.join(".cargo").join("config.toml");
    assert!(
        config_path.exists(),
        "cargo-config surface must generate .cargo/config.toml"
    );
    let config_content = std::fs::read_to_string(&config_path).unwrap();
    assert!(
        config_content.contains("[patch.crates-io"),
        "generated config must carry [patch.crates-io]; got:\n{config_content}"
    );
    assert!(
        config_content.contains("acme-lib"),
        "generated config must carry the acme-lib key; got:\n{config_content}"
    );
    // Path stays weave-root-relative: `github/acme/lib` (no `../`).
    // Cargo resolves relative patch paths against the PARENT of
    // `.cargo/` (not `.cargo/` itself — measured directly
    // 2026-07-17). Our `.cargo/` sits directly under the weave root,
    // so a weave-root-relative path resolves the same as it does
    // on the manifest surface. NO canonicalization — resolving the
    // logical path would break a symlinked `.cargo/`.
    assert!(
        config_content.contains("\"github/acme/lib\""),
        "path must be weave-root-relative `github/acme/lib` — cargo \
             resolves patch paths in .cargo/config.toml against the parent \
             of `.cargo/`; got:\n{config_content}"
    );
    // Cross-check: no accidental `../` prefix.
    assert!(
        !config_content.contains("../github/acme/lib"),
        "path must NOT carry a `../` prefix; got:\n{config_content}"
    );
    // The rwv marker decorates the entry (same hybrid ownership as
    // the manifest surface).
    assert!(
        config_content.contains("managed by rwv"),
        "generated entry must carry rwv marker; got:\n{config_content}"
    );
}

/// The nesting-immune case: the derived-mode scan
/// finds a registry dep in an ACTIVE weave member; the patch lands in
/// `.cargo/config.toml`; a nested-workspace opt-out present in the
/// same weave picks up the patch when built from inside its dir via
/// upward config discovery.
///
/// This is the shape a real weave would have: an active member (say,
/// `chatly/server`) uses `acme-lib = "1.0"` as a registry dep, and a
/// nested-workspace opt-out (rvtty, mcp_agent_mail_rust, grok-build)
/// also uses `acme-lib` in its own build. Both consumers should see
/// the in-weave `acme-lib` — the config surface is the ONLY surface
/// that can serve both.
#[test]
fn cargo_config_surface_reaches_both_active_member_and_opt_out() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Weave-native lib.
    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    );
    // Active member consuming acme-lib (this drives the derived scan
    // to emit the patch).
    write_file(
        root,
        "github/chatly/server/Cargo.toml",
        "[package]\nname = \"chatly-server\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"1.0\"\n",
    );
    // Nested-workspace opt-out. It exists in the weave but is
    // structurally excluded from the workspace manifest — the
    // manifest surface can't patch its builds.
    write_file(
        root,
        "github/xai-org/grok-build/Cargo.toml",
        "[workspace]\nmembers = [\"crates/consumer\"]\nresolver = \"2\"\n",
    );
    write_file(
        root,
        "github/xai-org/grok-build/crates/consumer/Cargo.toml",
        "[package]\nname = \"grok-consumer\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"1.0\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/chatly/server", Role::Owned),
        ("github/xai-org/grok-build", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\nexclude = [\"github/xai-org/grok-build\"]\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    // Manifest surface is inert.
    let manifest_content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        !manifest_content.contains("[patch"),
        "cargo-config surface must not write into the manifest; got:\n{manifest_content}"
    );

    // Config surface carries the patch.
    let config_path = root.join(".cargo").join("config.toml");
    let config_content = std::fs::read_to_string(&config_path).unwrap();
    assert!(
        config_content.contains("acme-lib"),
        "patch must land in .cargo/config.toml; got:\n{config_content}"
    );
    assert!(
        config_content.contains("\"github/acme/lib\""),
        "path is weave-root-relative (cargo resolves against \
             parent-of-.cargo); got:\n{config_content}"
    );
    // The opt-out repo is present at the tested path. Cargo's upward
    // walk from grok-consumer would land on this file (structural,
    // not asserted via cargo here — see e2e_cargo_test.rs for the
    // cargo-metadata assertion).
    let opt_out_path = root.join("github/xai-org/grok-build/crates/consumer");
    assert!(opt_out_path.exists(), "opt-out repo layout expected");
}

/// The `manifest` surface remains the default: an unspecified
/// `patch-surface` behaves EXACTLY like the pre-2026 output. Zero
/// migration for existing manifests.
#[test]
fn manifest_surface_is_default_zero_migration() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    // No patch-surface key — default is manifest.
    let config = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let manifest_content = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        manifest_content.contains("[patch.crates-io"),
        "manifest surface default: patch lands in Cargo.toml; got:\n{manifest_content}"
    );
    // No `../` prefix on manifest surface — paths are weave-relative.
    assert!(
        manifest_content.contains("\"github/acme/lib\"")
            || manifest_content.contains("'github/acme/lib'"),
        "manifest surface path stays weave-relative (no `../` prefix); got:\n{manifest_content}"
    );
    // No `.cargo/config.toml` generated under manifest surface.
    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "manifest surface must NOT generate .cargo/config.toml"
    );
}

/// User-authored keys in a pre-existing `.cargo/config.toml`
/// (linker flags, per-target settings, hand-written unmarked patch
/// entries) survive activation. Same hybrid ownership as the
/// manifest surface — the marker is the pen.
#[test]
fn cargo_config_surface_preserves_user_authored_keys() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Seed a `.cargo/config.toml` with mixed user content: a linker
    // flag section, a user-authored `[patch.crates-io]` entry (no
    // rwv marker), and a hand-written comment.
    write_file(
        root,
        ".cargo/config.toml",
        r#"# hand-written weave-level policy
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[patch.crates-io]
vendor-foo = { git = "https://user.example.com/vendor-foo.git" }
"#,
    );

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();

    // User's linker flag survives.
    assert!(
        content.contains("link-arg=-fuse-ld=lld"),
        "user-authored linker flags must survive; got:\n{content}"
    );
    assert!(
        content.contains("[target.x86_64-unknown-linux-gnu]"),
        "user-authored target block must survive; got:\n{content}"
    );
    // User's hand-authored patch entry survives untouched.
    assert!(
        content.contains("https://user.example.com/vendor-foo.git"),
        "user-authored [patch.crates-io].vendor-foo must survive; got:\n{content}"
    );
    // rwv's entry landed next to it, marked.
    assert!(
        content.contains("acme-lib"),
        "rwv-derived patch must land; got:\n{content}"
    );
    assert!(
        content.contains("managed by rwv"),
        "rwv-generated entry must carry marker; got:\n{content}"
    );
}

/// Deactivate under the cargo-config surface strips the rwv-marker
/// entries from `.cargo/config.toml`, preserves user keys, and
/// deletes the file (and `.cargo/`) iff the strip leaves nothing.
#[test]
fn deactivate_strips_marked_entries_from_cargo_config_surface() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Seed the managed Cargo.toml (rwv-marker workspace).
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app"]
# managed by rwv
resolver = "2"
"#,
    );
    // Seed a `.cargo/config.toml` with mixed content: a marked
    // rwv-generated entry plus a user-authored key. Deactivate must
    // strip the former and preserve the latter.
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
# managed by rwv
acme-lib = { path = "../github/acme/lib" }
vendor-foo = { git = "https://user.example.com/vendor-foo.git" }
"#,
    );

    CargoWorkspace.deactivate(root).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(
        !content.contains("acme-lib"),
        "rwv-marker entry must be stripped from cargo-config; got:\n{content}"
    );
    assert!(
        content.contains("vendor-foo"),
        "user-authored entry must survive; got:\n{content}"
    );
}

/// Deactivate under the cargo-config surface deletes an emptied
/// `.cargo/config.toml` and prunes the parent `.cargo/` dir when it
/// too is empty. Mirrors the file-deletion rule for hybrid files.
#[test]
fn deactivate_deletes_emptied_cargo_config_and_dir() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // Managed Cargo.toml with only rwv-owned keys.
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app"]
# managed by rwv
resolver = "2"
"#,
    );
    // Cargo config with ONLY rwv-marker patch entries — after strip,
    // the file is empty.
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
# managed by rwv
acme-lib = { path = "../github/acme/lib" }
"#,
    );

    CargoWorkspace.deactivate(root).unwrap();

    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "emptied cargo-config must be deleted"
    );
    assert!(
        !root.join(".cargo").exists(),
        "empty .cargo/ dir must be pruned"
    );
}

/// Deactivate under the cargo-config surface preserves an unrelated
/// sibling in `.cargo/` (e.g. `credentials`) — the dir prune only
/// fires when the dir is EMPTY.
#[test]
fn deactivate_preserves_dot_cargo_siblings() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app"]
# managed by rwv
resolver = "2"
"#,
    );
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
# managed by rwv
acme-lib = { path = "../github/acme/lib" }
"#,
    );
    // User-authored sibling (e.g. cargo credentials).
    write_file(
        root,
        ".cargo/credentials.toml",
        "[registry]\ntoken = \"x\"\n",
    );

    CargoWorkspace.deactivate(root).unwrap();

    // Config gone.
    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "emptied cargo-config must be deleted"
    );
    // Dir SURVIVES because the sibling exists.
    assert!(
        root.join(".cargo").exists(),
        ".cargo/ must survive when it holds user siblings"
    );
    assert!(
        root.join(".cargo").join("credentials.toml").exists(),
        "user sibling must survive"
    );
}

/// The wrapper name every test on this page can rely on being
/// runnable: the binary running this test suite.
const PRESENT_WRAPPER: &str = "cargo";
const ABSENT_WRAPPER: &str = "rwv-test-absent-wrapper";

fn wrapper_ctx_parts(root: &Path) -> (Manifest, ProjectName) {
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    );
    (
        make_manifest(vec![("github/acme/app", Role::Owned)]),
        ProjectName::new("test-project").unwrap(),
    )
}

#[test]
fn rustc_wrapper_writes_marked_build_key_when_on_path() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    let config = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"));
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(
        content.contains("[build]"),
        "wrapper key must land under [build]; got:\n{content}"
    );
    assert!(
        content.contains(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"")),
        "wrapper key must carry the configured name; got:\n{content}"
    );
    assert!(
        content.contains("managed by rwv"),
        "wrapper key must carry the rwv marker; got:\n{content}"
    );
}

#[test]
fn rustc_wrapper_writes_nothing_when_binary_is_absent() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    let config = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{ABSENT_WRAPPER}\"\n"));
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "no wrapper on PATH must mean no generated .cargo/config.toml — \
             cargo hard-errors on a wrapper it cannot spawn"
    );
}

#[test]
fn rustc_wrapper_strips_marked_key_when_detection_turns_off() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    let cache = HashMap::new();

    let with = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"));
    let ctx = make_ctx(root, &project, &manifest, &with, &cache);
    CargoWorkspace.activate(&ctx).unwrap();
    assert!(root.join(".cargo").join("config.toml").exists());

    // The uninstall path: detection answers None (here via a name that
    // resolves nowhere), and the marked key — whatever value it holds —
    // must go, taking the emptied file and dir with it.
    let without = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{ABSENT_WRAPPER}\"\n"));
    let ctx = make_ctx(root, &project, &manifest, &without, &cache);
    CargoWorkspace.activate(&ctx).unwrap();

    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "stripping the only marked key must prune the file"
    );
    assert!(
        !root.join(".cargo").exists(),
        "an emptied .cargo/ dir must be pruned"
    );
}

#[test]
fn rustc_wrapper_defers_to_a_user_authored_key() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    write_file(
        root,
        ".cargo/config.toml",
        "[build]\nrustc-wrapper = \"mine\"\njobs = 4\n",
    );
    let config = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"));
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(
        content.contains("rustc-wrapper = \"mine\""),
        "an unmarked user key holds the pen; got:\n{content}"
    );
    assert!(
        !content.contains("managed by rwv"),
        "deferring must not decorate the user's key; got:\n{content}"
    );
    assert!(
        content.contains("jobs = 4"),
        "unrelated user keys must survive; got:\n{content}"
    );
}

#[test]
fn rustc_wrapper_coexists_with_cargo_config_patches() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );
    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let cache = HashMap::new();

    let both = IntegrationConfig::from_toml(&format!(
        "patch = \"derived\"\npatch-surface = \"cargo-config\"\n\
             rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"
    ));
    let ctx = make_ctx(root, &project, &manifest, &both, &cache);
    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(content.contains("[patch.crates-io"), "got:\n{content}");
    assert!(
        content.contains(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"")),
        "got:\n{content}"
    );

    // Dropping the wrapper must strip only the [build] key — the patch
    // entries and their file survive.
    let patches_only =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let ctx = make_ctx(root, &project, &manifest, &patches_only, &cache);
    CargoWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(content.contains("[patch.crates-io"), "got:\n{content}");
    assert!(
        !content.contains("rustc-wrapper"),
        "wrapper key must be stripped; got:\n{content}"
    );
}

#[test]
fn deactivate_strips_the_marked_wrapper_key() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    let config = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"));
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);
    CargoWorkspace.activate(&ctx).unwrap();
    assert!(root.join(".cargo").join("config.toml").exists());

    CargoWorkspace.deactivate(root).unwrap();

    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "deactivate must strip the marked wrapper key and prune the file"
    );
}

#[test]
fn verify_is_clean_after_wrapper_activation_and_drifts_on_a_stale_key() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    let (manifest, project) = wrapper_ctx_parts(root);
    let cache = HashMap::new();

    // The lock is activate_hook's product, which this test does not run.
    write_file(root, "Cargo.lock", "version = 3\n");

    let with = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{PRESENT_WRAPPER}\"\n"));
    let ctx = make_ctx(root, &project, &manifest, &with, &cache);
    CargoWorkspace.activate(&ctx).unwrap();
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    assert!(
        issues.is_empty(),
        "verify must be clean right after activation; got: {issues:?}"
    );

    // Config now expects no wrapper (detection answers None), but the
    // marked key is still on disk — the stale-key drift an operator
    // sees between an uninstall and the next materialization.
    let without = IntegrationConfig::from_toml(&format!("rustc-wrapper = \"{ABSENT_WRAPPER}\"\n"));
    let ctx = make_ctx(root, &project, &manifest, &without, &cache);
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    assert!(
        issues.iter().any(|i| i.message.contains("rustc-wrapper")),
        "a marked wrapper key with no detected binary must read as drift; got: {issues:?}"
    );
}

/// Structural: `PatchSurface` is an ENUM (not two booleans), so
/// enabling both surfaces at once is impossible by construction —
/// a `patch-surface` field can only carry ONE value. This is the
/// required "double-patch prevention"; it lives at the type
/// level and is confirmed here by observing that only one surface
/// ever gets written.
#[test]
fn only_one_surface_writes_per_activation() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let cache = HashMap::new();

    // Round 1: cargo-config surface.
    let config_a =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let ctx_a = make_ctx(root, &project, &manifest, &config_a, &cache);
    CargoWorkspace.activate(&ctx_a).unwrap();
    let manifest_a = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    let config_a_content =
        std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(!manifest_a.contains("[patch"), "surface a: manifest inert");
    assert!(
        config_a_content.contains("acme-lib"),
        "surface a: config carries patch"
    );

    // Round 2: manifest surface (fresh fixture — no prior state,
    // because in a real workspace a mode flip is a full re-activation).
    // Delete round 1 output first, matching activate_intent's model.
    CargoWorkspace.deactivate(root).unwrap();
    let config_b = IntegrationConfig::from_toml("patch = \"derived\"\n");
    let ctx_b = make_ctx(root, &project, &manifest, &config_b, &cache);
    CargoWorkspace.activate(&ctx_b).unwrap();
    let manifest_b = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        manifest_b.contains("[patch.crates-io"),
        "surface b: manifest carries patch"
    );
    assert!(
        !root.join(".cargo").join("config.toml").exists(),
        "surface b: config surface not written"
    );
}

/// verify() under cargo-config surface classifies MISSING /
/// USER-HELD / DRIFT / CLEAN for `.cargo/config.toml`.
#[test]
fn cargo_config_surface_verify_three_state() {
    use repoweave::integration::Integration;

    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );
    // Managed Cargo.toml must exist (verify_cargo_toml runs first).
    write_file(
        root,
        "Cargo.toml",
        r#"[workspace]
# managed by rwv
members = ["github/acme/app", "github/acme/lib"]
# managed by rwv
resolver = "2"
"#,
    );

    let manifest = make_manifest(vec![
        ("github/acme/lib", Role::Owned),
        ("github/acme/app", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    // (a) MISSING — no .cargo/config.toml yet, but patch is derived
    // and app depends on lib.
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    let has_missing = issues.iter().any(|i| {
        i.message.replace('\\', "/").contains(".cargo/config.toml") && i.message.contains("missing")
    });
    assert!(
        has_missing,
        "expected MISSING finding for .cargo/config.toml; got: {issues:?}"
    );

    // (b) DRIFT — a stale marked entry for a different crate.
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
# managed by rwv
stale-crate = { path = "../github/nowhere" }
"#,
    );
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    let has_drift = issues
        .iter()
        .any(|i| i.message.contains(".cargo/config.toml") && i.message.contains("drift"));
    assert!(
        has_drift,
        "expected DRIFT finding for stale marked entry; got: {issues:?}"
    );

    // (c) USER-HELD — same expected crate key but WITHOUT the marker.
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
acme-lib = { path = "../github/acme/lib" }
"#,
    );
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    let has_user_held = issues.iter().any(|i| {
        i.message.replace('\\', "/").contains(".cargo/config.toml")
            && i.message.contains("unmarked")
    });
    assert!(
        has_user_held,
        "expected USER-HELD finding for unmarked expected key; got: {issues:?}"
    );

    // (d) CLEAN — expected entry present with the marker.
    write_file(
        root,
        ".cargo/config.toml",
        r#"[patch.crates-io]
# managed by rwv
acme-lib = { path = "../github/acme/lib" }
"#,
    );
    let issues = CargoWorkspace.verify(&ctx).unwrap();
    let has_config_finding = issues
        .iter()
        .any(|i| i.message.contains(".cargo/config.toml"));
    assert!(
        !has_config_finding,
        "expected no cargo-config finding when marked entry matches expected; got: {issues:?}"
    );
}

/// A member's own `.cargo/config.toml` shadowing the same
/// `[patch.crates-io].<crate>` key silently defeats the weave-level
/// entry under the config surface — the same shadowing as the manifest
/// surface. The scan is target-agnostic (checks all discoverable
/// member configs regardless of where the weave writes).
#[test]
fn cargo_config_surface_shadowing_warning() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "github/acme/lib/Cargo.toml",
        "[package]\nname = \"acme-lib\"\nversion = \"0.3.5\"\nedition = \"2021\"\n",
    );
    write_file(
        root,
        "github/acme/app/Cargo.toml",
        "[package]\nname = \"acme-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\
             [dependencies]\nacme-lib = \"0.3\"\n",
    );
    // Shadowing config in the member's tree.
    write_file(
        root,
        "github/acme/app/.cargo/config.toml",
        "[patch.crates-io]\nacme-lib = { path = \"/wrong/place\" }\n",
    );

    let manifest = make_manifest(vec![
        ("github/acme/app", Role::Owned),
        ("github/acme/lib", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config =
        IntegrationConfig::from_toml("patch = \"derived\"\npatch-surface = \"cargo-config\"\n");
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    // Must not panic; write still lands. The warning is advisory
    // (captured via eprintln — not asserted here, mirroring the
    // manifest-surface counterpart which is unit-covered in
    // scan_patch_shadowing_against_keys).
    CargoWorkspace.activate(&ctx).unwrap();

    let config_content = std::fs::read_to_string(root.join(".cargo").join("config.toml")).unwrap();
    assert!(
        config_content.contains("acme-lib"),
        "output must land even when a member shadows the key; got:\n{config_content}"
    );
}
