// ===========================================================================
// uv-workspace
// ===========================================================================

use super::*;

#[test]
fn auto_detects_repos_with_pyproject_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/acme/server/pyproject.toml");
    touch(root, "github/acme/web/pyproject.toml");
    touch(root, "github/acme/docs/README.md");

    let manifest = make_manifest(vec![
        ("github/acme/server", Role::Owned),
        ("github/acme/web", Role::Owned),
        ("github/acme/docs", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = UvWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(content.contains("github/acme/server"));
    assert!(content.contains("github/acme/web"));
    assert!(!content.contains("github/acme/docs"));
}

#[test]
fn generates_pyproject_toml_with_uv_workspace() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/chatly/protocol/pyproject.toml");
    touch(root, "github/chatly/server/pyproject.toml");

    let manifest = make_manifest(vec![
        ("github/chatly/protocol", Role::Owned),
        ("github/chatly/server", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = UvWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    // Post-port: ownership is proven by the per-key `# managed by rwv`
    // decor on the managed key (TomlDoc marker). The legacy
    // `# Generated by rwv` first-line header is gone.
    assert!(
        content.contains("# managed by rwv"),
        "managed-by-rwv decor missing: {content}"
    );
    assert!(
        !content.starts_with("# Generated by rwv"),
        "legacy header must not appear"
    );
    assert!(content.contains("[tool.uv.workspace]"));
    assert!(content.contains("\"github/chatly/protocol\""));
    assert!(content.contains("\"github/chatly/server\""));
}

#[test]
fn excludes_reference_repos() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    touch(root, "github/acme/server/pyproject.toml");
    touch(root, "github/acme/reference-lib/pyproject.toml");

    let manifest = make_manifest(vec![
        ("github/acme/server", Role::Owned),
        ("github/acme/reference-lib", Role::Reference),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let integration = UvWorkspace;
    integration.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(content.contains("github/acme/server"));
    assert!(!content.contains("reference-lib"));
}

#[test]
fn deactivation_removes_pyproject_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // A file holding only the marker-decorated managed region is fully
    // rwv-owned: deactivate strips it and deletes the empty file.
    write_file(
        root,
        "pyproject.toml",
        "[tool.uv.workspace]\n# managed by rwv\nmembers = []\n",
    );
    assert!(root.join("pyproject.toml").exists());

    let integration = UvWorkspace;
    integration.deactivate(root).unwrap();
    assert!(!root.join("pyproject.toml").exists());
}

#[test]
fn deactivation_preserves_handwritten_pyproject_toml() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    // A hand-written pyproject.toml without the generated header should NOT be removed
    write_file(
        root,
        "pyproject.toml",
        "[project]\nname = \"my-project\"\nversion = \"0.1.0\"\n",
    );
    assert!(root.join("pyproject.toml").exists());

    let integration = UvWorkspace;
    integration.deactivate(root).unwrap();
    assert!(root.join("pyproject.toml").exists());
}

#[cfg(unix)]
#[test]
fn check_warns_when_uv_not_on_path() {
    let absent = doctor_json_on_tool_only_path(
        "uv-workspace",
        "github/acme/server/pyproject.toml",
        "[project]\nname = \"server\"\nversion = \"0.1.0\"\n",
        &[],
    );
    let present = doctor_json_on_tool_only_path(
        "uv-workspace",
        "github/acme/server/pyproject.toml",
        "[project]\nname = \"server\"\nversion = \"0.1.0\"\n",
        &["uv"],
    );

    tool_missing_fires_then_clears(&absent, &present, "uv-workspace", "uv");
}

// -----------------------------------------------------------------------
// uv-workspace — scenarios (GREEN)
// -----------------------------------------------------------------------
//
// Seeds use astral-sh/ruff pyproject.toml idioms (maturin + ruff + black +
// rooster). Marker = per-key `# managed by rwv` decor on
// `[tool.uv.workspace].members`. Reuses TomlDoc from C7.

/// Activate preserves a real maturin+ruff root (merge, not clobber).
#[test]
fn s6_uv_1_activate_preserves_ruff_style_root() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/server/pyproject.toml");
    touch(root, "github/astral/web/pyproject.toml");

    // Ruff-style hand-maintained root with maturin build-backend,
    // [project] with array-of-inline-tables authors, [tool.ruff.lint],
    // [tool.black] with triple-quoted force-exclude, [tool.rooster] with
    // an inline comment.
    write_file(
        root,
        "pyproject.toml",
        r#"[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "acme"
version = "0.1.0"
authors = [
    { name = "Alice", email = "alice@example.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://example.com"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F"]

[tool.black]
force-exclude = '''
/(
    | \.eggs
    | build
)/
'''

[tool.rooster]
major_labels = []  # Ruff never uses major bumps
"#,
    );

    let manifest = make_manifest(vec![
        ("github/astral/server", Role::Owned),
        ("github/astral/web", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    let path = root.join("pyproject.toml");
    contract::assert_activate_preserves_foreign(
        &path,
        || {
            UvWorkspace.activate(&ctx).unwrap();
        },
        &[
            contract::substr_probe("members[server]", "github/astral/server"),
            contract::substr_probe("members[web]", "github/astral/web"),
        ],
        &contract::substr_probe("toml marker on members", "managed by rwv"),
        &[
            "build-backend = \"maturin\"",
            "name = \"acme\"",
            "{ name = \"Alice\", email = \"alice@example.com\" }",
            "[project.urls]",
            "[tool.ruff.lint]",
            "select = [\"E\", \"F\"]",
            "[tool.black]",
            "force-exclude = '''",
            "build",
            "Ruff never uses major bumps",
            "[tool.rooster]",
        ],
    );

    // The legacy `# Generated by rwv` line MUST NOT be the first line of
    // the file — it would either replace `[build-system]` (the bug) or
    // inject a header into a user file. Both are rejected.
    let text = std::fs::read_to_string(&path).unwrap();
    assert!(
        !text.starts_with("# Generated by rwv"),
        "legacy header must not be at line 1 of a user-authored file; \
             got first line: {:?}",
        text.lines().next()
    );
}

/// Add a repo: idempotent, only mutates members; user
/// `[tool.uv.sources]` entries that aren't `{workspace=true}` survive.
#[test]
fn s6_uv_2_add_member_preserves_user_sources() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/server/pyproject.toml");

    // Pre-existing seed: already-activated state with rwv marker decor +
    // user-added [tool.uv.sources] non-workspace entry.
    write_file(
        root,
        "pyproject.toml",
        r#"[project]
name = "acme"
version = "0.1.0"

[tool.ruff]
line-length = 100

[tool.uv.workspace]
# managed by rwv
members = ["github/astral/server"]

[tool.uv.sources]
some-private-lib = { git = "https://example.com/some-private-lib.git" }
"#,
    );

    // Web added to manifest.
    touch(root, "github/astral/web/pyproject.toml");
    let manifest = make_manifest(vec![
        ("github/astral/server", Role::Owned),
        ("github/astral/web", Role::Owned),
    ]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    UvWorkspace.activate(&ctx).unwrap();
    let after_first = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();

    // Second activate: must be idempotent.
    UvWorkspace.activate(&ctx).unwrap();
    let after_second = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert_eq!(
        after_first, after_second,
        "second activate must be byte-identical"
    );

    // members contains both, no dup.
    assert!(after_second.contains("github/astral/server"));
    assert!(after_second.contains("github/astral/web"));
    // Exactly one marker decor — no duplication.
    let marker_count = after_second.matches("managed by rwv").count();
    assert_eq!(marker_count, 1, "marker must appear exactly once");
    // User git source survives.
    assert!(
        after_second.contains("some-private-lib"),
        "user [tool.uv.sources] entry must survive; got:\n{after_second}"
    );
    assert!(
        after_second.contains("https://example.com/some-private-lib.git"),
        "user git URL must survive; got:\n{after_second}"
    );
    // User policy survives.
    assert!(after_second.contains("[project]"));
    assert!(after_second.contains("[tool.ruff]"));
}

/// Deactivate strips only rwv keys, keeps the manifest.
/// User non-workspace sources survive.
#[test]
fn s6_uv_3_deactivate_strips_keeps_user_manifest() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();

    write_file(
        root,
        "pyproject.toml",
        r#"[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "acme"
version = "0.1.0"

[tool.ruff]
line-length = 100

[tool.uv.workspace]
# managed by rwv
members = ["github/astral/server", "github/astral/web"]

[tool.uv.sources]
# managed by rwv
server = { workspace = true }
some-private-lib = { git = "https://example.com/some-private-lib.git" }
"#,
    );

    UvWorkspace.deactivate(root).unwrap();

    assert!(
        root.join("pyproject.toml").exists(),
        "pyproject.toml must NOT be deleted (foreign content remains)"
    );
    let content = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    // rwv-owned regions gone.
    assert!(
        !content.contains("[tool.uv.workspace]"),
        "[tool.uv.workspace] must be stripped; got:\n{content}"
    );
    assert!(
        !content.contains("workspace = true"),
        "{{workspace=true}} source must be stripped; got:\n{content}"
    );
    assert!(
        !content.contains("managed by rwv"),
        "marker decor must be removed; got:\n{content}"
    );
    // User content survives.
    assert!(content.contains("build-backend = \"maturin\""));
    assert!(content.contains("[project]"));
    assert!(content.contains("[tool.ruff]"));
    // User git source survives.
    assert!(
        content.contains("some-private-lib"),
        "user [tool.uv.sources] entry must survive; got:\n{content}"
    );
    assert!(
        content.contains("https://example.com/some-private-lib.git"),
        "user git URL must survive"
    );
}

/// Greenfield root: rwv creates pyproject.toml from scratch with
/// `package=false`; deactivate removes the managed region but preserves
/// `package = false` (it is a `DefaultOnly` key — user-adjustable, never
/// stripped). The file survives deactivation with only the DefaultOnly key.
#[test]
fn s6_uv_4_greenfield_create_then_deactivate_preserves_package_false() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/protocol/pyproject.toml");

    // No root pyproject.toml.
    assert!(!root.join("pyproject.toml").exists());

    let manifest = make_manifest(vec![("github/astral/protocol", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    UvWorkspace.activate(&ctx).unwrap();

    let content = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(content.contains("github/astral/protocol"));
    // greenfield must set package = false so uv sync accepts the root.
    assert!(
        content.contains("package = false") || content.contains("package=false"),
        "greenfield root must declare [tool.uv].package = false; got:\n{content}"
    );

    // Marker must be present so deactivate can identify it.
    assert!(
        content.contains("managed by rwv"),
        "marker required for deactivate to act; got:\n{content}"
    );

    UvWorkspace.deactivate(root).unwrap();

    // package = false is DefaultOnly — it is NOT stripped on deactivate.
    // The file survives with only the DefaultOnly key; it is not deleted.
    assert!(
        root.join("pyproject.toml").exists(),
        "file must survive deactivate — package=false (DefaultOnly) was not stripped"
    );
    let after = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(
        after.contains("package = false") || after.contains("package=false"),
        "package=false must survive deactivate (DefaultOnly key); got:\n{after}"
    );
    // The managed region (members, marker) must be gone.
    assert!(
        !after.contains("managed by rwv"),
        "marker must be removed on deactivate; got:\n{after}"
    );
    assert!(
        !after.contains("members"),
        "members key must be stripped on deactivate; got:\n{after}"
    );
}

// -----------------------------------------------------------------------
// DefaultOnly regression tests for [tool.uv].package
// -----------------------------------------------------------------------

/// Regression — user opt-in: file with marker present + user has set
/// `[tool.uv].package = true` → after activate, stays `true`.
/// `DefaultOnly` must never overwrite an existing value.
#[test]
fn default_only_does_not_overwrite_user_set_package_true() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/protocol/pyproject.toml");

    // Pre-existing pyproject.toml with marker on members + user-set package = true.
    write_file(
        root,
        "pyproject.toml",
        concat!(
            "[tool.uv.workspace]\n",
            "# managed by rwv\n",
            "members = [\"github/astral/protocol\"]\n",
            "\n",
            "[tool.uv]\n",
            "package = true\n",
        ),
    );

    let manifest = make_manifest(vec![("github/astral/protocol", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    UvWorkspace.activate(&ctx).unwrap();

    let after = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(
        after.contains("package = true"),
        "user-set package=true must survive activate (DefaultOnly never overwrites); got:\n{after}"
    );
    assert!(
        !after.contains("package = false"),
        "DefaultOnly must not inject package=false when key is present; got:\n{after}"
    );
}

/// Regression — greenfield: fresh file (no root pyproject.toml) gets
/// `[tool.uv].package = false` set by DefaultOnly.
#[test]
fn default_only_sets_package_false_on_greenfield() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/protocol/pyproject.toml");

    // No root pyproject.toml — greenfield.
    assert!(!root.join("pyproject.toml").exists());

    let manifest = make_manifest(vec![("github/astral/protocol", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    UvWorkspace.activate(&ctx).unwrap();

    let after = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(
        after.contains("package = false") || after.contains("package=false"),
        "greenfield file must get package=false from DefaultOnly; got:\n{after}"
    );
}

/// Regression — pre-existing without override: file with marker + no
/// `[tool.uv].package` key → DefaultOnly sets `false`.
#[test]
fn default_only_sets_package_false_when_key_absent() {
    let tmp = common::tempdir().unwrap();
    let root = tmp.path();
    touch(root, "github/astral/protocol/pyproject.toml");

    // File exists, has marker on members, but no package key.
    write_file(
        root,
        "pyproject.toml",
        concat!(
            "[tool.uv.workspace]\n",
            "# managed by rwv\n",
            "members = [\"github/astral/protocol\"]\n",
        ),
    );

    let manifest = make_manifest(vec![("github/astral/protocol", Role::Owned)]);
    let project = ProjectName::new("test-project").unwrap();
    let config = IntegrationConfig::default();
    let cache = HashMap::new();
    let ctx = make_ctx(root, &project, &manifest, &config, &cache);

    UvWorkspace.activate(&ctx).unwrap();

    let after = std::fs::read_to_string(root.join("pyproject.toml")).unwrap();
    assert!(
        after.contains("package = false") || after.contains("package=false"),
        "pre-existing file without package key must get package=false from DefaultOnly; got:\n{after}"
    );
}
