//! Cargo-workspace integration.
//!
//! Generates the `[workspace]` region of a hybrid root `Cargo.toml` declaring
//! every Rust repo in the active project as a workspace member, then lets
//! `cargo generate-lockfile` produce a shared `Cargo.lock`.
//!
//! ## Hybrid file ownership (the cargo merge port)
//!
//! `Cargo.toml` is a **hybrid** file: rwv owns a declared key set, the user
//! owns everything else. Authoring goes through the shared `TomlDoc`
//! helper in [`crate::integrations::merge`], which preserves comments, key
//! order, profile blocks, lints, `[patch]` tables, and per-key formatting
//! byte-for-semantics across `toml_edit::DocumentMut` round-trips.
//!
//! **Owned keys** (the only bytes rwv writes):
//! - `[workspace].members`
//! - `[workspace].resolver` (always `"2"`)
//! - `[workspace.package]` (only when `workspace-package: true`)
//!
//! Everything else — `[profile.*]`, `[workspace.dependencies]`,
//! `[workspace.lints.*]`, `[workspace.metadata.*]`, `[patch.*]`, stray
//! top-level `[package]`, comments — is user policy and is **never**
//! written or stripped.
//!
//! **Marker:** the per-key TOML decoration `# managed by rwv` (a comment
//! line attached as the prefix of each owned key). Position-independent;
//! survives reordering; never injects a top-level header into a user file.
//! See [`crate::integrations::merge::TomlDoc`] for the format details.
//!
//! **Activate** = read-or-empty → merge-set the owned keys (via
//! `merge_activate`) → write. If the file is missing it is created with
//! only the managed region. The legacy `# Generated by rwv` first-line
//! header is gone.
//!
//! **Deactivate** = `strip_deactivate` — gate on the marker, strip the
//! owned keys, prune empty `[workspace]`, delete the file iff it would
//! otherwise be empty. Hand-written `Cargo.toml` files (no marker) are
//! left strictly alone — the strip is a no-op.
//!
//! ## Design decisions — locked in plan §7.2
//!
//! **(a) Members sub-path config.** `CargoWorkspaceConfig::members` maps a
//! repo path string to a `MemberSpec{include, exclude}`. When a repo appears
//! in this map, its root is NOT treated as a member; instead,
//! `<repo>/<inc_path>` is emitted for each `include` entry minus `exclude`.
//! Repos absent from the map keep the current root-as-member auto-behavior.
//! This is what lets rvtty (no root `Cargo.toml`, sub-packages `daemon/`,
//! `client/`, `common/`) contribute its packages to the weave workspace
//! instead of being excluded. See `cargo-workspace-vs-repo.md` §179–212.
//!
//! **(b) Merge-preserve scope.** Owns ONLY `[workspace].members`,
//! `[workspace].resolver`, and (behind `workspace_package: true`)
//! `[workspace.package]`. All other tables are user policy and survive
//! every activate/deactivate cycle unmodified.
//!
//! **(c) Cross-repo path deps / `[patch]` opt-in.** Default
//! (`patch: false`): all-internal — operators commit relative `path = "..."`
//! deps in member manifests; rwv never touches them. When `patch: true`,
//! `activate()` scans each member's `Cargo.toml` for cross-repo path deps
//! (entries whose resolved path lands inside another known member dir) and
//! writes `[patch.crates-io].<crate> = { path = "<member>" }` entries at the
//! weave-root `Cargo.toml`, each decorated with the `# managed by rwv`
//! marker. User-authored `[patch.crates-io]` entries are preserved
//! (verify-and-warn at the entry level); `deactivate` strips only the
//! marked entries, then prunes the table if empty.
//!
//! **(d) Nested-workspace hard error.** Refinement: a repo listed under
//! `members.<repo>` is exempt from the `declares_workspace()` check on its
//! **root** (its sub-packages, not its root, are the declared members).
//! However, if such a repo's root *does* declare `[workspace]`, that is still
//! a hard error — the ancestor-walk would bind sub-packages to it.
//!
//! ## Per-repo opt-out
//!
//! Repos can be opted out of the cargo workspace via the integration config:
//!
//! ```yaml
//! integrations:
//!   cargo-workspace:
//!     exclude:
//!       - github/cwalv/mcp_agent_mail_rust
//! ```
//!
//! Opted-out repos are dropped from `members`. (The pre-port behavior of
//! emitting `# excluded: <path> (opted out)` comments above the `[workspace]`
//! block is gone — the TomlDoc helper authors keys, not free-floating
//! comments. Operators see exclusions in `rwv.yaml`; surfacing them via
//! `check()` is a separate concern.)
//!
//! Opt-out keys that don't match any active Rust repo are silently ignored
//! (so leaving a stale entry behind after removing a repo is not an error).

use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use crate::integrations::merge::{
    drift_issues, keypath, merge_activate, missing_issue, strip_deactivate, toml_array_strings,
    KeyPath, ManagedDoc, MergeResult, OwnedValue, Ownership, TomlDoc,
};
use crate::manifest::{CargoWorkspaceConfig, MemberSpec};
use anyhow::Context;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

pub struct CargoWorkspace;

impl CargoWorkspace {
    /// Are there active cargo workspace contributions in this context?
    ///
    /// Returns `true` if at least one of:
    /// - a repo with a root `Cargo.toml` is detected (the usual case), OR
    /// - a configured `members.<repo>` entry names an active manifest repo
    ///   (the members-subpath case, e.g. rvtty — no root file but
    ///   `cfg.members.<repo>.include` contributes sub-packages).
    ///
    /// The second arm is what unblocks the members-subpath scenario: without it
    /// `activate()` early-returns and the rvtty case never reaches
    /// `partition()`.
    fn has_active_cargo_work(ctx: &IntegrationContext, cfg: &CargoWorkspaceConfig) -> bool {
        if !ctx.detect_repos_with_manifest("Cargo.toml").is_empty() {
            return true;
        }
        // Any configured-members repo that is active in the manifest counts.
        ctx.active_repos()
            .any(|(rp, _)| cfg.members.contains_key(rp.as_str()))
    }

    /// Compute the sorted member-path list and the nested-workspace
    /// conflict list for the active Rust repos.
    ///
    /// Behavior:
    /// - A repo in `cfg.exclude` is dropped entirely (no member emitted, no
    ///   workspace check).
    /// - A repo listed under `cfg.members` (a `MemberSpec`) does NOT
    ///   contribute its root as a member; it contributes
    ///   `<repo>/<inc>` for each `inc` in `include` minus `exclude` instead.
    ///   Its root is exempt from the `declares_workspace()` check **unless**
    ///   the root itself actually declares `[workspace]` (still a hard error —
    ///   the ancestor-walk binds sub-packages to it).
    /// - Any other Rust repo contributes its root as a member; if the root
    ///   declares `[workspace]`, it joins the nested-conflict list.
    ///
    /// **Members-subpath repos without a root Cargo.toml**: a
    /// repo listed under `cfg.members` whose root has no `Cargo.toml` (the
    /// canonical rvtty olb.5.4 shape — sub-packages `daemon/`/`client/`/...
    /// with no root manifest) is still emitted: `detect_repos_with_manifest`
    /// would miss it (its filter is "Cargo.toml at the root"), but the
    /// `members.<repo>` config is the explicit "this repo contributes sub-
    /// path packages" signal. With no root file there is no `[workspace]` to
    /// conflict with, so the nested-workspace check is moot for that path.
    ///
    /// Returns `(members, nested_conflicts)`. `members` is sorted
    /// lexicographically (the on-disk ordering the toml_edit array honors).
    fn partition(
        ctx: &IntegrationContext,
        cfg: &CargoWorkspaceConfig,
    ) -> anyhow::Result<(Vec<String>, Vec<String>)> {
        let rust_repos = ctx.detect_repos_with_manifest("Cargo.toml");
        let rust_repo_set: BTreeSet<&str> = rust_repos.iter().map(String::as_str).collect();
        let opt_out: BTreeSet<&str> = cfg.exclude.iter().map(String::as_str).collect();

        // Build the iteration set: union of (a) repos with a root Cargo.toml
        // and (b) configured-member repos that are active in the manifest.
        // The second set is what unblocks the rvtty case — a repo whose
        // sub-packages are the members has no root file, so detect_repos_*
        // misses it; the explicit cfg.members entry provides the signal.
        let active_members_in_cfg: BTreeSet<String> = ctx
            .active_repos()
            .map(|(rp, _)| rp.as_str().to_string())
            .filter(|p| cfg.members.contains_key(p))
            .collect();

        let mut all_repos: BTreeSet<String> = BTreeSet::new();
        all_repos.extend(rust_repos.iter().cloned());
        all_repos.extend(active_members_in_cfg.iter().cloned());

        let mut members: Vec<String> = Vec::new();
        let mut nested_conflicts: Vec<String> = Vec::new();

        for repo in &all_repos {
            if opt_out.contains(repo.as_str()) {
                continue;
            }

            // Only read the root Cargo.toml if it actually exists. A
            // members-subpath repo (no root Cargo.toml) skips this — the
            // nested-workspace check is moot when there is no root manifest
            // to declare `[workspace]`.
            let root_has_workspace = if rust_repo_set.contains(repo.as_str()) {
                let cargo_toml = ctx.workspace_root.join(repo).join("Cargo.toml");
                let content = std::fs::read_to_string(&cargo_toml)
                    .with_context(|| format!("failed to read {}", cargo_toml.display()))?;
                declares_workspace(&content)
            } else {
                false
            };

            if let Some(spec) = cfg.members.get(repo) {
                // members.<repo> sub-path mode.
                // Refinement (plan §7.2-d): if the repo root itself declares
                // [workspace] this is STILL a hard error — sub-packages can't
                // dodge an ancestor workspace declaration via member
                // configuration.
                if root_has_workspace {
                    nested_conflicts.push(repo.clone());
                    continue;
                }
                for sub in resolve_member_spec(spec) {
                    members.push(format!("{repo}/{sub}"));
                }
            } else if root_has_workspace {
                nested_conflicts.push(repo.clone());
            } else {
                members.push(repo.clone());
            }
        }

        members.sort();
        members.dedup();
        Ok((members, nested_conflicts))
    }

    /// Enumerate cargo-workspace members for the READ-ONLY scan path
    /// (version-skew + patch-shadowing).
    ///
    /// Distinct from [`partition`] (activation-time): the scan path must
    /// include repos whose root declares `[workspace]` (grok-build shape),
    /// because that is where `[workspace.dependencies]` typically lives.
    /// Activation still hard-errors on those repos (they cannot be members
    /// of the weave workspace); the scan just reads them.
    ///
    /// Returned member paths are weave-relative and sorted. When a repo has
    /// a `members.<repo>` sub-path spec (rvtty-style), its sub-paths are
    /// emitted; when a repo is a nested workspace, its ROOT is emitted (the
    /// scanner then reads `<root>/Cargo.toml`'s `[workspace.dependencies]`
    /// directly). Opt-outs are respected.
    pub fn scan_members(
        ctx: &IntegrationContext,
        cfg: &CargoWorkspaceConfig,
    ) -> anyhow::Result<Vec<String>> {
        let rust_repos = ctx.detect_repos_with_manifest("Cargo.toml");
        let rust_repo_set: BTreeSet<&str> = rust_repos.iter().map(String::as_str).collect();
        let opt_out: BTreeSet<&str> = cfg.exclude.iter().map(String::as_str).collect();

        let active_members_in_cfg: BTreeSet<String> = ctx
            .active_repos()
            .map(|(rp, _)| rp.as_str().to_string())
            .filter(|p| cfg.members.contains_key(p))
            .collect();

        let mut all_repos: BTreeSet<String> = BTreeSet::new();
        all_repos.extend(rust_repos.iter().cloned());
        all_repos.extend(active_members_in_cfg.iter().cloned());

        let mut members: Vec<String> = Vec::new();
        for repo in &all_repos {
            if opt_out.contains(repo.as_str()) {
                continue;
            }
            // members-subpath repo: emit each sub-path exactly like
            // activation. Do NOT skip if the root declares [workspace] —
            // activation's hard-error is orthogonal to the scan.
            if let Some(spec) = cfg.members.get(repo) {
                for sub in resolve_member_spec(spec) {
                    members.push(format!("{repo}/{sub}"));
                }
                continue;
            }
            // Default: emit the repo root if it has a Cargo.toml. This
            // includes nested-workspace repos (grok-build shape) for the
            // scan — activation still bails on them via `partition`, but
            // the scanner can still read their `[workspace.dependencies]`.
            if rust_repo_set.contains(repo.as_str()) {
                members.push(repo.clone());
            }
        }
        members.sort();
        members.dedup();
        Ok(members)
    }

    /// Build the (key, ownership, value) triples the merge helper will set
    /// during `activate()`. Pure — no I/O.
    fn owned_pairs(
        members: &[String],
        cfg: &CargoWorkspaceConfig,
    ) -> Vec<(KeyPath, Ownership, OwnedValue)> {
        let mut owned: Vec<(KeyPath, Ownership, OwnedValue)> = Vec::with_capacity(3);

        owned.push((
            keypath(["workspace", "members"]),
            Ownership::Author,
            OwnedValue::Array(members.to_vec()),
        ));
        owned.push((
            keypath(["workspace", "resolver"]),
            Ownership::DefaultOnly,
            OwnedValue::String("2".to_string()),
        ));

        if cfg.workspace_package {
            // The cargo-workspace-vs-repo.md design surfaces `rwv.yaml`
            // `project.{license, authors, description, repository, ...}` into
            // `[workspace.package]`. The Manifest type does not yet carry a
            // `project` section (cargo-workspace-vs-repo.md §324-376 is the
            // forward-looking design; the manifest extension is a separate
            // work item). Until that lands, the opt-in writes an empty
            // `[workspace.package]` table.
            //
            // The wiring is correct: when the project metadata field lands,
            // populate the BTreeMap below from it; the TomlDoc merge-into-
            // existing-table behavior will set each sub-key while preserving
            // user-added ones.
            owned.push((
                keypath(["workspace", "package"]),
                Ownership::Author,
                OwnedValue::Object(std::collections::BTreeMap::new()),
            ));
        }

        owned
    }
}

impl Integration for CargoWorkspace {
    fn name(&self) -> &str {
        "cargo-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;

        // Early-return when there are no rust repos AND no configured members.
        // A members-subpath repo (e.g. rvtty: no root Cargo.toml) is invisible
        // to detect_repos_with_manifest but is the explicit signal that this
        // repo contributes sub-package members; we must still proceed.
        if !Self::has_active_cargo_work(ctx, &cfg) {
            return Ok(());
        }

        let (members, nested_conflicts) = Self::partition(ctx, &cfg)?;

        if !nested_conflicts.is_empty() {
            anyhow::bail!("{}", nested_workspace_error(&nested_conflicts));
        }

        // `output_dir = project_dir` (plan §4.1) — the committed `Cargo.toml`
        // lives in the project directory and the weave-root symlink surfaces
        // it. Writing through `output_dir` writes into the committed file.
        let path = ctx.output_dir.join("Cargo.toml");
        let owned = Self::owned_pairs(&members, &cfg);

        let _result: MergeResult = merge_activate::<TomlDoc>(&path, &owned)
            .with_context(|| format!("merge-activate {}", path.display()))?;

        // When `cfg.patch == true`, opt the weave into rwv-generated `[patch]`
        // entries for cross-repo path deps (plan §5a-c). Patch entries are
        // dynamic (one per cross-repo path dep), not a fixed owned-key set,
        // so they don't fit `merge_activate`'s static `(KeyPath, OwnedValue)`
        // contract; we write them post-merge using toml_edit directly.
        //
        // Each entry is an inline table `<crate> = { path = "<rel>" }` under
        // `[patch.crates-io]`, decorated with the `# managed by rwv` marker
        // on the leaf key so the strip-deactivate pass can discriminate
        // rwv-authored entries from user-authored ones.
        if cfg.patch {
            let patches = Self::compute_patches(ctx, &members)
                .context("computing cross-repo path-dep patches")?;
            if !patches.is_empty() {
                Self::merge_patch_entries(&path, &patches)
                    .with_context(|| format!("merge-patch {}", path.display()))?;
            }
        }

        // `MergeResult.deferred` lists keys the user took the pen on (a
        // hand-written `[workspace]` block with no marker). The trigger-model
        // story is that context verbs verify-and-warn rather than author;
        // surfacing deferrals as `Severity::Warning` is a framework concern
        // tracked by C3 (`generated_files()` split + verify split). For now
        // the merge silently defers — consistent with the pre-port behavior
        // of leaving hand-written files alone.

        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        // `root` is the project_dir per the framework's deactivate contract
        // (`integration_runner::run_deactivations`). It is the same path
        // `output_dir` resolved to during activate.
        let path = root.join("Cargo.toml");

        // First pass: strip Author-owned keys (members, workspace.package).
        // DefaultOnly keys (resolver) are excluded from this list — their
        // values survive deactivation (operator may have customized them).
        let author_keys = Self::deactivate_owned_keys();
        strip_deactivate::<TomlDoc>(&path, &author_keys)
            .with_context(|| format!("strip-deactivate {}", path.display()))?;

        // Second pass: remove the `# managed by rwv` marker decor from
        // DefaultOnly keys without removing their values. resolver is
        // DefaultOnly — its value stays but the decoration must be cleaned up
        // so the file doesn't carry stale rwv annotations post-deactivation.
        Self::undecorate_default_only_keys(&path)
            .with_context(|| format!("undecorate-default-only {}", path.display()))?;

        // Third pass: strip rwv-marker-decorated `[patch.crates-io].*`
        // entries. This is independent of the workspace marker — patch
        // entries carry their own per-key marker decor, so they may need
        // stripping even when `strip_deactivate` left the file unchanged
        // (e.g. the user holds the pen on `[workspace]`). The generic
        // strip_deactivate has no static handle on the dynamic
        // patch.crates-io.<name> key set, so this is handled here.
        Self::strip_marked_patch_entries(&path)
            .with_context(|| format!("strip-patch {}", path.display()))?;

        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;
        if !Self::has_active_cargo_work(ctx, &cfg) {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("cargo").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "cargo is not on PATH".to_string(),
                safe_to_fix: true,
            });
        }

        // Surface nested-workspace conflicts as errors during `rwv doctor`
        // so operators see the same diagnostic without having to run lock.
        let (_, nested_conflicts) = Self::partition(ctx, &cfg)?;
        if !nested_conflicts.is_empty() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Error,
                message: nested_workspace_error(&nested_conflicts),
                safe_to_fix: true,
            });
        }

        Ok(issues)
    }

    fn activate_hook(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;
        if !Self::has_active_cargo_work(ctx, &cfg) {
            return Ok(());
        }

        // Run from workspace_root: that's where activation symlinks are
        // in place so cargo sees the workspace the user sees. output_dir
        // (project_dir) is where the canonical Cargo.toml lives, but the
        // member paths in it are resolved relative to the symlink at
        // workspace_root.
        let status = std::process::Command::new("cargo")
            .arg("generate-lockfile")
            .current_dir(ctx.workspace_root)
            .status()
            .context("failed to run cargo")?;

        if !status.success() {
            anyhow::bail!("cargo generate-lockfile failed (exit {})", status);
        }

        Ok(())
    }

    /// `Cargo.lock` is fully-owned — gitignore-eligible, whole-deletable.
    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        let Ok(cfg) = ctx.config.settings::<CargoWorkspaceConfig>() else {
            return vec![];
        };
        if !Self::has_active_cargo_work(ctx, &cfg) {
            return vec![];
        }
        vec!["Cargo.lock".to_string()]
    }

    /// Verify that the on-disk `Cargo.toml` reflects the current intent
    /// (`rwv.yaml` membership configuration). Called by `rwv doctor` and
    /// context verbs; **read-only** — never authors content.
    ///
    /// Three findings (see the verify design doc for rationale):
    ///
    /// - **MISSING** (`safe_to_fix = true`): file absent; `--fix` regenerates.
    /// - **DRIFT** (`safe_to_fix = true`): markers present but on-disk values
    ///   of owned keys differ from config; `--fix` regenerates.
    /// - **USER-HELD** (`safe_to_fix = false`): file present with
    ///   `[workspace]` members/resolver but **no** `# managed by rwv` marker
    ///   on the owned keys — the user holds the pen. Doctor surfaces the
    ///   finding but never auto-overwrites.
    ///
    /// CLEAN (no issues) when markers present AND values match config.
    fn verify(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;

        if !Self::has_active_cargo_work(ctx, &cfg) {
            return Ok(vec![]);
        }

        let path = ctx.output_dir.join("Cargo.toml");

        // ── MISSING ────────────────────────────────────────────────────────
        if !path.exists() {
            return Ok(vec![missing_issue(self.name(), &path)]);
        }

        // Parse the on-disk file. A parse failure is surfaced as an error
        // (can't assess drift on a malformed file, and auto-repair of a
        // malformed file is potentially data-lossy).
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {} for verify", path.display()))?;
        let toml_doc = TomlDoc::parse(&text)
            .with_context(|| format!("parsing {} for verify", path.display()))?;
        // Also parse as toml_edit::DocumentMut for reading values.
        let edit_doc: toml_edit::DocumentMut = text
            .parse()
            .with_context(|| format!("parsing {} for verify (toml_edit)", path.display()))?;

        // Build the owned key set (same as activate uses).
        let owned_keys: Vec<KeyPath> = vec![
            keypath(["workspace", "members"]),
            keypath(["workspace", "resolver"]),
        ];

        let marker_present = toml_doc.has_marker(&owned_keys);

        // cargo's USER-HELD predicate is bespoke: members OR resolver present
        // (either owned [workspace] key counts). The other five integrations
        // have a single owned key; cargo's two-key OR stays here, and the
        // result feeds the shared four-state dispatch.
        let owned_key_present = toml_doc.key_present(&keypath(["workspace", "members"]))
            || toml_doc.key_present(&keypath(["workspace", "resolver"]));

        // The nested-conflict early-return is cargo-specific and must run
        // BETWEEN USER-HELD and DRIFT (a conflict suppresses the DRIFT finding
        // — `check()` already surfaces it as an Error — but USER-HELD still
        // wins if the user holds the pen). So handle USER-HELD first via the
        // shared helper, then short-circuit on conflicts, then let the helper
        // decide DRIFT vs CLEAN.
        if !marker_present && owned_key_present {
            return Ok(drift_issues(
                self.name(),
                &path,
                marker_present,
                owned_key_present,
                None,
                &[],
                "Cut over manually by removing [workspace] from the file \
                 or by exercising the intent-mode merge",
                "",
            ));
        }

        // Only `Ownership::Author` keys are checked for drift:
        //   - `members` is `Ownership::Author` → drift is a DRIFT finding.
        //   - `resolver` is `Ownership::DefaultOnly` → operators may override
        //     it (e.g. `resolver = "1"` for compat); any on-disk value is
        //     CLEAN. Skip the resolver drift check entirely.
        let (members, nested_conflicts) = Self::partition(ctx, &cfg)?;
        if !nested_conflicts.is_empty() {
            // Nested-workspace conflict: activation would fail anyway;
            // don't add a misleading DRIFT finding on top of the check error.
            return Ok(vec![]);
        }

        // Read on-disk members. resolver is DefaultOnly — not checked for drift
        // (always CLEAN). Only `members` (Ownership::Author) is compared; the
        // shared helper sorts + dedups both sides and emits DRIFT/CLEAN.
        // `None` (no `members` key) is distinct from present-but-empty: an
        // absent owned key is always DRIFT even when `members` (expected) is
        // empty — preserves the pre-lift `Option` compare exactly.
        let on_disk = toml_array_strings(&edit_doc, &["workspace", "members"]);

        Ok(drift_issues(
            self.name(),
            &path,
            marker_present,
            owned_key_present,
            on_disk.as_deref(),
            &members,
            "Cut over manually by removing [workspace] from the file \
             or by exercising the intent-mode merge",
            "on-disk [workspace] content differs from rwv.yaml config.",
        ))
    }

    /// `Cargo.toml` is **hybrid** (rwv owns the `[workspace]` region; the
    /// user owns `[profile.*]`, `[workspace.lints.*]`, `[workspace.dependencies]`,
    /// `[patch.*]`, comments, etc.). It MUST NOT appear in
    /// `generated_files()` — that would mark it gitignore-eligible and
    /// whole-deletable, the exact data-loss bug the merge port fixes.
    fn managed_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        let mut files = self.generated_files(ctx);
        let Ok(cfg) = ctx.config.settings::<CargoWorkspaceConfig>() else {
            return files;
        };
        if Self::has_active_cargo_work(ctx, &cfg) {
            files.push("Cargo.toml".to_string());
        }
        files
    }
}

impl CargoWorkspace {
    /// The owned key paths stripped on `deactivate(root)`. Static because
    /// `Integration::deactivate` has no `IntegrationContext` — see
    /// `integration.rs:154`. Plan §3 / §11 res #15:
    ///
    /// - `members` is stripped unconditionally — it is an `Ownership::Author`
    ///   key.
    /// - `resolver` is `Ownership::DefaultOnly`: operators may have adjusted
    ///   it after rwv wrote the initial default, so it is **not** stripped on
    ///   deactivate. The operator's value (e.g. `"1"`) is intentional and
    ///   must survive the deactivation cycle.
    /// - `workspace.package` is also stripped unconditionally. The marker
    ///   gate in `strip_deactivate` is per-key: if the key was never
    ///   authored (the opt-in was off), no decor exists, and the strip is a
    ///   no-op for that key. If it WAS authored, stripping is correct.
    ///   This avoids leaking the activate-time `workspace_package` boolean
    ///   into the deactivate path (which doesn't have the config).
    fn deactivate_owned_keys() -> Vec<KeyPath> {
        vec![
            keypath(["workspace", "members"]),
            // resolver is Ownership::DefaultOnly — not stripped on deactivate.
            keypath(["workspace", "package"]),
        ]
    }

    /// Remove the `# managed by rwv` decoration from DefaultOnly keys that
    /// survive deactivation. The key VALUE is preserved (the operator may
    /// have customized it); only the rwv comment prefix is removed.
    ///
    /// Currently the only DefaultOnly key is `[workspace].resolver`.
    fn undecorate_default_only_keys(path: &Path) -> anyhow::Result<()> {
        if !path.exists() {
            return Ok(());
        }
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading {} for undecorate", path.display()))?;
        let mut doc = TomlDoc::parse(&text)
            .with_context(|| format!("parsing {} for undecorate", path.display()))?;

        let default_only_keys: Vec<KeyPath> = vec![keypath(["workspace", "resolver"])];

        // Only bother writing if at least one key carries the marker.
        if !doc.has_marker(&default_only_keys) {
            return Ok(());
        }

        doc.remove_marker(&default_only_keys);

        let serialized = doc.serialize()?;
        std::fs::write(path, serialized)
            .with_context(|| format!("writing {} after undecorate", path.display()))?;

        Ok(())
    }

    /// Compute the `[patch.crates-io]` entries rwv should generate, when
    /// `cfg.patch == true`.
    ///
    /// Approach (plan §5a-c, opt-in `[patch]` for publishable crates):
    ///
    /// 1. Build an index of every member: `member_path -> crate_name` by
    ///    reading each `<member>/Cargo.toml`'s `[package].name`.
    /// 2. Scan each member's `[dependencies]` and `[dev-dependencies]` for
    ///    entries that include `path = "<rel>"`.
    /// 3. Resolve `<rel>` against the member's directory. If the resolved
    ///    target equals another member's directory, emit a patch entry
    ///    keyed by that other member's crate name, with `path = "<member>"`
    ///    (weave-root-relative).
    ///
    /// This is "the cheapest approach that works for the rvtty case": we
    /// only scan the member manifests, not all repo Cargo.tomls, and we
    /// don't peek at `rwv.lock`'s topology. Cross-repo path deps not
    /// pointing at a known member are ignored (they're either intra-repo
    /// internal-only deps, or operator-managed vendor deps — neither needs
    /// a `[patch]` entry).
    ///
    /// Output is sorted by crate name (stable across runs).
    fn compute_patches(
        ctx: &IntegrationContext,
        members: &[String],
    ) -> anyhow::Result<Vec<(String, String)>> {
        // Index members by their canonicalized absolute on-disk path so we can
        // match the resolved target of a `path = "..."` dep against them. The
        // value side stores both the weave-root-relative member path (for the
        // emitted `path = "<rel>"`) and the crate name (the patch table key).
        let mut by_abs: BTreeMap<std::path::PathBuf, (String, String)> = BTreeMap::new();
        for member in members {
            let member_dir = ctx.workspace_root.join(member);
            let cargo_toml = member_dir.join("Cargo.toml");
            if !cargo_toml.exists() {
                continue;
            }
            let text = std::fs::read_to_string(&cargo_toml)
                .with_context(|| format!("reading {}", cargo_toml.display()))?;
            let doc: toml_edit::DocumentMut = text
                .parse()
                .with_context(|| format!("parsing {}", cargo_toml.display()))?;
            let Some(name) = doc
                .get("package")
                .and_then(|i| i.as_table())
                .and_then(|t| t.get("name"))
                .and_then(|i| i.as_str())
            else {
                continue;
            };
            // Best-effort canonicalize; fall back to the joined path so tests
            // that don't `canonicalize()` test dirs still work.
            let abs = std::fs::canonicalize(&member_dir).unwrap_or(member_dir.clone());
            by_abs.insert(abs, (member.clone(), name.to_string()));
        }

        let mut patches: BTreeMap<String, String> = BTreeMap::new();
        for member in members {
            let member_dir = ctx.workspace_root.join(member);
            let cargo_toml = member_dir.join("Cargo.toml");
            if !cargo_toml.exists() {
                continue;
            }
            let text = std::fs::read_to_string(&cargo_toml)
                .with_context(|| format!("reading {}", cargo_toml.display()))?;
            let doc: toml_edit::DocumentMut = text
                .parse()
                .with_context(|| format!("parsing {}", cargo_toml.display()))?;

            for deps_key in ["dependencies", "dev-dependencies"] {
                let Some(deps) = doc.get(deps_key).and_then(|i| i.as_table()) else {
                    continue;
                };
                for (_dep_name, dep_item) in deps.iter() {
                    // Path deps come in two forms:
                    //   foo = { path = "../foo" }       (inline table)
                    //   [dependencies.foo] path = "..." (sub-table)
                    let path_str = if let Some(inline) = dep_item.as_inline_table() {
                        inline.get("path").and_then(|v| v.as_str())
                    } else if let Some(table) = dep_item.as_table() {
                        table.get("path").and_then(|i| i.as_str())
                    } else {
                        None
                    };
                    let Some(rel) = path_str else { continue };

                    let target = member_dir.join(rel);
                    let target_abs = std::fs::canonicalize(&target).unwrap_or(target.clone());

                    let Some((target_member, target_crate)) = by_abs.get(&target_abs) else {
                        continue;
                    };
                    // Don't emit a patch entry for self (intra-member dep —
                    // not a workspace-cross dep).
                    if target_member == member {
                        continue;
                    }
                    patches.insert(target_crate.clone(), target_member.clone());
                }
            }
        }

        Ok(patches.into_iter().collect())
    }

    /// Merge rwv-generated `[patch.crates-io].<crate>` entries into `path`
    /// (the weave-root `Cargo.toml`). Co-requisite of `strip_marked_patch_entries`.
    ///
    /// Each entry is written as an inline table
    /// `<crate> = { path = "<rel>" }` with the `# managed by rwv` decor on the
    /// leaf key — that decor is the per-entry marker the strip pass keys off
    /// to discriminate rwv-authored entries from user-authored ones.
    ///
    /// Verify-and-warn semantics (matching the merge model): if a key is
    /// already present on disk and is NOT carrying the rwv marker, the user
    /// holds the pen — rwv leaves that entry alone.
    fn merge_patch_entries(path: &Path, patches: &[(String, String)]) -> anyhow::Result<()> {
        use crate::integrations::merge::TOML_MARKER_TEXT;

        let text = if path.exists() {
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?
        } else {
            String::new()
        };
        let mut doc: toml_edit::DocumentMut = text
            .parse()
            .with_context(|| format!("parsing {}", path.display()))?;

        // Get-or-create `[patch.crates-io]`.
        let patch = doc.as_table_mut().entry("patch").or_insert_with(|| {
            let mut t = toml_edit::Table::new();
            t.set_implicit(true);
            toml_edit::Item::Table(t)
        });
        let patch_table = match patch {
            toml_edit::Item::Table(t) => t,
            _ => anyhow::bail!("`patch` is present but is not a table"),
        };
        let crates_io = patch_table
            .entry("crates-io")
            .or_insert_with(|| toml_edit::Item::Table(toml_edit::Table::new()));
        let crates_io_table = match crates_io {
            toml_edit::Item::Table(t) => t,
            _ => anyhow::bail!("`patch.crates-io` is present but is not a table"),
        };

        for (crate_name, target_relpath) in patches {
            // Verify-and-warn: if the user already authored this entry (no
            // rwv marker on the leaf), do not overwrite.
            let user_holds_pen = crates_io_table
                .key(crate_name.as_str())
                .map(|k| {
                    let prefix = k
                        .leaf_decor()
                        .prefix()
                        .and_then(|r| r.as_str())
                        .unwrap_or("");
                    !prefix.contains(TOML_MARKER_TEXT)
                })
                .unwrap_or(false)
                && crates_io_table.contains_key(crate_name.as_str());
            if user_holds_pen {
                continue;
            }

            // Compose `{ path = "<rel>" }` inline table.
            let mut inline = toml_edit::InlineTable::new();
            inline.insert(
                "path",
                toml_edit::Value::String(toml_edit::Formatted::new(target_relpath.clone())),
            );
            crates_io_table.insert(
                crate_name.as_str(),
                toml_edit::Item::Value(toml_edit::Value::InlineTable(inline)),
            );

            // Attach the `# managed by rwv` marker on the leaf key,
            // idempotently and preserving any existing user decor lines.
            if let Some(mut key_mut) = crates_io_table.key_mut(crate_name.as_str()) {
                let decor = key_mut.leaf_decor_mut();
                let existing = decor.prefix().and_then(|r| r.as_str()).unwrap_or("");
                if !existing.contains(TOML_MARKER_TEXT) {
                    let new = if existing.is_empty() {
                        "# managed by rwv\n".to_string()
                    } else if existing.ends_with('\n') {
                        format!("{existing}# managed by rwv\n")
                    } else {
                        format!("{existing}\n# managed by rwv\n")
                    };
                    decor.set_prefix(new);
                }
            }
        }

        std::fs::write(path, doc.to_string())
            .with_context(|| format!("writing {}", path.display()))?;
        Ok(())
    }

    /// Strip every rwv-marker-decorated entry under `[patch.crates-io]`,
    /// then prune empty `[patch.crates-io]` and `[patch]` tables.
    ///
    /// Co-requisite of the activate-time `[patch.crates-io]` generation: the
    /// generic `strip_deactivate` only handles a static set of owned keys;
    /// patch entries are dynamic (one per cross-repo path dep), so they're
    /// enumerated here. The marker decor on each key is the discriminator —
    /// user-authored `[patch.crates-io].some-crate` entries (decorated by the
    /// user, not by rwv) survive.
    fn strip_marked_patch_entries(path: &Path) -> anyhow::Result<()> {
        use crate::integrations::merge::TOML_MARKER_TEXT;

        if !path.exists() {
            return Ok(());
        }
        let text =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        let mut doc: toml_edit::DocumentMut = text
            .parse()
            .with_context(|| format!("parsing {}", path.display()))?;

        let mut changed = false;
        // Collect entries to remove under [patch.crates-io] whose key decor
        // carries the rwv marker. (We avoid mutating while iterating.)
        let to_remove: Vec<String> = doc
            .get("patch")
            .and_then(|i| i.as_table())
            .and_then(|t| t.get("crates-io"))
            .and_then(|i| i.as_table())
            .map(|t| {
                t.iter()
                    .filter_map(|(name, _)| {
                        let key = t.key(name)?;
                        let prefix = key.leaf_decor().prefix().and_then(|r| r.as_str())?;
                        if prefix.contains(TOML_MARKER_TEXT) {
                            Some(name.to_string())
                        } else {
                            None
                        }
                    })
                    .collect()
            })
            .unwrap_or_default();

        if !to_remove.is_empty() {
            if let Some(crates_io) = doc
                .get_mut("patch")
                .and_then(|i| i.as_table_mut())
                .and_then(|t| t.get_mut("crates-io"))
                .and_then(|i| i.as_table_mut())
            {
                for name in &to_remove {
                    crates_io.remove(name);
                }
                changed = true;
            }
        }

        // Prune `[patch.crates-io]` if it's now empty.
        let prune_crates_io = doc
            .get("patch")
            .and_then(|i| i.as_table())
            .and_then(|t| t.get("crates-io"))
            .and_then(|i| i.as_table())
            .is_some_and(|t| t.is_empty());
        if prune_crates_io {
            if let Some(patch) = doc.get_mut("patch").and_then(|i| i.as_table_mut()) {
                patch.remove("crates-io");
                changed = true;
            }
        }
        // Prune `[patch]` if it's now empty.
        let prune_patch = doc
            .get("patch")
            .and_then(|i| i.as_table())
            .is_some_and(|t| t.is_empty());
        if prune_patch {
            doc.as_table_mut().remove("patch");
            changed = true;
        }

        if changed {
            std::fs::write(path, doc.to_string())
                .with_context(|| format!("writing {}", path.display()))?;
        }
        Ok(())
    }
}

/// Resolve a `MemberSpec` to its effective sorted sub-path list.
///
/// `include` minus `exclude`. An empty `include` yields the empty list (no
/// members from that repo — see `MemberSpec` docs for the rationale).
/// Exclude entries that don't match any include are silently ignored.
fn resolve_member_spec(spec: &MemberSpec) -> Vec<String> {
    let exclude: BTreeSet<&str> = spec.exclude.iter().map(String::as_str).collect();
    let mut out: Vec<String> = spec
        .include
        .iter()
        .filter(|s| !exclude.contains(s.as_str()))
        .cloned()
        .collect();
    out.sort();
    out.dedup();
    out
}

/// Returns true if `content` declares a `[workspace]` section (including
/// virtual workspaces, with or without a `[package]` section, and the
/// `[workspace.<key>]` sub-table form).
///
/// Scans line-by-line for a TOML table header at line start. TOML requires
/// headers to be the first non-whitespace token on a line, so this stays
/// correct even when the file embeds the literal text `[workspace]` inside
/// a string value or a comment.
fn declares_workspace(content: &str) -> bool {
    for raw in content.lines() {
        let line = raw.trim_start();
        if line.starts_with('#') {
            continue;
        }
        // Accept both `[workspace]` and `[workspace.foo]` table headers.
        // Require a delimiter (`]` or `.`) right after `workspace` so we
        // don't match a hypothetical `[workspaceish]`.
        let after_bracket = match line.strip_prefix('[') {
            Some(rest) => rest,
            None => continue,
        };
        let after_keyword = match after_bracket.strip_prefix("workspace") {
            Some(rest) => rest,
            None => continue,
        };
        if after_keyword.starts_with(']') || after_keyword.starts_with('.') {
            return true;
        }
    }
    false
}

/// Build the actionable error message for one or more nested-workspace
/// conflicts. Pluralized so the wording reads naturally either way.
fn nested_workspace_error(conflicts: &[String]) -> String {
    let mut msg = String::new();
    if conflicts.len() == 1 {
        msg.push_str(&format!(
            "repo `{}` declares its own [workspace]; cannot be a member of \
             the cargo workspace.\n",
            conflicts[0]
        ));
    } else {
        msg.push_str(
            "the following repos declare their own [workspace] and cannot \
             be members of the cargo workspace:\n",
        );
        for repo in conflicts {
            msg.push_str(&format!("  - {}\n", repo));
        }
    }
    msg.push_str("\nresolve by one of:\n");
    msg.push_str("  - remove the nested [workspace] from the repo's Cargo.toml\n");
    msg.push_str("  - disable the cargo-workspace integration entirely in rwv.yaml\n");
    msg.push_str(
        "  - opt this repo out (per-repo) by adding its path to\n    \
         integrations.cargo-workspace.exclude in rwv.yaml\n",
    );
    msg.push_str(
        "  - for repos with sub-package layouts (no root [workspace] but\n    \
         multiple sub-crates), use integrations.cargo-workspace.members.<repo>\n    \
         with an `include:` list to contribute the sub-paths instead\n",
    );
    msg
}

// ===========================================================================
// Version-skew observatory + same-key patch shadowing scanner (fo-t9x0l1.1)
// ===========================================================================
//
// Read-only scans that feed `rwv doctor` (both the text and `--json` channels)
// without going through the Integration trait — Integration::check returns
// `Issue`s which do not surface in `--json`, but the design (Finding 3 in
// grok-build-export-findings.md) requires structured records for agent/script
// consumers.
//
// Both scans are **warnings** — they never fail doctor's exit status by
// default. They are informational for the operator (version skew), or a
// precondition check for the future derived-patches bead (patch shadowing).

/// One member's requirement for one crate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CargoSkewOccurrence {
    /// Weave-relative member path (e.g. `github/cwalv/foo`, or
    /// `<repo>/<sub>` for members-subpath repos).
    pub member: String,
    /// Requirement string as declared by the member, post
    /// `workspace = true` indirection (so what cargo would actually
    /// resolve against). For inline-table deps the version field is
    /// used; for plain string deps the string itself.
    pub requirement: String,
}

/// A single same-key patch-shadowing finding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PatchShadowingRecord {
    /// The weave-level file that declares the (would-be) inert patch key.
    /// Today this is the weave-root `Cargo.toml`; when Finding 2's
    /// `.cargo/config.toml` surface lands, this may also point there.
    pub weave_config: std::path::PathBuf,
    /// The member-level `.cargo/config.toml` that shadows the weave key
    /// (per cargo's closest-config-wins per key).
    pub member_config: std::path::PathBuf,
    /// The registry sub-table (`crates-io`, or a git URL string).
    pub registry: String,
    /// The specific crate name whose key collides.
    pub crate_name: String,
}

impl CargoWorkspace {
    /// Aggregate every workspace-member's external (registry) dependencies
    /// and report **version skew**: same crate name required at differing
    /// version-req strings across members.
    ///
    /// Resolves `dep.workspace = true` through the member's own
    /// `[workspace.dependencies]` before recording the effective
    /// requirement. Members that ARE workspaces (grok-build shape) are
    /// scanned by reading their own `[workspace.dependencies]`; the scan
    /// path is decoupled from the activation-time nested-workspace
    /// hard-error (which still applies).
    ///
    /// Version comparison is at the raw-string level for v1 — an exact
    /// difference is skew, ambiguous cases (`"1"` vs `"1.0"`, caret
    /// implicit vs explicit) surface as skew and the operator decides.
    /// A semver-smarter comparison is a defensible future refinement but
    /// out of scope here — the observatory is report-not-mandate, so
    /// noisy is safer than silent.
    ///
    /// Returns records sorted by crate name for stable output.
    pub fn scan_version_skew(
        workspace_root: &Path,
        members: &[String],
    ) -> Vec<(String, Vec<CargoSkewOccurrence>)> {
        // Per member, load its Cargo.toml and any workspace-dep table
        // reachable from the member (either its own `[workspace.dependencies]`
        // when the member is a workspace root, or the containing repo's when
        // the member is a `<repo>/<sub>` sub-path).
        let mut per_crate: BTreeMap<String, Vec<CargoSkewOccurrence>> = BTreeMap::new();

        for member in members {
            let member_dir = workspace_root.join(member);
            let cargo_toml = member_dir.join("Cargo.toml");
            let Ok(text) = std::fs::read_to_string(&cargo_toml) else {
                continue;
            };
            let Ok(doc) = text.parse::<toml_edit::DocumentMut>() else {
                continue;
            };

            // Locate the workspace-deps table this member's `workspace = true`
            // inheritances would resolve against. Two cases:
            //
            // (a) `member/Cargo.toml` has its own `[workspace.dependencies]`
            //     (the member is itself a workspace root — grok-build shape).
            // (b) `member` is a sub-path (`<repo>/<sub>`), so walk up to the
            //     repo root's `Cargo.toml` and read its
            //     `[workspace.dependencies]`.
            //
            // Failing both, `workspace = true` deps in this member are
            // uninterpretable and get skipped.
            let workspace_deps_doc: Option<toml_edit::DocumentMut> =
                if extract_workspace_deps_table(&doc).is_some() {
                    Some(doc.clone())
                } else {
                    find_ancestor_workspace_deps(workspace_root, member)
                };

            for deps_key in ["dependencies", "dev-dependencies", "build-dependencies"] {
                let Some(deps) = doc.get(deps_key).and_then(|i| i.as_table()) else {
                    continue;
                };
                for (dep_name, dep_item) in deps.iter() {
                    let effective = resolve_effective_requirement(
                        dep_item,
                        dep_name,
                        workspace_deps_doc.as_ref(),
                    );
                    if let Some(req) = effective {
                        per_crate.entry(dep_name.to_string()).or_default().push(
                            CargoSkewOccurrence {
                                member: member.clone(),
                                requirement: req,
                            },
                        );
                    }
                }
            }
        }

        // Emit only crates that have >=2 distinct requirement strings.
        let mut out: Vec<(String, Vec<CargoSkewOccurrence>)> = Vec::new();
        for (name, occs) in per_crate {
            let distinct: BTreeSet<&str> = occs.iter().map(|o| o.requirement.as_str()).collect();
            if distinct.len() > 1 {
                let mut occs = occs;
                // Sort by (member, requirement) for stable output.
                occs.sort_by(|a, b| {
                    a.member
                        .cmp(&b.member)
                        .then_with(|| a.requirement.cmp(&b.requirement))
                });
                out.push((name, occs));
            }
        }
        out
    }

    /// Detect `.cargo/config.toml` files in the member-directory discovery
    /// chain that carry `[patch.*].<crate>` keys colliding with the
    /// weave-level patch table.
    ///
    /// Cargo's config discovery merges `.cargo/config.toml` files by
    /// **closest-wins per key**: a member's own `.cargo/config.toml` with
    /// `[patch.crates-io].foo = ...` **wholly replaces** the weave-level
    /// entry for `foo`, silently, with no warning from cargo.
    ///
    /// Weave-level patch keys are collected from two sources:
    ///
    /// 1. `<workspace_root>/Cargo.toml`'s `[patch.<reg>]` sub-tables (the
    ///    surface today — see `compute_patches`).
    /// 2. `<workspace_root>/.cargo/config.toml`'s `[patch.<reg>]` sub-tables
    ///    (the surface Finding 2 will add; already-supported today).
    ///
    /// Member-level configs are discovered by walking upward from each
    /// member directory to `workspace_root` (exclusive), reading any
    /// `.cargo/config.toml` found. Each collision produces one record —
    /// callers can group as they see fit.
    ///
    /// Runs standalone (does not require `cfg.patch == true`) — it is the
    /// mandatory precheck for the future derived-patches bead
    /// (fo-t9x0l1.2), which relies on cargo actually applying the patches
    /// generated.
    pub fn scan_patch_shadowing(
        workspace_root: &Path,
        members: &[String],
    ) -> Vec<PatchShadowingRecord> {
        // ---- weave-level patch keys ----
        // {registry -> {crate_name -> source_file}} so each finding names the
        // exact file the weave key came from.
        let mut weave_keys: BTreeMap<String, BTreeMap<String, std::path::PathBuf>> =
            BTreeMap::new();
        collect_patch_keys(&workspace_root.join("Cargo.toml"), &mut weave_keys);
        collect_patch_keys(
            &workspace_root.join(".cargo").join("config.toml"),
            &mut weave_keys,
        );

        if weave_keys.is_empty() {
            return Vec::new();
        }

        // ---- member-level `.cargo/config.toml`s in each member's
        // discovery chain (walk from member upward, exclusive of
        // workspace_root; the weave-level file is treated as the ceiling
        // and is not itself a "member" config for shadowing purposes).
        let mut records: Vec<PatchShadowingRecord> = Vec::new();
        let mut seen: BTreeSet<(std::path::PathBuf, String, String)> = BTreeSet::new();

        // Canonicalize the ceiling once for identity comparison.
        let ceiling =
            std::fs::canonicalize(workspace_root).unwrap_or_else(|_| workspace_root.to_path_buf());

        for member in members {
            let member_dir = workspace_root.join(member);
            for config_path in walk_cargo_configs(&member_dir, &ceiling) {
                let mut member_keys: BTreeMap<String, BTreeMap<String, std::path::PathBuf>> =
                    BTreeMap::new();
                collect_patch_keys(&config_path, &mut member_keys);
                for (registry, crates) in &member_keys {
                    let Some(weave_crates) = weave_keys.get(registry) else {
                        continue;
                    };
                    for crate_name in crates.keys() {
                        let Some(weave_source) = weave_crates.get(crate_name) else {
                            continue;
                        };
                        let key = (config_path.clone(), registry.clone(), crate_name.clone());
                        if !seen.insert(key) {
                            continue;
                        }
                        records.push(PatchShadowingRecord {
                            weave_config: weave_source.clone(),
                            member_config: config_path.clone(),
                            registry: registry.clone(),
                            crate_name: crate_name.clone(),
                        });
                    }
                }
            }
        }

        // Stable output.
        records.sort_by(|a, b| {
            a.member_config
                .cmp(&b.member_config)
                .then_with(|| a.registry.cmp(&b.registry))
                .then_with(|| a.crate_name.cmp(&b.crate_name))
        });
        records
    }
}

/// Read `[patch.<registry>].<crate>` keys from `path` into `into`.
///
/// Silent no-op if the file doesn't exist or doesn't parse. Both are
/// acceptable in scan context — we surface findings, not parse errors.
fn collect_patch_keys(
    path: &Path,
    into: &mut BTreeMap<String, BTreeMap<String, std::path::PathBuf>>,
) {
    let Ok(text) = std::fs::read_to_string(path) else {
        return;
    };
    let Ok(doc) = text.parse::<toml_edit::DocumentMut>() else {
        return;
    };
    let Some(patch) = doc.get("patch").and_then(|i| i.as_table()) else {
        return;
    };
    for (registry, sub) in patch.iter() {
        let Some(sub) = sub.as_table() else { continue };
        for (crate_name, _) in sub.iter() {
            into.entry(registry.to_string())
                .or_default()
                .insert(crate_name.to_string(), path.to_path_buf());
        }
    }
}

/// Walk from `start` upward toward (but not including) `ceiling`, yielding
/// every `.cargo/config.toml` found on the way. Order is closest-first
/// (member's own config first, then its parent's, etc.).
///
/// `ceiling` is compared by canonical path; if `start` is not under
/// `ceiling` (e.g. a symlinked or foreign path), the walk still terminates
/// at filesystem root.
fn walk_cargo_configs(start: &Path, ceiling: &Path) -> Vec<std::path::PathBuf> {
    let mut out = Vec::new();
    let start_canonical = std::fs::canonicalize(start).unwrap_or_else(|_| start.to_path_buf());
    let mut cur: Option<&Path> = Some(&start_canonical);
    while let Some(dir) = cur {
        if dir == ceiling {
            break;
        }
        let cfg = dir.join(".cargo").join("config.toml");
        if cfg.is_file() {
            out.push(cfg);
        }
        cur = dir.parent();
    }
    out
}

/// If `doc` has a `[workspace.dependencies]` table, return an anchor
/// referencing it (the caller can then look up a specific dep name via
/// [`workspace_dep_requirement`]).
fn extract_workspace_deps_table(doc: &toml_edit::DocumentMut) -> Option<&toml_edit::Table> {
    doc.get("workspace")
        .and_then(|i| i.as_table())
        .and_then(|t| t.get("dependencies"))
        .and_then(|i| i.as_table())
}

/// Walk ancestor directories of `<workspace_root>/<member>` looking for a
/// `Cargo.toml` that declares `[workspace.dependencies]`, and return the
/// parsed document. Stops at (and does not include) `workspace_root`. This
/// covers the `<repo>/<sub>` case where a repo's sub-package inherits
/// workspace deps from the repo's own root `Cargo.toml`.
fn find_ancestor_workspace_deps(
    workspace_root: &Path,
    member: &str,
) -> Option<toml_edit::DocumentMut> {
    let member_dir = workspace_root.join(member);
    let mut cur = member_dir.parent();
    while let Some(dir) = cur {
        // Terminate at workspace_root (exclusive) — the weave-root
        // `Cargo.toml` is rwv's aggregating root, its
        // `[workspace.dependencies]` is user-supplied and orthogonal to a
        // member's inheritance choice.
        if dir == workspace_root {
            break;
        }
        let candidate = dir.join("Cargo.toml");
        if candidate.is_file() {
            if let Ok(text) = std::fs::read_to_string(&candidate) {
                if let Ok(doc) = text.parse::<toml_edit::DocumentMut>() {
                    if extract_workspace_deps_table(&doc).is_some() {
                        return Some(doc);
                    }
                }
            }
        }
        cur = dir.parent();
    }
    None
}

/// Compute the effective version-requirement string for one dep entry,
/// resolving `workspace = true` through `workspace_deps_doc`'s
/// `[workspace.dependencies]` table.
///
/// Returns `None` for entries that are not registry deps (path-only, git-
/// only, or workspace-inherit with no matching workspace-deps table).
fn resolve_effective_requirement(
    dep_item: &toml_edit::Item,
    dep_name: &str,
    workspace_deps_doc: Option<&toml_edit::DocumentMut>,
) -> Option<String> {
    // Case 1: plain string version (`foo = "1.2"`).
    if let Some(s) = dep_item.as_str() {
        return Some(s.to_string());
    }

    // Case 2: inline table or sub-table. Both expose a `get(...)` API via
    // conversion.
    let (workspace_inherit, version_field, has_path, has_git) =
        if let Some(inline) = dep_item.as_inline_table() {
            (
                inline.get("workspace").and_then(|v| v.as_bool()) == Some(true),
                inline
                    .get("version")
                    .and_then(|v| v.as_str())
                    .map(str::to_string),
                inline.contains_key("path"),
                inline.contains_key("git"),
            )
        } else {
            let table = dep_item.as_table()?;
            (
                table.get("workspace").and_then(|i| i.as_bool()) == Some(true),
                table
                    .get("version")
                    .and_then(|i| i.as_str())
                    .map(str::to_string),
                table.contains_key("path"),
                table.contains_key("git"),
            )
        };

    if workspace_inherit {
        let doc = workspace_deps_doc?;
        return workspace_dep_requirement(doc, dep_name);
    }
    if has_path || has_git {
        // Not a registry requirement. Skew comparison would be misleading:
        // two members can share a name at different local sources
        // legitimately (canonical-path patch, monorepo sibling).
        return None;
    }
    version_field
}

/// Look up the effective requirement for `dep_name` in `doc`'s
/// `[workspace.dependencies]` table.
fn workspace_dep_requirement(doc: &toml_edit::DocumentMut, dep_name: &str) -> Option<String> {
    let table = extract_workspace_deps_table(doc)?;
    let item = table.get(dep_name)?;
    // Reuse the leaf logic, but disable `workspace = true` recursion — a
    // workspace-deps table entry that itself says `workspace = true` is
    // ill-formed cargo; ignore rather than infinite-loop.
    if let Some(s) = item.as_str() {
        return Some(s.to_string());
    }
    if let Some(inline) = item.as_inline_table() {
        if inline.contains_key("path") || inline.contains_key("git") {
            return None;
        }
        return inline
            .get("version")
            .and_then(|v| v.as_str())
            .map(str::to_string);
    }
    if let Some(t) = item.as_table() {
        if t.contains_key("path") || t.contains_key("git") {
            return None;
        }
        return t
            .get("version")
            .and_then(|i| i.as_str())
            .map(str::to_string);
    }
    None
}

// ===========================================================================
// Unit tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_simple_workspace_header() {
        let s = "[workspace]\nmembers = []\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn detects_virtual_workspace_without_package() {
        // Virtual workspace: only [workspace], no [package] section.
        let s = "[workspace]\nmembers = [\"crate-a\"]\nresolver = \"2\"\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn detects_workspace_subtable_header() {
        // Some Cargo.toml files start with `[workspace.package]` etc.
        let s = "[package]\nname = \"foo\"\n[workspace.package]\nversion = \"1\"\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn ignores_workspace_inside_comment() {
        let s = "# [workspace]\n[package]\nname = \"foo\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn ignores_workspace_inside_string_value() {
        // The literal text `[workspace]` appearing in a value (not at line
        // start as a header) should not trip detection.
        let s = "[package]\nname = \"foo\"\ndescription = \"see [workspace] docs\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn ignores_workspaceish_lookalike() {
        let s = "[workspaceish]\nx = 1\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn plain_package_file_is_not_a_workspace() {
        let s = "[package]\nname = \"foo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn member_spec_resolve_filters_excludes() {
        let spec = MemberSpec {
            include: vec!["daemon".into(), "client".into(), "common".into()],
            exclude: vec!["common".into()],
        };
        assert_eq!(resolve_member_spec(&spec), vec!["client", "daemon"]);
    }

    #[test]
    fn member_spec_resolve_empty_include_is_empty() {
        let spec = MemberSpec::default();
        assert!(resolve_member_spec(&spec).is_empty());
    }
}
