use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use std::path::Path;

const GENERATED_HEADER: &str = "# Generated by rwv \u{2014} do not edit";

pub struct CargoWorkspace;

impl Integration for CargoWorkspace {
    fn name(&self) -> &str {
        "cargo-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(());
        }

        let members: Vec<String> = paths.iter().map(|p| format!("\"{}\"", p)).collect();
        let members_str = members.join(", ");

        let content = format!(
            "{}\n\n[workspace]\nmembers = [{}]\nresolver = \"2\"\n",
            GENERATED_HEADER, members_str
        );

        std::fs::write(ctx.output_dir.join("Cargo.toml"), content)?;
        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        let path = root.join("Cargo.toml");
        if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            if content.starts_with(GENERATED_HEADER) {
                std::fs::remove_file(path)?;
            }
        }
        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("cargo").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "cargo is not on PATH".to_string(),
            });
        }
        Ok(issues)
    }

    fn lock(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(());
        }

        let status = std::process::Command::new("cargo")
            .arg("generate-lockfile")
            .current_dir(ctx.output_dir)
            .status()
            .map_err(|e| anyhow::anyhow!("failed to run cargo: {e}"))?;

        if !status.success() {
            anyhow::bail!("cargo generate-lockfile failed (exit {})", status);
        }

        Ok(())
    }

    fn generated_files(&self, _ctx: &IntegrationContext) -> Vec<String> {
        vec!["Cargo.toml".to_string(), "Cargo.lock".to_string()]
    }
}
