//! Cargo-workspace integration.
//!
//! Generates the `[workspace]` region of a hybrid root `Cargo.toml` declaring
//! every Rust repo in the active project as a workspace member, then lets
//! `cargo generate-lockfile` produce a shared `Cargo.lock`.
//!
//! ## Hybrid file ownership (fo-cnpjy.7 — the cargo merge port)
//!
//! `Cargo.toml` is a **hybrid** file: rwv owns a declared key set, the user
//! owns everything else. Authoring goes through the shared `TomlDoc`
//! helper in [`crate::integrations::merge`], which preserves comments, key
//! order, profile blocks, lints, `[patch]` tables, and per-key formatting
//! byte-for-semantics across `toml_edit::DocumentMut` round-trips.
//!
//! **Owned keys** (the only bytes rwv writes):
//! - `[workspace].members`
//! - `[workspace].resolver` (always `"2"`)
//! - `[workspace.package]` (only when `workspace-package: true`)
//!
//! Everything else — `[profile.*]`, `[workspace.dependencies]`,
//! `[workspace.lints.*]`, `[workspace.metadata.*]`, `[patch.*]`, stray
//! top-level `[package]`, comments — is user policy and is **never**
//! written or stripped.
//!
//! **Marker:** the per-key TOML decoration `# managed by rwv` (a comment
//! line attached as the prefix of each owned key). Position-independent;
//! survives reordering; never injects a top-level header into a user file.
//! See [`crate::integrations::merge::TomlDoc`] for the format details.
//!
//! **Activate** = read-or-empty → merge-set the owned keys (via
//! `merge_activate`) → write. If the file is missing it is created with
//! only the managed region. The legacy `# Generated by rwv` first-line
//! header is gone.
//!
//! **Deactivate** = `strip_deactivate` — gate on the marker, strip the
//! owned keys, prune empty `[workspace]`, delete the file iff it would
//! otherwise be empty. Hand-written `Cargo.toml` files (no marker) are
//! left strictly alone — the strip is a no-op.
//!
//! ## Design decisions — locked in fo-cnpjy.6 (plan §7.2)
//!
//! **(a) Members sub-path config.** `CargoWorkspaceConfig::members` maps a
//! repo path string to a `MemberSpec{include, exclude}`. When a repo appears
//! in this map, its root is NOT treated as a member; instead,
//! `<repo>/<inc_path>` is emitted for each `include` entry minus `exclude`.
//! Repos absent from the map keep the current root-as-member auto-behavior.
//! This is what lets rvtty (no root `Cargo.toml`, sub-packages `daemon/`,
//! `client/`, `common/`) contribute its packages to the weave workspace
//! instead of being excluded. See `cargo-workspace-vs-repo.md` §179–212.
//!
//! **(b) Merge-preserve scope.** Owns ONLY `[workspace].members`,
//! `[workspace].resolver`, and (behind `workspace_package: true`)
//! `[workspace.package]`. All other tables are user policy and survive
//! every activate/deactivate cycle unmodified.
//!
//! **(c) Cross-repo path deps / `[patch]` opt-in.**
//! `CargoWorkspaceConfig::patch` is **out of scope for this bead** — fo-cnpjy.8
//! adds the `[patch]` generation behind the flag. The flag exists in the
//! config type already (no-op here).
//!
//! **(d) Nested-workspace hard error.** Refinement: a repo listed under
//! `members.<repo>` is exempt from the `declares_workspace()` check on its
//! **root** (its sub-packages, not its root, are the declared members).
//! However, if such a repo's root *does* declare `[workspace]`, that is still
//! a hard error — the ancestor-walk would bind sub-packages to it.
//!
//! ## Per-repo opt-out
//!
//! Repos can be opted out of the cargo workspace via the integration config:
//!
//! ```yaml
//! integrations:
//!   cargo-workspace:
//!     exclude:
//!       - github/cwalv/mcp_agent_mail_rust
//! ```
//!
//! Opted-out repos are dropped from `members`. (The pre-port behavior of
//! emitting `# excluded: <path> (opted out)` comments above the `[workspace]`
//! block is gone — the TomlDoc helper authors keys, not free-floating
//! comments. Operators see exclusions in `rwv.yaml`; surfacing them via
//! `check()` is a separate concern.)
//!
//! Opt-out keys that don't match any active Rust repo are silently ignored
//! (so leaving a stale entry behind after removing a repo is not an error).

use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use crate::integrations::merge::{
    keypath, merge_activate, strip_deactivate, KeyPath, MergeResult, OwnedValue, TomlDoc,
};
use crate::manifest::{CargoWorkspaceConfig, MemberSpec};
use anyhow::Context;
use std::collections::BTreeSet;
use std::path::Path;

pub struct CargoWorkspace;

impl CargoWorkspace {
    /// Compute the sorted member-path list and the nested-workspace
    /// conflict list for the active Rust repos.
    ///
    /// Behavior:
    /// - A repo in `cfg.exclude` is dropped entirely (no member emitted, no
    ///   workspace check).
    /// - A repo listed under `cfg.members` (a `MemberSpec`) does NOT
    ///   contribute its root as a member; it contributes
    ///   `<repo>/<inc>` for each `inc` in `include` minus `exclude` instead.
    ///   Its root is exempt from the `declares_workspace()` check **unless**
    ///   the root itself actually declares `[workspace]` (still a hard error —
    ///   the ancestor-walk binds sub-packages to it).
    /// - Any other Rust repo contributes its root as a member; if the root
    ///   declares `[workspace]`, it joins the nested-conflict list.
    ///
    /// Returns `(members, nested_conflicts)`. `members` is sorted
    /// lexicographically (the on-disk ordering the toml_edit array honors).
    fn partition(
        ctx: &IntegrationContext,
        cfg: &CargoWorkspaceConfig,
    ) -> anyhow::Result<(Vec<String>, Vec<String>)> {
        let rust_repos = ctx.detect_repos_with_manifest("Cargo.toml");
        let opt_out: BTreeSet<&str> = cfg.exclude.iter().map(String::as_str).collect();

        let mut members: Vec<String> = Vec::new();
        let mut nested_conflicts: Vec<String> = Vec::new();

        for repo in &rust_repos {
            if opt_out.contains(repo.as_str()) {
                continue;
            }
            let cargo_toml = ctx.workspace_root.join(repo).join("Cargo.toml");
            let content = std::fs::read_to_string(&cargo_toml)
                .with_context(|| format!("failed to read {}", cargo_toml.display()))?;
            let root_has_workspace = declares_workspace(&content);

            if let Some(spec) = cfg.members.get(repo) {
                // members.<repo> sub-path mode.
                // Refinement (plan §7.2-d): if the repo root itself declares
                // [workspace] this is STILL a hard error — sub-packages can't
                // dodge an ancestor workspace declaration via member
                // configuration.
                if root_has_workspace {
                    nested_conflicts.push(repo.clone());
                    continue;
                }
                for sub in resolve_member_spec(spec) {
                    members.push(format!("{repo}/{sub}"));
                }
            } else if root_has_workspace {
                nested_conflicts.push(repo.clone());
            } else {
                members.push(repo.clone());
            }
        }

        members.sort();
        members.dedup();
        Ok((members, nested_conflicts))
    }

    /// Build the (key, value) pairs the merge helper will set during
    /// `activate()`. Pure — no I/O.
    fn owned_pairs(members: &[String], cfg: &CargoWorkspaceConfig) -> Vec<(KeyPath, OwnedValue)> {
        let mut owned: Vec<(KeyPath, OwnedValue)> = Vec::with_capacity(3);

        owned.push((
            keypath(["workspace", "members"]),
            OwnedValue::Array(members.to_vec()),
        ));
        owned.push((
            keypath(["workspace", "resolver"]),
            OwnedValue::String("2".to_string()),
        ));

        if cfg.workspace_package {
            // The cargo-workspace-vs-repo.md design surfaces `rwv.yaml`
            // `project.{license, authors, description, repository, ...}` into
            // `[workspace.package]`. The Manifest type does not yet carry a
            // `project` section (cargo-workspace-vs-repo.md §324-376 is the
            // forward-looking design; the manifest extension is a separate
            // bead). Until that lands, the opt-in writes an empty
            // `[workspace.package]` table.
            //
            // The wiring is correct: when the project metadata field lands,
            // populate the BTreeMap below from it; the TomlDoc merge-into-
            // existing-table behavior will set each sub-key while preserving
            // user-added ones.
            owned.push((
                keypath(["workspace", "package"]),
                OwnedValue::Object(std::collections::BTreeMap::new()),
            ));
        }

        owned
    }
}

impl Integration for CargoWorkspace {
    fn name(&self) -> &str {
        "cargo-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(());
        }

        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;
        let (members, nested_conflicts) = Self::partition(ctx, &cfg)?;

        if !nested_conflicts.is_empty() {
            anyhow::bail!("{}", nested_workspace_error(&nested_conflicts));
        }

        // `output_dir = project_dir` (plan §4.1) — the committed `Cargo.toml`
        // lives in the project directory and the weave-root symlink surfaces
        // it. Writing through `output_dir` writes into the committed file.
        let path = ctx.output_dir.join("Cargo.toml");
        let owned = Self::owned_pairs(&members, &cfg);

        let _result: MergeResult = merge_activate::<TomlDoc>(&path, &owned)
            .with_context(|| format!("merge-activate {}", path.display()))?;

        // `MergeResult.deferred` lists keys the user took the pen on (a
        // hand-written `[workspace]` block with no marker). The trigger-model
        // story is that context verbs verify-and-warn rather than author;
        // surfacing deferrals as `Severity::Warning` is a framework concern
        // tracked by C3 (`generated_files()` split + verify split). For now
        // the merge silently defers — consistent with the pre-port behavior
        // of leaving hand-written files alone.

        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        // `root` is the project_dir per the framework's deactivate contract
        // (`integration_runner::run_deactivations`). It is the same path
        // `output_dir` resolved to during activate.
        let path = root.join("Cargo.toml");
        let owned_keys = Self::deactivate_owned_keys();
        strip_deactivate::<TomlDoc>(&path, &owned_keys)
            .with_context(|| format!("strip-deactivate {}", path.display()))?;
        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("cargo").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "cargo is not on PATH".to_string(),
            });
        }

        // Surface nested-workspace conflicts as errors during `rwv doctor`
        // so operators see the same diagnostic without having to run lock.
        let cfg: CargoWorkspaceConfig = ctx.config.settings()?;
        let (_, nested_conflicts) = Self::partition(ctx, &cfg)?;
        if !nested_conflicts.is_empty() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Error,
                message: nested_workspace_error(&nested_conflicts),
            });
        }

        Ok(issues)
    }

    fn activate_hook(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("Cargo.toml");
        if paths.is_empty() {
            return Ok(());
        }

        // Run from workspace_root: that's where activation symlinks are
        // in place so cargo sees the workspace the user sees. output_dir
        // (project_dir) is where the canonical Cargo.toml lives, but the
        // member paths in it are resolved relative to the symlink at
        // workspace_root.
        let status = std::process::Command::new("cargo")
            .arg("generate-lockfile")
            .current_dir(ctx.workspace_root)
            .status()
            .context("failed to run cargo")?;

        if !status.success() {
            anyhow::bail!("cargo generate-lockfile failed (exit {})", status);
        }

        Ok(())
    }

    /// `Cargo.lock` is fully-owned — gitignore-eligible, whole-deletable.
    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        if ctx.detect_repos_with_manifest("Cargo.toml").is_empty() {
            return vec![];
        }
        vec!["Cargo.lock".to_string()]
    }

    /// `Cargo.toml` is **hybrid** (rwv owns the `[workspace]` region; the
    /// user owns `[profile.*]`, `[workspace.lints.*]`, `[workspace.dependencies]`,
    /// `[patch.*]`, comments, etc.). It MUST NOT appear in
    /// `generated_files()` — that would mark it gitignore-eligible and
    /// whole-deletable, the exact data-loss bug the merge port fixes.
    fn managed_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        let mut files = self.generated_files(ctx);
        if !ctx.detect_repos_with_manifest("Cargo.toml").is_empty() {
            files.push("Cargo.toml".to_string());
        }
        files
    }
}

impl CargoWorkspace {
    /// The owned key paths stripped on `deactivate(root)`. Static because
    /// `Integration::deactivate` has no `IntegrationContext` — see
    /// `integration.rs:154`. Plan §3 / §11 res #15:
    ///
    /// - `members` and `resolver` are stripped unconditionally — they are
    ///   the always-owned keys.
    /// - `workspace.package` is also stripped unconditionally. The marker
    ///   gate in `strip_deactivate` is per-key: if the key was never
    ///   authored (the opt-in was off), no decor exists, and the strip is a
    ///   no-op for that key. If it WAS authored, stripping is correct.
    ///   This avoids leaking the activate-time `workspace_package` boolean
    ///   into the deactivate path (which doesn't have the config).
    fn deactivate_owned_keys() -> Vec<KeyPath> {
        vec![
            keypath(["workspace", "members"]),
            keypath(["workspace", "resolver"]),
            keypath(["workspace", "package"]),
        ]
    }
}

/// Resolve a `MemberSpec` to its effective sorted sub-path list.
///
/// `include` minus `exclude`. An empty `include` yields the empty list (no
/// members from that repo — see `MemberSpec` docs for the rationale).
/// Exclude entries that don't match any include are silently ignored.
fn resolve_member_spec(spec: &MemberSpec) -> Vec<String> {
    let exclude: BTreeSet<&str> = spec.exclude.iter().map(String::as_str).collect();
    let mut out: Vec<String> = spec
        .include
        .iter()
        .filter(|s| !exclude.contains(s.as_str()))
        .cloned()
        .collect();
    out.sort();
    out.dedup();
    out
}

/// Returns true if `content` declares a `[workspace]` section (including
/// virtual workspaces, with or without a `[package]` section, and the
/// `[workspace.<key>]` sub-table form).
///
/// Scans line-by-line for a TOML table header at line start. TOML requires
/// headers to be the first non-whitespace token on a line, so this stays
/// correct even when the file embeds the literal text `[workspace]` inside
/// a string value or a comment.
fn declares_workspace(content: &str) -> bool {
    for raw in content.lines() {
        let line = raw.trim_start();
        if line.starts_with('#') {
            continue;
        }
        // Accept both `[workspace]` and `[workspace.foo]` table headers.
        // Require a delimiter (`]` or `.`) right after `workspace` so we
        // don't match a hypothetical `[workspaceish]`.
        let after_bracket = match line.strip_prefix('[') {
            Some(rest) => rest,
            None => continue,
        };
        let after_keyword = match after_bracket.strip_prefix("workspace") {
            Some(rest) => rest,
            None => continue,
        };
        if after_keyword.starts_with(']') || after_keyword.starts_with('.') {
            return true;
        }
    }
    false
}

/// Build the actionable error message for one or more nested-workspace
/// conflicts. Pluralized so the wording reads naturally either way.
fn nested_workspace_error(conflicts: &[String]) -> String {
    let mut msg = String::new();
    if conflicts.len() == 1 {
        msg.push_str(&format!(
            "repo `{}` declares its own [workspace]; cannot be a member of \
             the cargo workspace.\n",
            conflicts[0]
        ));
    } else {
        msg.push_str(
            "the following repos declare their own [workspace] and cannot \
             be members of the cargo workspace:\n",
        );
        for repo in conflicts {
            msg.push_str(&format!("  - {}\n", repo));
        }
    }
    msg.push_str("\nresolve by one of:\n");
    msg.push_str("  - remove the nested [workspace] from the repo's Cargo.toml\n");
    msg.push_str("  - disable the cargo-workspace integration entirely in rwv.yaml\n");
    msg.push_str(
        "  - opt this repo out (per-repo) by adding its path to\n    \
         integrations.cargo-workspace.exclude in rwv.yaml\n",
    );
    msg.push_str(
        "  - for repos with sub-package layouts (no root [workspace] but\n    \
         multiple sub-crates), use integrations.cargo-workspace.members.<repo>\n    \
         with an `include:` list to contribute the sub-paths instead\n",
    );
    msg
}

// ===========================================================================
// Unit tests for the parser helper
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_simple_workspace_header() {
        let s = "[workspace]\nmembers = []\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn detects_virtual_workspace_without_package() {
        // Virtual workspace: only [workspace], no [package] section.
        let s = "[workspace]\nmembers = [\"crate-a\"]\nresolver = \"2\"\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn detects_workspace_subtable_header() {
        // Some Cargo.toml files start with `[workspace.package]` etc.
        let s = "[package]\nname = \"foo\"\n[workspace.package]\nversion = \"1\"\n";
        assert!(declares_workspace(s));
    }

    #[test]
    fn ignores_workspace_inside_comment() {
        let s = "# [workspace]\n[package]\nname = \"foo\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn ignores_workspace_inside_string_value() {
        // The literal text `[workspace]` appearing in a value (not at line
        // start as a header) should not trip detection.
        let s = "[package]\nname = \"foo\"\ndescription = \"see [workspace] docs\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn ignores_workspaceish_lookalike() {
        let s = "[workspaceish]\nx = 1\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn plain_package_file_is_not_a_workspace() {
        let s = "[package]\nname = \"foo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n";
        assert!(!declares_workspace(s));
    }

    #[test]
    fn member_spec_resolve_filters_excludes() {
        let spec = MemberSpec {
            include: vec!["daemon".into(), "client".into(), "common".into()],
            exclude: vec!["common".into()],
        };
        assert_eq!(resolve_member_spec(&spec), vec!["client", "daemon"]);
    }

    #[test]
    fn member_spec_resolve_empty_include_is_empty() {
        let spec = MemberSpec::default();
        assert!(resolve_member_spec(&spec).is_empty());
    }
}
