use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use crate::integrations::merge::{merge_activate, strip_deactivate, KeyPath, OwnedValue, YamlDoc};
use anyhow::Context;
use std::path::Path;

pub struct PnpmWorkspaces;

/// Return the owned [`KeyPath`] for the `packages:` key.
///
/// `packages:` is the only key rwv manages in pnpm-workspace.yaml.
/// `catalog:`, `overrides:`, `peerDependencyRules:`, `hoistPattern:`,
/// and any user comments are strictly user content and are never touched.
fn packages_key() -> KeyPath {
    vec!["packages".to_string()]
}

impl Integration for PnpmWorkspaces {
    fn name(&self) -> &str {
        "pnpm-workspaces"
    }

    fn default_enabled(&self) -> bool {
        false
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("package.json");
        if paths.is_empty() {
            return Ok(());
        }

        let path = ctx.output_dir.join("pnpm-workspace.yaml");

        // Sorted list of member paths — deterministic output.
        let mut members: Vec<String> = paths.into_iter().map(|p| p.to_string()).collect();
        members.sort();

        let owned = vec![(packages_key(), OwnedValue::sorted_array(members))];

        merge_activate::<YamlDoc>(&path, &owned)
            .with_context(|| format!("pnpm-workspaces: activate {}", path.display()))?;

        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        let path = root.join("pnpm-workspace.yaml");

        // Marker gate: strip_deactivate leaves the file alone if the marker
        // is absent (user took the pen). Deletes only if empty after strip.
        let owned_keys = [packages_key()];
        strip_deactivate::<YamlDoc>(&path, &owned_keys)
            .with_context(|| format!("pnpm-workspaces: deactivate {}", path.display()))?;

        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let paths = ctx.detect_repos_with_manifest("package.json");
        if paths.is_empty() {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("pnpm").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "pnpm is not on PATH".to_string(),
                safe_to_fix: true,
            });
        }
        Ok(issues)
    }

    fn activate_hook(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("package.json");
        if paths.is_empty() {
            return Ok(());
        }

        // Full `pnpm install` (not `--lockfile-only`): activation is the
        // moment to bring `node_modules` in sync; the hook fired from
        // `rwv lock` previously and used `--lockfile-only` for that
        // reason. Run from workspace_root for the same reason npm does —
        // that's where the symlinks make member paths resolve correctly.
        let status = std::process::Command::new("pnpm")
            .args(["install"])
            .current_dir(ctx.workspace_root)
            .status()
            .context("failed to run pnpm")?;

        if !status.success() {
            anyhow::bail!("pnpm install failed (exit {})", status);
        }

        Ok(())
    }

    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        if ctx.detect_repos_with_manifest("package.json").is_empty() {
            return vec![];
        }
        // pnpm-lock.yaml is fully-rwv-owned (generated by `pnpm install`).
        vec!["pnpm-lock.yaml".to_string()]
    }

    fn managed_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        if ctx.detect_repos_with_manifest("package.json").is_empty() {
            return vec![];
        }
        // pnpm-workspace.yaml is a hybrid file: rwv owns the `packages:`
        // block; the user owns `catalog:`, `overrides:`, etc. It is
        // symlinked (via managed_files) but never gitignored, and
        // deactivate strips the owned region rather than deleting wholesale.
        vec!["pnpm-workspace.yaml".to_string()]
    }
}
