use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use std::path::Path;

const GENERATED_HEADER: &str = "# Generated by rwv \u{2014} do not edit";

pub struct UvWorkspace;

impl Integration for UvWorkspace {
    fn name(&self) -> &str {
        "uv-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(());
        }

        let mut content = format!("{}\n[tool.uv.workspace]\nmembers = [\n", GENERATED_HEADER);
        for p in &paths {
            content.push_str(&format!("    \"{}\",\n", p));
        }
        content.push_str("]\n");

        std::fs::write(ctx.output_dir.join("pyproject.toml"), content)?;
        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        let path = root.join("pyproject.toml");
        if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            if content.starts_with(GENERATED_HEADER) {
                std::fs::remove_file(path)?;
            }
        }
        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("uv").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "uv is not on PATH".to_string(),
            });
        }
        Ok(issues)
    }

    fn lock(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(());
        }

        let status = std::process::Command::new("uv")
            .arg("lock")
            .current_dir(ctx.output_dir)
            .status()
            .map_err(|e| anyhow::anyhow!("failed to run uv: {e}"))?;

        if !status.success() {
            anyhow::bail!("uv lock failed (exit {})", status);
        }

        Ok(())
    }

    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        if ctx.detect_repos_with_manifest("pyproject.toml").is_empty() {
            return vec![];
        }
        vec!["pyproject.toml".to_string(), "uv.lock".to_string()]
    }
}
