//! uv-workspace integration.
//!
//! Generates the `[tool.uv.workspace]` region of a hybrid root `pyproject.toml`
//! declaring every Python repo in the active project as a workspace member, then
//! lets `uv sync` produce a shared `uv.lock`.
//!
//! ## Hybrid file ownership (fo-cnpjy.9 — the uv merge port)
//!
//! `pyproject.toml` is a **hybrid** file: rwv owns a declared key set, the user
//! owns everything else. Authoring goes through the shared `TomlDoc` helper in
//! [`crate::integrations::merge`], which preserves comments, key order, inline
//! tables, triple-quoted strings, and per-key formatting byte-for-semantics
//! across `toml_edit::DocumentMut` round-trips.
//!
//! **Owned keys** (the only bytes rwv writes):
//! - `[tool.uv.workspace].members` — the member path array.
//! - `[tool.uv.sources].<member-name>` = `{ workspace = true }` — one entry
//!   per detected member (only `workspace=true` entries; user git/url/index/
//!   path sources inside `[tool.uv.sources]` are NOT touched).
//! - `[tool.uv].package` = `false` — **greenfield only** (when the file does
//!   not exist before `activate()`). Required so `uv sync` accepts a
//!   non-package root. Not written on subsequent activations of an
//!   already-existing file; per plan §5b and §7.4.
//!
//! **Never authored:** `[project]`, `[build-system]`, `[tool.ruff]`,
//! `[tool.black]`, `[tool.rooster]`, or any other section — those are user
//! content.
//!
//! **Marker:** the per-key TOML decoration `# managed by rwv` (a comment line
//! attached as the prefix of the `members` key). Position-independent; survives
//! reordering; never injects a top-level header into a user file. See
//! [`crate::integrations::merge::TomlDoc`] for the format details.
//!
//! **Activate** = detect-greenfield → read-or-empty → merge-set the owned keys
//! (via `merge_activate`) → write. If the file is missing it is created with
//! only the managed region (plus `package = false`). The legacy
//! `# Generated by rwv` first-line header is gone.
//!
//! **Deactivate** = gate on marker → strip `members` (via `strip_deactivate`) →
//! strip only `{workspace=true}` source entries (custom adapter) → prune empty
//! `[tool.uv.workspace]`/`[tool.uv.sources]`/`[tool.uv]`/`[tool]` → delete
//! the file iff it would otherwise be empty. Legacy `starts_with(HEADER)` is
//! kept as a one-line fallback on the deactivate path only (to avoid orphaning
//! files written by the prior overwrite writer on the operator's one-off
//! migration; per plan §7.1 and the rwv-alpha-no-backcompat rule).
//!
//! ## Strip-by-predicate decision (the deactivate design choice)
//!
//! The shared `strip_deactivate` helper strips whole key paths. For
//! `[tool.uv.sources]` we own ONLY entries whose value contains
//! `workspace = true` — user git/url/index/path sources must survive. Two
//! options were evaluated:
//!
//! - **(a) Bespoke adapter in uv_workspace.rs**: after `strip_deactivate`
//!   removes `members`, run a separate pass that reads the document, removes
//!   only `{workspace=true}` source entries, and prunes any empty parent tables.
//!   Then, if the whole document is empty, delete the file.
//! - **(b) Extend TomlDoc with a predicate-based stripper**: a new
//!   `remove_owned_where` method accepting a closure, wired into the shared
//!   `ManagedDoc` trait.
//!
//! **Decision: (a) bespoke adapter.** Option (b) would add API surface to
//! `ManagedDoc` for a single integration's edge case. Option (a) keeps the
//! shared helper clean and moves the specialization to the one integration that
//! needs it. The bespoke adapter is ~30 lines in this file; the logic is
//! self-contained and tested by the §6.uv.3 scenario.
//!
//! ## managed/generated split (C3)
//!
//! `pyproject.toml` moves from `generated_files()` to `managed_files()` here.
//! `uv.lock` stays in `generated_files()` — it is fully-owned by rwv and
//! gitignore-eligible.

use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use crate::integrations::merge::{
    keypath, merge_activate, strip_deactivate, KeyPath, MergeResult, OwnedValue, TomlDoc,
};
use anyhow::Context;
use std::path::Path;

/// The legacy header written by the old overwrite writer. Recognised on the
/// deactivate path only (not on activate) so that files written by the prior
/// version are cleaned up on the operator's one-off migration.
const LEGACY_HEADER: &str = "# Generated by rwv \u{2014} do not edit";

pub struct UvWorkspace;

impl UvWorkspace {
    /// The owned key paths passed to `strip_deactivate`. These cover
    /// `members` (and the whole-table pruning of `[tool.uv.workspace]`) and
    /// the greenfield `package = false` key.
    ///
    /// `[tool.uv.sources]` workspace-true entries are handled separately
    /// by the bespoke adapter (`strip_workspace_sources`).
    ///
    /// Including `["tool", "uv", "package"]` here is safe: if the marker is
    /// present (rwv wrote this file), we strip `package = false`; if the user
    /// wrote `package` manually without the marker, the deactivate is a no-op
    /// (no marker → strip_deactivate bails early).
    fn deactivate_owned_keys() -> Vec<KeyPath> {
        vec![
            keypath(["tool", "uv", "workspace", "members"]),
            keypath(["tool", "uv", "package"]),
        ]
    }

    /// Build the **primary** `(key, value)` pairs for `merge_activate`.
    ///
    /// Only the keys that carry the `# managed by rwv` marker:
    /// - `members` = sorted array of member paths.
    /// - `[tool.uv].package` = `false` **only if** `is_greenfield`.
    ///
    /// Source entries (`[tool.uv.sources].*`) are NOT included here —
    /// they are written in a second pass by `set_workspace_sources` so that
    /// only `members` carries the marker decoration (not each source entry).
    /// See `activate()` and the module doc.
    fn primary_owned_pairs(members: &[String], is_greenfield: bool) -> Vec<(KeyPath, OwnedValue)> {
        let mut owned: Vec<(KeyPath, OwnedValue)> = Vec::new();

        // members: the primary key that carries the `# managed by rwv` marker.
        owned.push((
            keypath(["tool", "uv", "workspace", "members"]),
            OwnedValue::Array(members.to_vec()),
        ));

        // greenfield-only: [tool.uv].package = false
        if is_greenfield {
            owned.push((
                keypath(["tool", "uv", "package"]),
                OwnedValue::Bool(false),
            ));
        }

        owned
    }

    /// Set `[tool.uv.sources].<dep_name> = { workspace = true }` for each
    /// member into the file at `path`, using a direct toml_edit pass.
    ///
    /// This is a **separate pass** from `merge_activate` so that source entries
    /// do NOT carry the `# managed by rwv` marker decoration. The marker lives
    /// solely on `members`; per-source markers would cause the "exactly one
    /// marker" idempotency invariant to fail.
    ///
    /// Preserves all user-authored keys in `[tool.uv.sources]` (git/url/index/
    /// path sources).  Only sets the workspace-true entries for each member.
    fn set_workspace_sources(path: &Path, members: &[String]) -> anyhow::Result<()> {
        if members.is_empty() || !path.exists() {
            return Ok(());
        }
        let text =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        let mut doc: toml_edit::DocumentMut = text
            .parse()
            .with_context(|| format!("parsing {} for sources set", path.display()))?;

        for member in members {
            let dep_name = member
                .rsplit('/')
                .next()
                .unwrap_or(member.as_str())
                .to_string();

            // Walk/create [tool][uv][sources], then set <dep_name> = { workspace = true }.
            // Using nested get_mut/insert rather than the private parent_and_leaf helper.
            if !doc.as_table().contains_key("tool") {
                let mut t = toml_edit::Table::new();
                t.set_implicit(true);
                doc.as_table_mut()
                    .insert("tool", toml_edit::Item::Table(t));
            }
            let tool = doc
                .as_table_mut()
                .get_mut("tool")
                .and_then(|i| i.as_table_mut())
                .ok_or_else(|| anyhow::anyhow!("tool is not a table in {}", path.display()))?;

            if !tool.contains_key("uv") {
                let mut t = toml_edit::Table::new();
                t.set_implicit(true);
                tool.insert("uv", toml_edit::Item::Table(t));
            }
            let uv = tool
                .get_mut("uv")
                .and_then(|i| i.as_table_mut())
                .ok_or_else(|| anyhow::anyhow!("[tool.uv] is not a table in {}", path.display()))?;

            if !uv.contains_key("sources") {
                let mut t = toml_edit::Table::new();
                t.set_implicit(true);
                uv.insert("sources", toml_edit::Item::Table(t));
            }
            let sources = uv
                .get_mut("sources")
                .and_then(|i| i.as_table_mut())
                .ok_or_else(|| {
                    anyhow::anyhow!("[tool.uv.sources] is not a table in {}", path.display())
                })?;

            // Only set the entry if it doesn't already exist OR if it already
            // is a `{workspace = true}` entry (idempotent update). Never
            // clobber a user-authored entry (git/url/index/path source).
            let should_set = match sources.get(&dep_name) {
                None => true,
                Some(existing) => is_workspace_true_source(existing),
            };
            if should_set {
                let mut inline = toml_edit::InlineTable::new();
                inline.insert("workspace", toml_edit::Value::from(true));
                sources.insert(
                    &dep_name,
                    toml_edit::Item::Value(toml_edit::Value::InlineTable(inline)),
                );
            }
        }

        let out = doc.to_string();
        std::fs::write(path, out).with_context(|| format!("writing {}", path.display()))?;
        Ok(())
    }

    /// Strip only `{workspace=true}` entries from `[tool.uv.sources]` using a
    /// bespoke adapter (see module doc — design decision (a)).
    ///
    /// Steps:
    /// 1. Read + parse the file (if present).
    /// 2. Iterate `[tool.uv.sources]` entries; remove those whose TOML value
    ///    is an inline table containing `workspace = true`.
    /// 3. Prune empty `[tool.uv.sources]` / `[tool.uv]` / `[tool]` tables.
    /// 4. If the document is empty after pruning → delete the file.
    ///    Else → write the stripped document back.
    ///
    /// Runs **after** `strip_deactivate` has already removed `members` and
    /// pruned `[tool.uv.workspace]`. The marker is gone at this point, so
    /// this function does NOT re-check the marker (the caller gated on it).
    fn strip_workspace_sources(path: &Path) -> anyhow::Result<()> {
        if !path.exists() {
            return Ok(());
        }
        let text =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        let mut doc: toml_edit::DocumentMut = text
            .parse()
            .with_context(|| format!("parsing {} for sources strip", path.display()))?;

        // Collect source-entry keys to remove (workspace = true).
        let keys_to_remove: Vec<String> = {
            let mut to_remove = Vec::new();
            // Walk to [tool.uv.sources] if present (read-only borrow).
            if let Some(tool) = doc.get("tool").and_then(|i| i.as_table()) {
                if let Some(uv) = tool.get("uv").and_then(|i| i.as_table()) {
                    if let Some(sources) = uv.get("sources").and_then(|i| i.as_table()) {
                        for (k, v) in sources.iter() {
                            if is_workspace_true_source(v) {
                                to_remove.push(k.to_string());
                            }
                        }
                    }
                }
            }
            to_remove
        };

        if keys_to_remove.is_empty() {
            // Nothing to strip.
            return Ok(());
        }

        // Remove each workspace-true source entry, then prune empty parents.
        for key in &keys_to_remove {
            // Walk to [tool][uv][sources] with mutable borrow; remove leaf.
            if let Some(tool) = doc.get_mut("tool").and_then(|i| i.as_table_mut()) {
                if let Some(uv) = tool.get_mut("uv").and_then(|i| i.as_table_mut()) {
                    if let Some(sources) = uv.get_mut("sources").and_then(|i| i.as_table_mut()) {
                        sources.remove(key);
                    }
                }
            }
        }

        // Prune: remove [tool.uv.sources] if empty, then [tool.uv] if empty,
        // then [tool] if empty. Each step re-borrows immutably first to check,
        // then mutably to remove.
        prune_if_empty(&mut doc, &["tool", "uv", "sources"]);
        prune_if_empty(&mut doc, &["tool", "uv"]);
        prune_if_empty(&mut doc, &["tool"]);

        // Check if the document is now empty.
        if doc.as_table().is_empty() {
            std::fs::remove_file(path)
                .with_context(|| format!("removing empty {}", path.display()))?;
        } else {
            let out = doc.to_string();
            std::fs::write(path, out).with_context(|| format!("writing {}", path.display()))?;
        }
        Ok(())
    }
}

/// Returns true if the toml_edit item represents a `{workspace = true}` source.
///
/// Accepts both inline table (`{ workspace = true }`) and regular table
/// (`[tool.uv.sources.foo]\nworkspace = true`).
fn is_workspace_true_source(item: &toml_edit::Item) -> bool {
    let table = match item {
        toml_edit::Item::Value(toml_edit::Value::InlineTable(t)) => {
            return t
                .get("workspace")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
        }
        toml_edit::Item::Table(t) => t,
        _ => return false,
    };
    table
        .get("workspace")
        .and_then(|v| v.as_value())
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
}

/// Remove a nested key at `path` if it exists and is an empty table.
///
/// Checks (immutable borrow) whether the table at `path` is empty.
/// If so, removes it (mutable borrow). The two borrows are sequential,
/// which the borrow checker accepts.
fn prune_if_empty(doc: &mut toml_edit::DocumentMut, path: &[&str]) {
    if path.is_empty() {
        return;
    }
    // Immutable check: is the table at `path` empty?
    let is_empty = {
        let mut t: &toml_edit::Table = doc.as_table();
        let mut ok = true;
        for seg in &path[..path.len() - 1] {
            match t.get(*seg) {
                Some(toml_edit::Item::Table(sub)) => t = sub,
                _ => {
                    ok = false;
                    break;
                }
            }
        }
        if ok {
            match t.get(path[path.len() - 1]) {
                Some(toml_edit::Item::Table(sub)) => sub.is_empty(),
                _ => false,
            }
        } else {
            false
        }
    };

    if !is_empty {
        return;
    }

    // Mutable removal: walk to parent and remove the leaf.
    let mut t: &mut toml_edit::Table = doc.as_table_mut();
    for seg in &path[..path.len() - 1] {
        match t.get_mut(*seg) {
            Some(toml_edit::Item::Table(sub)) => t = sub,
            _ => return,
        }
    }
    t.remove(path[path.len() - 1]);
}

impl Integration for UvWorkspace {
    fn name(&self) -> &str {
        "uv-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(());
        }

        // Sort members for determinism.
        let mut members = paths;
        members.sort();

        // Greenfield detection: does the root pyproject.toml exist before we
        // write? Checked before merge_activate creates it.
        let path = ctx.output_dir.join("pyproject.toml");
        let is_greenfield = !path.exists();

        // Step 1: merge-activate the PRIMARY owned keys only (`members` and
        // greenfield `package = false`). These are the keys that carry the
        // `# managed by rwv` marker. Sources are handled in step 2.
        let primary_owned = Self::primary_owned_pairs(&members, is_greenfield);
        let _result: MergeResult = merge_activate::<TomlDoc>(&path, &primary_owned)
            .with_context(|| format!("merge-activate {}", path.display()))?;

        // Step 2: write `[tool.uv.sources].<dep> = { workspace = true }` for
        // each member via a direct toml_edit pass. Source entries do NOT carry
        // the marker (only `members` does) — see module doc.
        Self::set_workspace_sources(&path, &members)
            .with_context(|| format!("set-workspace-sources {}", path.display()))?;

        // `MergeResult.deferred` lists keys the user took the pen on.
        // Surfacing these as `Severity::Warning` issues is a C3 concern.
        // For now, silently defer — consistent with the pre-port behavior of
        // leaving hand-written sections alone.

        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        let path = root.join("pyproject.toml");
        if !path.exists() {
            return Ok(());
        }

        // Legacy fallback: files written by the old overwrite writer start with
        // the LEGACY_HEADER. Remove them whole (the old write-then-delete
        // behavior). This is a one-line deactivate path for the operator's
        // migration; it only fires on pre-port files. Per plan §7.1 and the
        // rwv-alpha-no-backcompat rule, this path has NO corresponding activate
        // equivalent.
        {
            let content = std::fs::read_to_string(&path)
                .with_context(|| format!("reading {}", path.display()))?;
            if content.starts_with(LEGACY_HEADER) {
                std::fs::remove_file(&path)
                    .with_context(|| format!("removing legacy {}", path.display()))?;
                return Ok(());
            }
        }

        // New path: strip_deactivate removes `members` (and prunes empty
        // [tool.uv.workspace]) gated on the per-key marker. Then the bespoke
        // adapter strips workspace-true sources.
        let owned_keys = Self::deactivate_owned_keys();
        strip_deactivate::<TomlDoc>(&path, &owned_keys)
            .with_context(|| format!("strip-deactivate {}", path.display()))?;

        // After strip_deactivate, the marker is gone and [tool.uv.workspace]
        // is pruned. Now strip only {workspace=true} entries from
        // [tool.uv.sources] (bespoke adapter — see module doc).
        Self::strip_workspace_sources(&path)
            .with_context(|| format!("strip-workspace-sources {}", path.display()))?;

        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(vec![]);
        }

        let mut issues = Vec::new();
        if which::which("uv").is_err() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: "uv is not on PATH".to_string(),
                safe_to_fix: true,
            });
        }
        Ok(issues)
    }

    fn activate_hook(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let paths = ctx.detect_repos_with_manifest("pyproject.toml");
        if paths.is_empty() {
            return Ok(());
        }

        // `uv sync` installs into `.venv` and refreshes `uv.lock`.
        // Runs from workspace_root for the same reason as the other ecosystem
        // hooks (activation symlinks are in place there so uv sees the
        // workspace the user sees).
        let status = std::process::Command::new("uv")
            .arg("sync")
            .current_dir(ctx.workspace_root)
            .status()
            .context("failed to run uv")?;

        if !status.success() {
            anyhow::bail!("uv sync failed (exit {})", status);
        }

        Ok(())
    }

    /// `uv.lock` is **fully-owned** — gitignore-eligible, whole-deletable.
    /// `pyproject.toml` is **hybrid** — it is in `managed_files()`, not here.
    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        if ctx.detect_repos_with_manifest("pyproject.toml").is_empty() {
            return vec![];
        }
        vec!["uv.lock".to_string()]
    }

    /// `pyproject.toml` is **hybrid** (rwv owns `[tool.uv.workspace].members`
    /// and the `{workspace=true}` entries in `[tool.uv.sources]`; the user
    /// owns everything else). It MUST NOT appear in `generated_files()` — that
    /// would mark it gitignore-eligible and whole-deletable, the exact
    /// data-loss bug the merge port fixes.
    fn managed_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        let mut files = self.generated_files(ctx);
        if !ctx.detect_repos_with_manifest("pyproject.toml").is_empty() {
            files.push("pyproject.toml".to_string());
        }
        files
    }
}

// ===========================================================================
// Unit tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_file(dir: &TempDir, name: &str, content: &str) -> std::path::PathBuf {
        let path = dir.path().join(name);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn is_workspace_true_recognises_inline_table() {
        // { workspace = true } inline table
        let toml = "[tool.uv.sources]\nfoo = { workspace = true }\n";
        let doc: toml_edit::DocumentMut = toml.parse().unwrap();
        let sources = doc["tool"]["uv"]["sources"].as_table().unwrap();
        let item = &sources["foo"];
        assert!(is_workspace_true_source(item));
    }

    #[test]
    fn is_workspace_true_rejects_git_source() {
        let toml =
            "[tool.uv.sources]\nbar = { git = \"https://example.com/bar.git\" }\n";
        let doc: toml_edit::DocumentMut = toml.parse().unwrap();
        let sources = doc["tool"]["uv"]["sources"].as_table().unwrap();
        let item = &sources["bar"];
        assert!(!is_workspace_true_source(item));
    }

    #[test]
    fn strip_workspace_sources_removes_workspace_true_leaves_git() {
        let tmp = TempDir::new().unwrap();
        let path = write_file(
            &tmp,
            "pyproject.toml",
            r#"[project]
name = "acme"

[tool.uv.sources]
server = { workspace = true }
some-private-lib = { git = "https://example.com/foo.git" }
"#,
        );

        UvWorkspace::strip_workspace_sources(&path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(!content.contains("workspace = true"), "ws=true must be gone");
        assert!(
            content.contains("some-private-lib"),
            "git source must survive"
        );
        assert!(
            content.contains("https://example.com/foo.git"),
            "git URL must survive"
        );
        assert!(content.contains("[project]"), "[project] must survive");
    }

    #[test]
    fn strip_workspace_sources_deletes_file_when_only_workspace_sources_remain() {
        let tmp = TempDir::new().unwrap();
        let path = write_file(
            &tmp,
            "pyproject.toml",
            "[tool.uv.sources]\nserver = { workspace = true }\n",
        );

        UvWorkspace::strip_workspace_sources(&path).unwrap();
        assert!(
            !path.exists(),
            "file with only workspace sources must be deleted"
        );
    }

    #[test]
    fn strip_workspace_sources_noop_when_no_workspace_true() {
        let tmp = TempDir::new().unwrap();
        let content =
            "[project]\nname = \"acme\"\n\n[tool.uv.sources]\nfoo = { git = \"x\" }\n";
        let path = write_file(&tmp, "pyproject.toml", content);

        UvWorkspace::strip_workspace_sources(&path).unwrap();
        let after = std::fs::read_to_string(&path).unwrap();
        assert_eq!(after, content, "noop: content must be unchanged");
    }

    #[test]
    fn primary_owned_pairs_greenfield_includes_package_false() {
        let pairs = UvWorkspace::primary_owned_pairs(&["github/a/server".to_string()], true);
        let has_package = pairs.iter().any(|(k, v)| {
            k == &keypath(["tool", "uv", "package"]) && *v == OwnedValue::Bool(false)
        });
        assert!(has_package, "greenfield must include package=false");
    }

    #[test]
    fn primary_owned_pairs_non_greenfield_no_package_key() {
        let pairs = UvWorkspace::primary_owned_pairs(&["github/a/server".to_string()], false);
        let has_package = pairs
            .iter()
            .any(|(k, _)| k == &keypath(["tool", "uv", "package"]));
        assert!(
            !has_package,
            "non-greenfield must NOT include package=false"
        );
    }

    #[test]
    fn primary_owned_pairs_does_not_include_sources() {
        // Sources are handled in the set_workspace_sources pass, not via
        // primary_owned_pairs — so the marker never appears on source entries.
        let pairs = UvWorkspace::primary_owned_pairs(&["github/acme/server".to_string()], false);
        let has_source = pairs
            .iter()
            .any(|(k, _)| k.len() >= 4 && k[2] == "sources");
        assert!(
            !has_source,
            "primary_owned_pairs must NOT include source keys (those go through set_workspace_sources)"
        );
    }
}
