use crate::integration::{Integration, IntegrationContext, Issue, Severity};
use std::path::Path;

/// Marker key written into generated `.code-workspace` files so that
/// `deactivate` can distinguish rwv-managed files from user-created ones.
const GENERATED_MARKER_KEY: &str = "rwv.generated";

pub struct VscodeWorkspace;

impl Integration for VscodeWorkspace {
    fn name(&self) -> &str {
        "vscode-workspace"
    }

    fn default_enabled(&self) -> bool {
        true
    }

    fn activate(&self, ctx: &IntegrationContext) -> anyhow::Result<()> {
        let filename = format!("{}.code-workspace", ctx.project.as_str());
        let filepath = ctx.output_dir.join(&filename);

        // Start with existing file content if present (for merge behavior)
        let mut obj: serde_json::Map<String, serde_json::Value> = if filepath.exists() {
            let content = std::fs::read_to_string(&filepath)?;
            serde_json::from_str(&content).unwrap_or_default()
        } else {
            serde_json::Map::new()
        };

        // Mark as generated by rwv so deactivate can identify managed files.
        obj.insert(
            GENERATED_MARKER_KEY.to_string(),
            serde_json::Value::Bool(true),
        );

        // Always overwrite folders
        let folder_name = format!("{} (primary)", ctx.project.as_str());
        obj.insert(
            "folders".to_string(),
            serde_json::json!([{ "path": ".", "name": folder_name }]),
        );

        // Merge settings: overwrite managed keys, preserve user keys
        let managed_settings: serde_json::Map<String, serde_json::Value> = serde_json::from_value(
            serde_json::json!({
                "git.autoRepositoryDetection": "subFolders",
                "git.repositoryScanMaxDepth": 3
            }),
        )
        .unwrap();

        let settings = obj
            .entry("settings".to_string())
            .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
        if let Some(settings_map) = settings.as_object_mut() {
            for (k, v) in managed_settings {
                settings_map.insert(k, v);
            }
        }

        let content = serde_json::to_string_pretty(&serde_json::Value::Object(obj))? + "\n";
        std::fs::write(&filepath, content)?;
        Ok(())
    }

    fn deactivate(&self, root: &Path) -> anyhow::Result<()> {
        // Remove only .code-workspace files that were generated by rwv
        // (identified by the presence of the generated marker key).
        if let Ok(entries) = std::fs::read_dir(root) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("code-workspace") {
                    continue;
                }
                if let Ok(content) = std::fs::read_to_string(&path) {
                    if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
                        if val.get(GENERATED_MARKER_KEY).and_then(|v| v.as_bool()) == Some(true)
                        {
                            std::fs::remove_file(path)?;
                        }
                    }
                }
            }
        }
        Ok(())
    }

    fn check(&self, ctx: &IntegrationContext) -> anyhow::Result<Vec<Issue>> {
        let filename = format!("{}.code-workspace", ctx.project.as_str());
        let filepath = ctx.output_dir.join(&filename);

        let mut issues = Vec::new();
        if !filepath.is_file() {
            issues.push(Issue {
                integration: self.name().to_string(),
                severity: Severity::Warning,
                message: format!("{} does not exist", filename),
            });
        }
        Ok(issues)
    }

    fn generated_files(&self, ctx: &IntegrationContext) -> Vec<String> {
        vec![format!("{}.code-workspace", ctx.project.as_str())]
    }
}
