//! `rwv setup` — generate workspace-level configuration files.
//!
//! Subcommands:
//! - `agents-md`: Generate/update `AGENTS.md` at the workspace root with the
//!   same content as `rwv prime`, for non-Claude agents (Cursor, Copilot, etc.)
//!   that read AGENTS.md.
//! - `claude`: Register `rwv prime` as a Claude Code hook in
//!   `~/.claude/settings.json` (SessionStart + PreCompact). Also installs
//!   WorktreeCreate/WorktreeRemove hook scripts to `~/.claude/hooks/` and
//!   registers them. Idempotent.

use crate::prime::render_context;
use crate::workspace::WorkspaceContext;
use anyhow::{bail, Context};
use serde_json::Value;
use std::path::{Path, PathBuf};

/// Header written to generated AGENTS.md so we can detect our own files.
const GENERATED_HEADER: &str = "<!-- Generated by rwv — do not edit -->";

/// Run `rwv setup agents-md` from the given working directory.
///
/// Generates (or updates) `AGENTS.md` at the workspace root.
/// Refuses to overwrite a file that does not contain the generated-file header.
pub fn agents_md(cwd: &Path) -> anyhow::Result<()> {
    let ctx = WorkspaceContext::resolve(cwd, None)?;
    let dest = ctx.root.join("AGENTS.md");

    // If the file already exists, only overwrite if it contains our header.
    if dest.exists() {
        let existing = std::fs::read_to_string(&dest)?;
        if !existing.contains(GENERATED_HEADER) {
            anyhow::bail!(
                "AGENTS.md exists at {} but was not generated by rwv. \
                 Remove it or add the header `{}` to allow rwv to manage it.",
                dest.display(),
                GENERATED_HEADER
            );
        }
    }

    let body = render_context(&ctx);
    let content = format!("{GENERATED_HEADER}\n\n{body}");

    std::fs::write(&dest, &content)?;
    eprintln!("wrote {}", dest.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// rwv setup claude
// ---------------------------------------------------------------------------

/// The command string registered as a hook.
const HOOK_COMMAND: &str = "rwv prime";

/// Hook events we register `rwv prime` under.
const HOOK_EVENTS: &[&str] = &["SessionStart", "PreCompact"];

/// The command registered for WorktreeCreate and WorktreeRemove hooks.
/// A single binary handles both events by reading `hook_event_name` from stdin JSON.
const WORKWEAVE_HOOK_COMMAND: &str = "rwv workweave --claude-hook";

/// Workweave hook events handled by `rwv workweave --claude-hook`.
const WORKWEAVE_HOOK_EVENTS: &[&str] = &["WorktreeCreate", "WorktreeRemove"];

/// Workweave hook scripts: (event, filename, embedded content).
/// Kept for reference / legacy callers; no longer installed by default.
#[allow(dead_code)]
const WORKWEAVE_HOOKS: &[(&str, &str, &str)] = &[
    (
        "WorktreeCreate",
        "rwv-workweave-create.sh",
        include_str!("../examples/hooks/rwv-workweave-create.sh"),
    ),
    (
        "WorktreeRemove",
        "rwv-workweave-remove.sh",
        include_str!("../examples/hooks/rwv-workweave-remove.sh"),
    ),
];

/// Resolve `~/.claude/settings.json`.
fn claude_settings_path() -> anyhow::Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME environment variable not set")?;
    Ok(Path::new(&home).join(".claude").join("settings.json"))
}

/// Resolve `~/.claude/hooks/` directory.
fn claude_hooks_dir() -> anyhow::Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME environment variable not set")?;
    Ok(Path::new(&home).join(".claude").join("hooks"))
}

/// Run `rwv setup claude`.
pub fn claude() -> anyhow::Result<()> {
    claude_inner(&claude_settings_path()?, &claude_hooks_dir()?)
}

/// Implementation that accepts explicit paths (for testing).
pub fn claude_at(settings_path: &Path, hooks_dir: &Path) -> anyhow::Result<()> {
    claude_inner(settings_path, hooks_dir)
}

fn claude_inner(settings_path: &Path, _hooks_dir: &Path) -> anyhow::Result<()> {
    if !settings_path.exists() {
        bail!(
            "{} does not exist. Please run Claude Code at least once to create it.",
            settings_path.display()
        );
    }

    // Read and parse settings.json.
    let content = std::fs::read_to_string(settings_path)
        .with_context(|| format!("failed to read {}", settings_path.display()))?;
    let mut root: Value = serde_json::from_str(&content)
        .with_context(|| format!("invalid JSON in {}", settings_path.display()))?;

    let hooks = root
        .as_object_mut()
        .context("settings.json root is not an object")?
        .entry("hooks")
        .or_insert_with(|| Value::Object(serde_json::Map::new()));

    let hooks_obj = hooks
        .as_object_mut()
        .context("\"hooks\" is not an object")?;

    let mut changed = false;

    // Register `rwv prime` for SessionStart + PreCompact.
    for &event in HOOK_EVENTS {
        if ensure_command_hook_registered(hooks_obj, event, HOOK_COMMAND) {
            changed = true;
        }
    }

    // Register `rwv workweave --claude-hook` for WorktreeCreate + WorktreeRemove.
    // The same command handles both events by reading hook_event_name from stdin JSON.
    for &event in WORKWEAVE_HOOK_EVENTS {
        if ensure_command_hook_registered(hooks_obj, event, WORKWEAVE_HOOK_COMMAND) {
            changed = true;
        }
    }

    if changed {
        let output = serde_json::to_string_pretty(&root)?;
        std::fs::write(settings_path, format!("{output}\n"))
            .with_context(|| format!("failed to write {}", settings_path.display()))?;
        println!("Registered rwv hooks in {}", settings_path.display());
    } else {
        println!("rwv hooks up to date — nothing to do.");
    }

    Ok(())
}

/// Ensure `command` is present in the hook array for `event`.
/// Returns `true` if the array was modified.
fn ensure_command_hook_registered(
    hooks: &mut serde_json::Map<String, Value>,
    event: &str,
    command: &str,
) -> bool {
    let entries = hooks
        .entry(event.to_string())
        .or_insert_with(|| Value::Array(vec![]));

    let arr = match entries.as_array_mut() {
        Some(a) => a,
        None => return false, // unexpected shape — leave it alone
    };

    // Already present in any group?
    for group in arr.iter() {
        if group_contains_command(group, command) {
            return false;
        }
    }

    // Append to existing catch-all group (matcher == ""), or create one.
    let hook_entry = serde_json::json!({
        "type": "command",
        "command": command
    });

    let catchall = arr.iter_mut().find(|g| {
        g.get("matcher")
            .and_then(|m| m.as_str())
            .map(|m| m.is_empty())
            .unwrap_or(false)
    });

    match catchall {
        Some(group) => {
            if let Some(hooks_arr) = group.get_mut("hooks").and_then(|h| h.as_array_mut()) {
                hooks_arr.push(hook_entry);
            }
        }
        None => {
            arr.push(serde_json::json!({
                "matcher": "",
                "hooks": [hook_entry]
            }));
        }
    }

    true
}

/// Check whether a matcher-group already contains the given command.
fn group_contains_command(group: &Value, command: &str) -> bool {
    group
        .get("hooks")
        .and_then(|h| h.as_array())
        .map(|hooks| {
            hooks.iter().any(|h| {
                h.get("command")
                    .and_then(|c| c.as_str())
                    .map(|c| c == command)
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_workspace(parent: &Path, name: &str) -> PathBuf {
        let root = parent.join(name);
        std::fs::create_dir_all(root.join("github")).unwrap();
        std::fs::create_dir_all(root.join("projects")).unwrap();
        root
    }

    fn write_manifest(root: &Path, project: &str, yaml: &str) {
        let dir = root.join("projects").join(project);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("rwv.yaml"), yaml).unwrap();
    }

    /// Helper: call claude_at with a temp hooks_dir alongside the settings file.
    fn claude_at_tmp(settings_path: &Path) -> anyhow::Result<()> {
        let hooks_dir = settings_path.parent().unwrap().join("hooks");
        claude_at(settings_path, &hooks_dir)
    }

    #[test]
    fn agents_md_creates_file() {
        let tmp = tempfile::tempdir().unwrap();
        let root = make_workspace(tmp.path(), "ws");
        write_manifest(&root, "demo", "repositories: {}\n");
        std::fs::write(root.join(".rwv-active"), "demo\n").unwrap();

        agents_md(&root).unwrap();

        let path = root.join("AGENTS.md");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with(GENERATED_HEADER));
        assert!(content.contains("# repoweave workspace"));
        assert!(content.contains("**Project**: `demo`"));
    }

    #[test]
    fn agents_md_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let root = make_workspace(tmp.path(), "ws");
        write_manifest(&root, "demo", "repositories: {}\n");
        std::fs::write(root.join(".rwv-active"), "demo\n").unwrap();

        agents_md(&root).unwrap();
        let first = std::fs::read_to_string(root.join("AGENTS.md")).unwrap();

        // Run again — should succeed and produce same content.
        agents_md(&root).unwrap();
        let second = std::fs::read_to_string(root.join("AGENTS.md")).unwrap();

        assert_eq!(first, second);
    }

    #[test]
    fn agents_md_refuses_hand_edited() {
        let tmp = tempfile::tempdir().unwrap();
        let root = make_workspace(tmp.path(), "ws");
        write_manifest(&root, "demo", "repositories: {}\n");
        std::fs::write(root.join(".rwv-active"), "demo\n").unwrap();

        // Write a hand-edited AGENTS.md (no generated header).
        std::fs::write(root.join("AGENTS.md"), "# My custom agents doc\n").unwrap();

        let err = agents_md(&root).unwrap_err();
        assert!(err.to_string().contains("not generated by rwv"));
    }

    #[test]
    fn agents_md_overwrites_generated() {
        let tmp = tempfile::tempdir().unwrap();
        let root = make_workspace(tmp.path(), "ws");
        write_manifest(&root, "demo", "repositories: {}\n");
        std::fs::write(root.join(".rwv-active"), "demo\n").unwrap();

        // Write a previously-generated AGENTS.md with stale content.
        std::fs::write(
            root.join("AGENTS.md"),
            format!("{GENERATED_HEADER}\n\n# old stale content\n"),
        )
        .unwrap();

        agents_md(&root).unwrap();

        let content = std::fs::read_to_string(root.join("AGENTS.md")).unwrap();
        assert!(content.contains("# repoweave workspace"));
        assert!(!content.contains("old stale content"));
    }

    // -- claude subcommand tests ------------------------------------------------

    #[test]
    fn claude_errors_if_settings_missing() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        let result = claude_at_tmp(&path);
        assert!(result.is_err());
        assert!(
            result.unwrap_err().to_string().contains("does not exist"),
            "should mention file does not exist"
        );
    }

    #[test]
    fn claude_adds_hooks_to_empty_settings() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        std::fs::write(&path, "{}").unwrap();

        claude_at_tmp(&path).unwrap();

        let content: Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        // rwv prime registered for SessionStart + PreCompact
        for event in HOOK_EVENTS {
            let arr = content["hooks"][event].as_array().unwrap();
            assert!(!arr.is_empty(), "{event} should have hooks");
            let found = arr.iter().any(|g| {
                g["hooks"]
                    .as_array()
                    .map(|hs| {
                        hs.iter()
                            .any(|h| h["command"].as_str() == Some(HOOK_COMMAND))
                    })
                    .unwrap_or(false)
            });
            assert!(found, "{event} should contain rwv prime");
        }

        // Workweave hook events registered with rwv workweave --claude-hook
        for &event in WORKWEAVE_HOOK_EVENTS {
            assert!(
                content["hooks"][event].as_array().is_some(),
                "{event} should be registered"
            );
        }
    }

    #[test]
    fn claude_does_not_install_hook_scripts() {
        // rwv setup claude no longer installs shell scripts — it registers
        // `rwv workweave --claude-hook` directly in settings.json.
        let tmp = tempfile::tempdir().unwrap();
        let settings_path = tmp.path().join("settings.json");
        let hooks_dir = tmp.path().join("hooks");
        std::fs::write(&settings_path, "{}").unwrap();

        claude_at(&settings_path, &hooks_dir).unwrap();

        // hooks_dir should NOT have been created (no scripts to install).
        assert!(
            !hooks_dir.exists(),
            "hooks_dir should not be created when using --claude-hook"
        );
    }

    #[test]
    fn claude_workweave_hooks_registered_in_settings() {
        let tmp = tempfile::tempdir().unwrap();
        let settings_path = tmp.path().join("settings.json");
        let hooks_dir = tmp.path().join("hooks");
        std::fs::write(&settings_path, "{}").unwrap();

        claude_at(&settings_path, &hooks_dir).unwrap();

        let content: Value =
            serde_json::from_str(&std::fs::read_to_string(&settings_path).unwrap()).unwrap();

        for &event in WORKWEAVE_HOOK_EVENTS {
            let arr = content["hooks"][event]
                .as_array()
                .unwrap_or_else(|| panic!("{event} should be present"));
            let found = arr.iter().any(|g| {
                g["hooks"]
                    .as_array()
                    .map(|hs| {
                        hs.iter()
                            .any(|h| h["command"].as_str() == Some(WORKWEAVE_HOOK_COMMAND))
                    })
                    .unwrap_or(false)
            });
            assert!(found, "{event} should contain command {WORKWEAVE_HOOK_COMMAND}");
        }
    }

    #[test]
    fn claude_appends_to_existing_catchall() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        std::fs::write(
            &path,
            serde_json::to_string_pretty(&serde_json::json!({
                "hooks": {
                    "SessionStart": [
                        {
                            "matcher": "",
                            "hooks": [
                                { "type": "command", "command": "bd prime" }
                            ]
                        }
                    ]
                }
            }))
            .unwrap(),
        )
        .unwrap();

        claude_at_tmp(&path).unwrap();

        let content: Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        // SessionStart: appended to existing catch-all
        let session_hooks = content["hooks"]["SessionStart"][0]["hooks"]
            .as_array()
            .unwrap();
        assert_eq!(session_hooks.len(), 2);
        assert_eq!(session_hooks[0]["command"], "bd prime");
        assert_eq!(session_hooks[1]["command"], HOOK_COMMAND);

        // PreCompact: new group created
        let pre_compact = content["hooks"]["PreCompact"].as_array().unwrap();
        assert_eq!(pre_compact.len(), 1);
    }

    #[test]
    fn claude_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        std::fs::write(&path, "{}").unwrap();

        claude_at_tmp(&path).unwrap();
        let first = std::fs::read_to_string(&path).unwrap();

        claude_at_tmp(&path).unwrap();
        let second = std::fs::read_to_string(&path).unwrap();

        assert_eq!(first, second, "second run should not change the file");
    }

    #[test]
    fn claude_idempotent_across_groups() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        // rwv prime already in a non-catch-all group
        std::fs::write(
            &path,
            serde_json::to_string_pretty(&serde_json::json!({
                "hooks": {
                    "SessionStart": [
                        {
                            "matcher": "special",
                            "hooks": [
                                { "type": "command", "command": HOOK_COMMAND }
                            ]
                        }
                    ]
                }
            }))
            .unwrap(),
        )
        .unwrap();

        claude_at_tmp(&path).unwrap();

        let content: Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let session_arr = content["hooks"]["SessionStart"].as_array().unwrap();
        assert_eq!(session_arr.len(), 1, "should not add a second group");

        // PreCompact should have been added
        assert!(content["hooks"]["PreCompact"].as_array().is_some());
    }

    #[test]
    fn claude_preserves_other_settings() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("settings.json");
        std::fs::write(
            &path,
            serde_json::to_string_pretty(&serde_json::json!({
                "attribution": { "commit": "" },
                "permissions": { "defaultMode": "bypassPermissions" }
            }))
            .unwrap(),
        )
        .unwrap();

        claude_at_tmp(&path).unwrap();

        let content: Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(content["attribution"]["commit"], "");
        assert_eq!(content["permissions"]["defaultMode"], "bypassPermissions");
        assert!(content["hooks"]["SessionStart"].as_array().is_some());
    }
}
